### ISSUE TITLE
@Tested/@Injectable does not support custom annotations when also using standard DI annotations

### ISSUE THREAD

**Issue by henryken** [jmockit/jmockit1#124]
Hi,

When upgrading from v1.9 to v1.14, the @Injectable is not working for non-javax annotated field.
This issue seems have been found few months ago (http://stackoverflow.com/questions/26683962/why-is-there-a-npe-on-injectable-class)

In the code below, the "clock" can be injected properly.
However, trialReadyTemplate and trialReadyTimer are not injected.

I'm using TestNG and Java 8.
The current workaround is to use reflection at the beginning of the test method.

```
@Service
public class TrialServerServiceImpl implements TrialServerService {

    @Resource
    private Clock clock;

    @Produce(uri = "direct:trial-ready")
    private ProducerTemplate trialReadyTemplate;

    @Metric(name = "trial.ready")
    private Timer trialReadyTimer;
}



public class TrialServerServiceImplTest {

    @Tested
    private TrialServerServiceImpl trialServerService;

    @Injectable
    private Clock clock;

    @Injectable
    private ProducerTemplate trialReadyTemplate;

    @Injectable
    private Timer trialReadyTimer;
}
```

**Comment by rliesenfeld** [comment]
It will work if @Resource is not used here. Is there a reason why it was used, without a name being provided?

**Comment by henryken** [comment]
It's used for dependency injection.
It doesn't have a "name" because it follows the name of the attribute.

Also, @Produce and @Metric will inject Spring beans.

**Comment by rliesenfeld** [comment]
Ok. The problem here is that the presence of @Resource (one of the "standard" DI annotations, together with @Inject and @Autowired) put JMockit in "annotations-only" mode, where only fields that use the standard annotations are regarded as injection points. I thought that Spring would not accept other annotations on their own (ie, without also using @Inject, @Resource, or @Autowired).

Do you happen to know where this behavior is mentioned in the Spring framework documentation?

**Comment by henryken** [comment]
I don't think that limiting the injection to those 3 annotations is the correct approach.
There are lots of other third party libraries and annotations which rely on Spring injection to provide the correct dependencies, e.g. in my case
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Produce.html
https://github.com/ryantenney/metrics-spring

Those libraries are supposed to work with Spring, so there is no reason to limit the presence of the injection annotations.

**Comment by rliesenfeld** [comment]
Hmm, actually, those other libraries which integrate with Spring and do their own injection are doing it the wrong way. All DI frameworks (Spring, Guice, CDI/JavaEE) adopted the rule (when using annotation-driven DI) that *all* injection points must use one of a set of standardized DI annotations (@javax.inject.Inject in the official Java standard for DI; one of @Inject, @Resource, @PersistenceContext, or @PersistenceUnit in Java EE; @Inject, @Autowired, or @Value in Spring).

The *correct* way would be to require use of @Inject together with a custom @Qualifier annotation. They would still have their own annotations (such as @Produce), the only difference being that @Inject (or @Autowired) would *also* be applied to each field. This would comply with the rule adopted by javax.inject, Spring, etc., and which JMockit attempts to follow.

That said, given the fact that other libraries decided to not support standardized DI, I will try and regard *any* runtime field annotation as marking an injection point. This should work well in practice.
