### ISSUE TITLE
Ant build fails out of the box

### ISSUE THREAD

**Issue by daviderickson** [jmockit/jmockit1#150]
```
ubuntu:~/git/jmockit1$ ant createjars
Buildfile: git/jmockit1/build.xml
  [taskdef] Could not load definitions from resource testngtasks. It could not be found.

BUILD FAILED
git/jmockit1/build.xml:10: taskdef class org.jacoco.ant.ReportTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```

Looks like the problem is in build.xml:
```
   <taskdef
      name="jacocoReport" classname="org.jacoco.ant.ReportTask"
      classpath="../../Java/jacoco-0.7.3/lib/jacocoant.jar"/>
```
it is pointing to a classpath that is outside of the project.

The testngtasks is also failing, it is pointing to:
```
 <taskdef resource="testngtasks" classpath="lib/testng-6.8.jar"/>
```

And there is no lib folder in the repo either. If these are required to build please package them into the repo.

**Comment by rliesenfeld** [comment]
Yes, this is normal, as there is no Ant build for the project. Building is done with Maven, using main/pom.xml and coverage/pom.xml. The targets in build.xml are just a bunch of convenience utilities for project developers, used to produce artifacts (basically, the "full distribution" zip file) for non-Maven users.
