### ISSUE TITLE
Verification argument capture uses actual object not copy

### ISSUE THREAD

**Issue by bcolvin** [jmockit/jmockit1#157]
I'm trying to test whether a method gets called with a specific field set, right after in the actual method being tested the field is set to null.

Example:
```
User user = new User();
user.setName("Bob");
cleanName(user); //attempting to capture the user at this point and verify name is set
user.setName(null);
return user;
```
```
new Verifications(){{
User arg = null;
someTestedClass.cleanName(arg=withCapture());
assertEquals("Bob",arg.getName()); // fails expected "Bob" actual <null>
}};
```
Is there another way of getting around this issue? Or was this the designed behavior? If the intention is to preserve the objects state at the time of invocation perhaps copying it to a new object would be better?

**Comment by rliesenfeld** [comment]
Yes, this is the designed behavior: argument capture simply copies the argument value (an object reference, in this case); it does not attempt to do a "deep copy" of the referenced object.

You can write the test with a recorded argument matcher, though:

    @Tested @Mocked SomeTestedClass someTestedClass;

    @Test
    public void someTest() {
        new Expectations() {{
            someTestedClass.cleanName(with(new Delegate<User>() {
                void validateName(User arg) { assertEquals("Bob", arg.getName()); }
            }));
        }};

        someTestedClass.someTestedMethod();
    }

There is also a "withArgThat(Matcher)" variant, which allows the use of arbitrary Hamcrest matchers (there is a "hasProperty" matcher for cases like this, if I remember correctly).

**Comment by bcolvin** [comment]
Awesome thanks!
