### ISSUE TITLE
Lambdas in Expectations

### ISSUE THREAD

**Issue by GilraenBurland** [jmockit/jmockit1#164]
Hi there.

I have some problems with Lambdas in Expectations.

I want to do something like this:

```
public MyClassTest {
    
    @Tested MyClass subject;
    @Injectable SomeClass someClass;

    @Test
    public void testWithLambda() {
        Supplier<String> lambda = someClass:someMethod;
        new Expectations() {{
            lambda.get();
        }};
    }

}
````

But I currently get an IllegalArgumentException saying:
`No class with name "MyClassTest$$Lambda$1/329611835 found."`

If I do this `Startup.retransformClass(lambda.getClass())` before the Expectations block, then I get a ClassNotFoundException:
`MyClassTest$$Lambda$1`

Any ideas how to solve this?

Thanks in advance.

**Comment by rliesenfeld** [comment]
Expectations are meant to be recorded/verified directly on the methods and constructors that are mocked. So, you would write "someClass.someMethod()" instead of "lambda.get()". Any reason why that can't be done?

**Comment by GilraenBurland** [comment]
Well I was trying to write a wrapper around jmockit which should use method references.
But then it seems, that it is not possible, thanks for the clarification :)
