### ISSUE TITLE
withCapture() not working on private methods in partial mocks

### ISSUE THREAD

**Issue by thwaerte** [jmockit/jmockit1#169]
In a partial mock, I want to capture a parameter value on a private method. If the method has an Integer (or primitive int) parameter and the captured is a String after that, a ClassCastException is raised. In other cases, the captured value is taken from the wrong actual parameter, for example if both parameters are an Integer.

```java
public class A {

    public void somePublicMethod() {
        somePrivateMethod(42, "SomeString");
    }

    private void somePrivateMethod(final int i, final String s) {
        //
    }
}
```

```java
public class ATest {

    @Tested
    A tested;

    @Test
    public void test() {

        new NonStrictExpectations(tested) {
            {
                Deencapsulation.invoke(tested, "somePrivateMethod", new Class[] { Integer.class, String.class }, anyInt, anyString);
            }
        };

        tested.somePublicMethod();

        new Verifications() {
            {
                String s;
                Deencapsulation.invoke(tested, "somePrivateMethod", new Class[] { Integer.class, String.class },
                        Integer.valueOf(42), s = withCapture());
                assertEquals("SomeString", s);
            }
        };
    }
}
```

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at ATest$2.<init>(ATest.java:42)
	at ATest.test(ATest.java:39)
```

**Comment by rliesenfeld** [comment]
Ok. The test fails simply because "withCapture()" is not supported when calling the mocked method indirectly through Reflection; it's only supported on direct method calls.

Mocking of private methods is rarely done (as it should be), so this is not an enhancement that I am willing to make. If somebody else offers a Pull Request for it, though, it might get in.

**Comment by thwaerte** [comment]
I see, thanks for your answer. I might have a look into that enhancement myself.

**Comment by bezuiden** [comment]
I would like to see the feature for capturing values of a private method in the verification stage.  I don't want to mock the private method, but I want to see if it was called with the expected arguments.  Maybe there is a way to do this already (new to jmockit)
