### ISSUE TITLE
$advice not mentinated in the Tutorial

### ISSUE THREAD

**Issue by hontvari** [jmockit/jmockit1#172]
The special $advice mock method is not mentioned in the Tutorial. It is in the Change history and JavaDoc.

**Comment by rliesenfeld** [comment]
Well, yes, it's not mentioned. The tutorial is not really meant to be comprehensive, but to cover the common use cases that people are expected to find. And "$advice" is an advanced feature which still lacks "common" use cases, so for now I would prefer to keep it in the API documentation only.

**Comment by hontvari** [comment]
At the end I found that it is better to implement the test case in question without $advice, which may further confirm your assumption.

**Comment by josefbetancourt** [comment]
I know this issue is closed, but like to mention that I wrote something on how AOP and test mocking relate:  "Use AOP Aspects as Mocks in JUnit tests?", http://octodecillion.com/blog/aop-advice-as-mocks/

**Comment by rliesenfeld** [comment]
Interesting article. Indeed, test isolation can be solved with the use of AOP tools.

I actually first looked at AOP during JMockit's inception, back in late 2005. The JBoss AOP tutorial has an entire chapter devoted to testing: http://docs.jboss.org/jbossaop/docs/2.0.0.GA/docs/aspect-framework/userguide/en/html/testing.html. I once had a sample test suite based on this, with the equivalent test using JMockit which, needless to say, was quite a bit simpler.

Personally, I could never find a compelling real-world use for AOP, that could not be better solved through other means (Java EE, Spring, good architecture).
