### ISSUE TITLE
Add Expectations.throws() to complement Expectations.returns()

### ISSUE THREAD

**Issue by bcalmac** [jmockit/jmockit1#178]
Return values can currently be specified in two ways:

    result  = "some result";
    returns("some result");

Thrown exceptions on the other hand can only be specified with:

    result = new Exception("some exception");

For consistency, it would be good to add `Expectations.throws()`. If one prefers the `returns(...)` style, it's awkward to resort to `result = ...` for thrown exceptions.

**Comment by rliesenfeld** [comment]
"throws" is a Java keyword, so it's not possible to create a "throws" method.

**Comment by bcalmac** [comment]
The name is not important. Something similar. Wouldn't you say that currently it's not consistent?

**Comment by rliesenfeld** [comment]
Yes, it's a small inconsistency. But you propose to add yet *another* inconsistency, by having another way to record exceptions to be thrown, in addition to "result = new XyzException()"?

As a matter of fact, there *is* a solution here, which is to remove the "returns" method; then the recording API would be more consistent. However, at this point it's not an acceptable change for JMockit 1.x, given that many tests were (probably) already written with "returns".

**Comment by bcalmac** [comment]
All right. If we look at returns() as deprecated the it's all good.
