### ISSUE TITLE
if a line is present in an Expectations block, then it can be omitted in FullVerificationsInOrder block

### ISSUE THREAD

**Issue by fedeolto** [jmockit/jmockit1#180]
I encountered following scenario:

This gist contains few classes I wrote to reproduce the problem https://gist.github.com/fedeolto/d2b0036ac3708f09a8ce

In this domain Television and Cable classes are manipulated by Person class in order to watchTv(). 
In particular, at a certain point, Person ensures cable.isPluggedInCorrectly(); before turn on tv.

In PersonTest.class I commented line 28 just to "test the test" and surprisingly it is still green. If I exchange order between lines 28 and 29 for example, it brokes, but it seems like the expectation act as a full ordered verification.

Reading initial four lines of the tutorial http://jmockit.org/tutorial/BehaviorBasedTesting.html#verification
I assumed that this behaviour takes place only in presence of a strict expectation block, not plain expectations one.
Is it a bug?

**Comment by rliesenfeld** [comment]
It's not a bug. Expectations that get verified *implicitly* don't need to be accounted for in a "full" verification block. Any recorded expectation with a minimum invocation count of one or more is verified implicitly, whether the constraint is specified explicitly or assumed by default (a regular expectation recorded in a "Expectations" block has a default "minTimes" of 1).

The section on "Full verification" mentions this, although it may not be as clear as it should: http://jmockit.org/tutorial/BehaviorBasedTesting.html#fullVerification

**Comment by fedeolto** [comment]
wow! Setting minTimes=0; broke the test as I was expecting:

new Expectations() {{
            cable.isPluggedInCorrectly();
            minTimes=0;
            result = true;
        }};

me and other members of my team use Expectations only to prepare data for
the test, we focus controls in *Verifications* block, so since now we
should put minTimes=0; in every Expectation line to be sure that if we
forget a Verification line the test get red. This will make our tests a
little bit more verbose but it fix the situation.
Thank you very much for the answer and for developing JMockit, we are
enthusiast!



On Wed, Jun 3, 2015 at 5:15 PM, Rogério Liesenfeld <notifications@github.com
> wrote:

> It's not a bug. Expectations that get verified *implicitly* don't need to
> be accounted for in a "full" verification block. Any recorded expectation
> with a minimum invocation count of one or more is verified implicitly,
> whether the constraint is specified explicitly or assumed by default (a
> regular expectation recorded in a "Expectations" block has a default
> "minTimes" of 1).
>
> The section on "Full verification" mentions this, although it may not be
> as clear as it should:
> http://jmockit.org/tutorial/BehaviorBasedTesting.html#fullVerification
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jmockit/jmockit1/issues/180#issuecomment-108479195>.
>



-- 
Federica Oltolina
homepage: http://federicaoltolina.altervista.org
