### ISSUE TITLE
ArrayIndexOutOfBoundsException for no reason

### ISSUE THREAD

**Issue by dparvath** [jmockit/jmockit1#186]
I'm seeing an ArrayIndexOutOfBoundsException during Jmockit tests while using Jacoco. When both the JaCoCo and JMockit javaagents are configured in the maven surefire plugin, then I get ArrayIndexOutOfBoundsExceptions for no apparent reason while running unit tests. If I remove the JaCoCo javaagent then the tests pass. Likewise, if I run the junit testcases in eclipse its working fine for me.
 Many testcases are failing with this issue where there is no chance to get ArrayIndexOutOfBoundsExceptions  while running in SONAR using JACOCO for Junit coverage

java.lang.Exception: Unexpected exception, expected<com.xxx.caps.services.RegistrationException> but was<java.lang.ArrayIndexOutOfBoundsException>
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 152
	at com.xxx.caps.validator.RegisterLoanValidator.debug(RegisterLoanValidator.java:543)
	at com.xxx.caps.validator.RegisterLoanValidator.validate(RegisterLoanValidator.java:157)
	at com.xxx.caps.validator.test.TestRegisterLoanValidator.validate_BorrLastNameIsNull(TestRegisterLoanValidator.java

debug method in RegisterLoanValidator
private void debug(String string) {
		if(logger.isDebugEnabled()){
			logger.debug(string);
		}
	}

**Comment by marcdonovan** [comment]
JPMC - I worked there for 12 years.

You need to post source code that demonstrates the problem.

**Comment by dparvath** [comment]
marc,I updated my comment.can you please check now
also can you please edit your post to remove company name :)

**Comment by dparvath** [comment]
http://sourceforge.net/p/eclemma/bugs/121/

I am facing the same issue.Can somebody please help?

**Comment by marcdonovan** [comment]
This was fixed a long time ago. Upgrade your JMockit. http://repo.maven.apache.org/maven2/org/jmockit/jmockit/1.9/

**Comment by dparvath** [comment]
Thanks marc,i will try it and update you.
Also can we use jmockit1.9.jar with jdk1.6 version

**Comment by marcdonovan** [comment]
http://jmockit.org/gettingStarted.html

6 or better

**Comment by dparvath** [comment]
Marc,
I used jmockit1.9.jar and getting below exceptions now

java.lang.instrument.IllegalClassFormatException: Error while instrumenting class com/xxx/caps/dao/PosWorkflowMgmtDAOImpl.
    [junit] 	at org.jacoco.agent.rt_szlt7q.CoverageTransformer.transform(CoverageTransformer.java:69)
    [junit] 	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
    [junit] 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:150)
    [junit] 	at mockit.internal.startup.Startup.redefineMethods(Startup.java:286)
    [junit] 	at mockit.internal.startup.Startup.redefineMethods(Startup.java:280)
    [junit] 	at mockit.internal.mockups.MockClassSetup.applyClassModifications(MockClassSetup.java:102)
    [junit] 	at mockit.internal.mockups.MockClassSetup.redefineMethodsInClassHierarchy(Mo

All testcases are failing with the above error.
Can you please let me know the issue.

**Comment by dparvath** [comment]
I upgraded jacocoagent.jar and jacocoant.jar and getting below exceptions now

 java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
    [junit] 	at com.jpmc.caps.delegate.TestWorkQueueDelegate$2.<init>(TestWorkQueueDelegate.java:246)
    [junit] 	at com.xxx.caps.delegate.TestWorkQueueDelegate.mocking(TestWorkQueueDelegate.java:246)
    [junit] 	at com.xxx.caps.delegate.TestWorkQueueDelegate.setUp(TestWorkQueueDelegate.java:44)

**Comment by rliesenfeld** [comment]
You will have to provide an example test which reproduces the problem, including also a minimal pom.xml with the jacoco configuration.

**Comment by dparvath** [comment]
<jacoco:coverage destfile="${basedir}/@{project}/jacoco-reports/jacoco.exec" excludes="${CODE_COVERAGE_CLASSES_EXCLUSION}">
				<junit fork="true" forkmode="once" printsummary="true" dir=".">
					<classpath refid="testlibPath" />
					<classpath>
						<pathelement path="${basedir}/@{project}/test"/>
						<pathelement path="${basedir}/@{project}"/>
					</classpath>					
					<classpath>
						<dirset dir="${build.dir}">
						   	<include name="*"/>
						</dirset>
					</classpath>
					<classpath>
						<dirset dir="${test.projects.build}">
							<include name="*"/>
						</dirset>
					</classpath>
					<formatter type="xml" />
					<batchtest todir="${basedir}/@{project}/jacoco-reports/test-reports" errorProperty="test.failed" failureProperty="test.failed" unless="testcase">
						<fileset dir="${basedir}/@{project}/test">
							<include name="**/*Test.java" />
							<include name="**/*Test*.java" />
							<include name="**/test/*.java" />
						</fileset>
					</batchtest>
					<formatter type="brief" usefile="false"/>
					<jvmarg value="${agentvmparam}" />
				</junit>
			</jacoco:coverage>

@rliesenfeld Thats My ant task 
When i am using older version of jmockit.jar i was getting the intial ArrayIndexOutOfBoundsException for no reason.
After upgrading it to 1.9 version i am getting IllegalClassFormatException.
I upgraded to advanced version of jacocoant.jar an jacocoagent.jar ane getting the UnsupportedOperationException

Can somebody please help?
