### ISSUE TITLE
Using jmockit, how to avoid the impact between two cases?

### ISSUE THREAD

**Issue by swingboat** [jmockit/jmockit1#188]
I have two classes, the first class:

public class FirstClass {
    private static final Logger LOG = Logger.getLogger(FirstClass.class);

    public void action(){
        LOG.info("FirstClass.action.");
    }
}
the second class:

public class SecondClass {
    private static final Logger LOG = Logger.getLogger(SecondClass.class);

    public void action(){
        FirstClass firstClass = new FirstClass();
        firstClass.action();
    }
}
I will write unit test for these two classes, the first class unit test:

public class FirstClassTest {
    @Test
    public void testAction(){
        FirstClass firstClass = new FirstClass();
        firstClass.action();
    }
}
the second class unit test:

public class SecondClassTest {
    @Mocked
    private Logger LOG;

    @Mocked
    private FirstClass firstClass;

    @Test
    public void testAction(){
        SecondClass secondClass = new SecondClass();
        secondClass.action();
    }
}  
About the second class unit test, As the second class depend on the first class, so I mocked the first class, at same time I also mocked Logger class.

I add a suite class to run these two classes:

@RunWith(Suite.class)
@Suite.SuiteClasses({SecondClassTest.class ,FirstClassTest.class})
public class TestAll {
}
When I run this suite class, it throw the follow exception:

java.lang.NullPointerException
at org.apache.log4j.Category.info(Category.java:663)
at steve.test.jmockit.issues.mocklog4j.FirstClass.action(FirstClass.java:12)
at steve.test.jmockit.issues.mocklog4j.FirstClassTest.testAction(FirstClassTest.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
From this trace log, the LOG of first class has been mocked. but in fact I don't mock Logger in FirstClassTest class.

But when I changed this suite class, firstly run FirstClassTest.class, and then run SecondClassTest.class. all cases are successful.

@RunWith(Suite.class)
@Suite.SuiteClasses({FirstClassTest.class ,SecondClassTest.class})
public class TestAll {
}
How to fix this issue and ensure that there is no effect between the two cases? Thanks!

**Comment by swingboat** [comment]
public class SecondClassTest {
@Mocked
private Logger LOG;

@Mocked
private FirstClass firstClass;

@Test
public void testAction(){
    SecondClass secondClass = new SecondClass();
    secondClass.action();
}
}

Firstly the 'Logger' is mocked, the 'FirstClass' is mocked too.  so the "FirstClass.LOG" will be mocked. Because the 'FirstClass.LOG' is static field, when run FirstClassTest.class and execute 'LOG.info("FirstClass.action.")', the field 'LOG' is mocked instance, but the 'Logger' don't be mocked. it will throw NullPointerException.

This issue is same as  '@Mocked(stubOutClassInitialization=true) private FirstClass firstClass'

**Comment by rliesenfeld** [comment]
My mistake, this isn't a bug. The following example test class should explain:

public class Issue188Test
{
   // This class will only go through static initialization on first use.
   static class ClassUsingLogger {
      // The LOG object is not created until the containing class gets initialized.
      static final Logger LOG = Logger.getLogger(ClassUsingLogger.class);
   }

   @Test // runs first
   public void callMethodOnMockedLogger(@Mocked Logger log)
   {
      // Causes static initialization of the class containing LOG, assigning a new instance to the field.
      // However, since the Logger class is mocked, the LOG object is an uninitialized instance, with
      // null on every reference field.
      ClassUsingLogger.LOG.info("");
   }

   @Test // runs second, after Logger class gets unmocked
   public void callMethodOnUnmockedLogger()
   {
      // Logger is no longer mocked, but the LOG field still points to an uninitialized instance,
      // hence the NPE on a null field is referenced.
      ClassUsingLogger.LOG.info("");
   }

   // Only way to avoid the problem: make sure classes containing static fields are initialized before
   // they get mocked, or any of the classes used in static fields get mocked.
   // uncomment to make the tests pass: @BeforeClass
   public static void setUp()
   {
      // Forces static initialization of the client class, so that LOG gets an initialized new instance.
      new ClassUsingLogger();
   }
}
