### ISSUE TITLE
Dynamic partial mocking of java.lang.System goes beyond mocked method

### ISSUE THREAD

**Issue by twigington** [jmockit/jmockit1#189]
What I'm attempting to do is mock System.currentTimeMillis() faking the system time to create a consistent answer for a function that uses the current time. When doing this the mocking seems to go behind the specific method.

Take this overly simple class.

    public class MyObject {
        public long getNow() {
            return System.currentTimeMillis();
        }
    }

These tests highlight the behavior I am seeing. 

    public class MyObjectTest {
        @Tested
        MyObject myObject;

        /**
         * This seems to works okay, but as you can see it also changes the behaviour of some other methods.
         */
        @Test
        public void fixedTime_FullyMocked(@Mocked final System system) {
            final LocalDateTime ldt = LocalDateTime.of(2000, 4, 15, 4, 0);

            new Expectations() {{
                System.currentTimeMillis();
                result = ldt.toEpochSecond(ZoneOffset.ofHours(0));
            }};

            assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
            assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
            assertThat("JAVA_HOME", System.getenv("JAVA_HOME"), is(nullValue()));
            assertThat("Property Size", System.getProperties(), hasKey("java.home"));
            assertThat("line separator", System.lineSeparator(), is(nullValue()));
            System.out.println("Hello World!");
            System.out.println(System.getenv("JAVA_HOME"));
        }

        /**
         * This worked great, but is going way in 1.19.
         */
        @Test
        public void fixedTime_partiallyMocked(@Mocked("currentTimeMillis") final System system) {
            final LocalDateTime ldt = LocalDateTime.of(2000, 4, 15, 4, 0);

            new Expectations() {{
                System.currentTimeMillis();
                result = ldt.toEpochSecond(ZoneOffset.ofHours(0));
            }};

            assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
            assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
            assertThat("JAVA_HOME", System.getenv("JAVA_HOME"), is(notNullValue()));
            assertThat("Property Size", System.getProperties(), hasKey("java.home"));
            assertThat("line separator", System.lineSeparator(), not(isEmptyString()));
            System.out.println("Hello World!");
            System.out.println(System.getenv("JAVA_HOME"));
        }

        /**
         * Fails with missing invocation to mocked type.
         */
        @Ignore
        @Test
        public void fixedTime_partialMockingClass() {
            final LocalDateTime ldt = LocalDateTime.of(2000, 4, 15, 4, 0);

            new Expectations(System.class) {{
                System.currentTimeMillis();
                result = ldt.toEpochSecond(ZoneOffset.ofHours(0));
            }};

            assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
            assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
            assertThat("JAVA_HOME", System.getenv("JAVA_HOME"), is(notNullValue()));
            assertThat("Property Size", System.getProperties(), hasKey("java.home"));
            assertThat("line separator", System.lineSeparator(), not(isEmptyString()));
            System.out.println("Hello World!");
            System.out.println(System.getenv("JAVA_HOME"));
        }
    }

**Comment by rliesenfeld** [comment]
System.currentTimeMillis() is a native method, which can't be mocked dynamically (I will a note about this to the API documentation).

Note the deprecation comment for @Mocked(value) suggests another alternative, the use of a MockUp. This will work better for mocking java.lang.System. This said, however, mocking System.currentTimeMillis() may be a sign something is wrong in the code under test.

**Comment by twigington** [comment]
I'll work up a sample using MockUp and report the results.

> This said, however, mocking System.currentTimeMillis() may be a sign something is wrong in the code under test.
I 100% agree. Legacy code for business features that are time dependent. I'll hopefully get them moved to a more deterministic solution like java.time.Clock over time.

Thanks for the reply.

**Comment by twigington** [comment]
This works just fine.

    @Test
    public void fixedTime_usingAnonymousMockUp() throws Exception {
        final LocalDateTime ldt = LocalDateTime.of(2000, 4, 15, 4, 0);

        new MockUp<System>() {
            @Mock long currentTimeMillis() {
                return ldt.toEpochSecond(ZoneOffset.ofHours(0));
            }
        };

        assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
        assertThat("getNow", myObject.getNow(), is(ldt.toEpochSecond(ZoneOffset.ofHours(0))));
        assertThat("JAVA_HOME", System.getenv("JAVA_HOME"), is(notNullValue()));
        assertThat("Property Size", System.getProperties(), hasKey("java.home"));
        assertThat("line separator", System.lineSeparator(), not(isEmptyString()));
        System.out.println(System.getenv("JAVA_HOME"));
    }

Thanks for the help.
