### ISSUE TITLE
Add Junit 4.x @Rule

### ISSUE THREAD

**Issue by shollander** [jmockit/jmockit1#193]
Jmockit already has a runner that can be used with Junit's `@RunWith`. Unfortunately, Junit does not support multiple `@RunWith` annotations so it cannot be used when other `@RunWith`s are needed.  It would be nice if JMockit had a @Rule that would supply the same functionality as the `JMockit` BlockJunit4ClassRunner.

This would provide similar functionality to Mockito's MockitoRule see http://site.mockito.org/mockito/docs/current/org/mockito/Mockito.html#32

**Comment by rliesenfeld** [comment]
It would not work, because JUnit's Rules do not support everything that a custom Runner does. Specifically, it does not support having parameters in test methods.
