### ISSUE TITLE
Version 1.18 does not work with OpenJDK

### ISSUE THREAD

**Issue by heapifyman** [jmockit/jmockit1#196]
When using version 1.18 with OpenJDK 8 I get
```
IllegalStateException: To run on OpenJDK 64-Bit Server VM use -javaagent:/home ...
```

After downgrading to version 1.16 it works without problems.

It would be great if 1.18 could work with OpenJDK like 1.16 does.
If that is not possible it would be great to prominently display the instructions for "javaagent" in the documentation to avoid confusion when your local build succeeds but suddenly fails on the build server because the build server is using OpenJDK.

**Comment by alexandarp** [comment]
@rliesenfeld Will this fix be in the 1.19?
