### ISSUE TITLE
How to mock variable number of instances of the same type with jmockit >= 1.9 ?

### ISSUE THREAD

**Issue by ugoscaiella** [jmockit/jmockit1#204]
We are trying to move from 1.8 to the latest, but we found that in version 1.9 the following code is no longer working
```java

public List<Data> mockData(int n) {
  List<Data> list = new ArrayList<>();  
  for (int i=0; i<n; i++) {
    Data d = new Data();
    new Expectations(d) {{
        d.getField1(); result = ...
        d.getField2(); result = ...
    }}
  }
  return list;
}

@Test
public void aTest() {
   List<Data> datas = mockData(10)
   ....

}

@Test
public void anotherTest() {
   List<Data> datas = mockData(1)
   ....

}

```

Class `Data` is not mocked, ie, there's no `@Mocked` instance of type `Data` defined anywhere.
We were using a lot of functions like this, to create several mocked data to be used to test different scenarios. But from version 1.9 this fails at runtime saying `java.lang.IllegalArgumentException: Already mocked: class ...`

This could be related to #15 , but it's different because in this case we are mocking two different instances...

Is there a way to achieve the same with version >= 1.8 ?

**Comment by rliesenfeld** [comment]
Shouldn't your test be able to just do

    Data d = new Data(value1, value2);

or 

    Data d = new Data();
    d.setField1(value1);
    ... ?

**Comment by ugoscaiella** [comment]
Hi Rogerio thanks for your quick reply
Sorry for the code snippet, it was just a quick example, and maybe doesn't help understanding the scenario.  Let me rewrite it:
```java
public Data mockData(final int field1, final String field2) {
    Data d = new Data();
    new Expectations(d) {{
        d.getField1(); result = field1
        d.getField2(); result = field2
    }}
  return d;
}

@Test
public void aTest() {
  List<Data> datas = Arrays.asList(
    mockData(1,"one"),
    mockData(42,"blabla"),
    ...
  )
   ....

}

@Test
public void anotherTest() {
   List<Data> datas = Arrays.asList( mockData(0,null) );
   ....

}

```

Usually the `Data` class is a class that doesn't provide any setter, because it's something that requires a complex build function, but for the scope of the test, only `field1` and `field2` are required. Anyway, the point is that we can no longer mock a variable number of instances of the same class. 

I know that if the size of the list is known in advance, then we could do add a list of instances of the class to be mocked as parameters of the test method, something like this

```
@Test
public void aTest(@Mocked Data data1, @Mocked Data data2, @Mocked Data data3, <...> ) {
  //add expectations for data1, data2, data3 separately
  ...
}
```
but this is makes code harder to maintain and doesn't solve the scenario above, because the number of instances is variable.

This could be solved using Mockito, but we would like to avoid adding another framework...
```
public Data mockData(int field1, String field2) {
  Data d = Mockito.mock(Data.class)
  Mockito.when(d.getField1()).thenReturn(field1);
  Mockito.when(d.getField2()).thenReturn(field2);
  return d;
}
...
```

Could you please confirm whether this scenario is still supported somehow in jmockit latest versions or not?

**Comment by rliesenfeld** [comment]
You can use the `onInstance(d)` constraint. Given a mocked class (`@Mocked Data d`), any number of instances can be created (`Data d = new Data()`), and then recorded:

    new Expectations() {{
        onInstance(d).getField1(); result = value1;
        onInstance(d).getField2(); result = value2;
    }};

**Comment by ugoscaiella** [comment]
Thanks, I confirm this works fine with current version, 1.19

However, to be honest, this is not exactly equal to the previous behavior because that was a partial mocking, while now we have to declare `Data` with `@Mocked`
For our use case it's fine, and maybe there are no valid use cases, but just for curiosity, could we replicate the exact behavior with the current version of jmockit, ie partial mocking of a variable number of instances of a given class?

In any case, thank you again for your efforts, we really appreciate your work.
