### ISSUE TITLE
How to inject a MockUp class into a tested class?

### ISSUE THREAD

**Issue by benze** [jmockit/jmockit1#211]
I'm new to JMockIt and am trying to figure out/understand how to use `@Injectable` for a top-level MockUp class that I have already defined.

For example:
```
    // JUnit Test Class
    public class RepositoryTest {
    
        @Tested private Repository repository;
        @Injectable private ResultsAPIWrapper resultsApiWrapper;
    
        @Test
        public void testRepo(){
            new ResultsApiWrapper();
        	assertThat(repository.doSomething(), is("done" ) );
        }
    }
    

    // Class under test
    public class Repository{
    
       @Autowired private ResultsAPIWrapper resultsApiWrapper;
       
       public String doSomething(){
          return resultsApiWrapper.load();
       }
    }
    
    // Mocked implementation of the ResultsAPIWrapper that I want injected into Repository
    public class ResultsApiWrapperMock extends MockUp<ResultsAPIWrapper>{
       @Mock
       public String load(){
          return "done";
       }
    }
```

If I try the above, I get an error
```
    java.lang.IllegalArgumentException: Class already mocked: com.fw.wrappers.ResultsAPIWrapper
    	at com.fw.wrappers.mock.ResultsApiWrapperMock.<init>(ResultsApiWrapperMock.java:12)
    	at com.fw.repository.RepositoryTest.testRepo(RepositoryTest.java:38)
```

But If I remove the `new ResultsApiWrapper()` then I do not know how to specify which is the class I want to use as my mocked implementation for the autowire.

Am I misunderstanding how to do this?  How can I specify that I want JMockit to autowire using my `MockUp<>` implementation?  Or is this a limitation of JMockit and this is not feasible?

**Comment by rliesenfeld** [comment]
Yes, it seems you're misunderstanding the mocking API. Did you read the Getting Started page, or the Tutorial?

**Comment by benze** [comment]
Yes - I have definitely read both.  In the Tutorial, it states:

> Fake implementations can be particularly useful in integration tests which depend on external entities > or resources such as the network, the file system, etc

Consequently, I would have expected that as part of an integration test, I could mock an external entity/library using the Mock API and have it injected into the class I want to test.  How else should I go about doing this?

My use case is that I am trying to Mock a 3rd party API, so I have written a small class that has some logic to simulate the API.  My API is normally injected into my service, so instead I want to inject my Mocked API (the dummy class I wrote) into my service instead.

Is there another mechanism to do this?

**Comment by rliesenfeld** [comment]
I think what you are looking for ("mock an external entity... and have it injected into the class I want to test") is what the "Instantiation and injection of tested classes" section of the Tutorial describes: http://jmockit.org/tutorial/Mocking.html#tested

**Comment by benze** [comment]
Yes - that is precisely the section I was looking at and reading, however something is still unclear to me.  In the example, what is class `Dependency dep1`?  Where is that defined?  Is that not supposed to be a MockUp<> class?  Otherwise, how do I provide the body for the class?

That is what I tried to do above with my `ResultsApiWrapperMock ` class, hoping that would be injected into my Test class, but apparently I'm doing something wrong.

**Comment by rliesenfeld** [comment]
In that example test, "Dependency" is an arbitrary type (a class or interface) which happens to be used by (ie, it's a "dependency" of) the "CodeUnderTest" class. In the documentation, types like "CodeUnderTest", "Dependency", "AnotherDependencty", etc. are merely placeholders; hopefully, the accompanying example tests and descriptions should make it clear what they represent.

**Comment by benze** [comment]
Unfortunately - no it is not clear to me.  I have gone through all the examples and descriptions.  

I want to be able to create Mock classes and have them injected into my @Test unit.  As in your example, I would want Dependency to be a mocked class.  How do I do that?  How do I provide a body/implementation for Dependency?

**Comment by rliesenfeld** [comment]
"... create stub-like Mock classes (ie: fake/mock-ups) and have them injected into my @Test unit": there is no support for this; instead, injection of mocked classes is done by using @Tested and @Injectable.

"... injection support and the Mockups API are mutually exclusive": exactly

**Comment by benze** [comment]
That explains why I haven't been able to accomplish this.  

Is there a philosophical reason why Injection and Mockups are mutually exclusive, or is it just a feature not implemented?

I can think of several ways that I would like to be able to use Injection support but provide Stubs (ie: fake/Mockups) for one particular implementation.  Instead, I am forced to write a lot of boiler-plate code to instantiate my Test objects by hand (and potentially use the Deencapsulation class to inject some fields).  I would have thought/expected this to be a natural usage of the framework.

I believe Mockito supports this with the @Spy annotation.

**Comment by rliesenfeld** [comment]
I suspect you simply need to read the documentation again, this time with an open mind, without making false assumptions. The 2nd chapter in the Tutorial, "Mocking", describes everything you need to know. The mocking API (ie, `Expectations`, `@Mocked`, `@Injectable`, `@Tested`) provides all the functionality (plus more) that any other mocking library provides. The faking API, described in the following chapter in the Tutorial, is something else entirely; it's a unique API which has no equivalent in any other library; normally, you wouldn't use both of them together, there is just no need.

**Comment by benze** [comment]
I have read the 2nd chapter at least half a dozen times, and apparently I am just missing something.  I thought I understood all the concepts presented, and yet I still am unable to wrap my head around how to make this work (_without_ using an Expectations() block).

I think I just noticed a mistake in my original example that I posted (I have edited the sample code I provided).  I am using Constructor injection to create my `Repository` class (not field injection as was originally indicated).  This may be part of the reason that my issue is not clear.

Perhaps my issue is that the third party class I am stubbing has no interface.  So I am forced to create a stub class with the same signature and inject that one instead into my system-under-test (SUT).  Having seeing the Mockup API, I thought it was brilliant.  I could easily create stub using the Mockup API without needing an interface.  However, I am then stuck as I cannot have jMockit inject my stub into my SUT.  Additionally, the Mockup API would allow me to create multiple different stubs for different purposes.  Fantastic.

But unless I can "activate" my stub, it serves me no purpose.  

Given that my SUT has a single constructor requiring the Stub class, I have to have a class available for the injection to use @Tested.  But there is unfortunately no way to make my Stub available to the Injection mechanism.

The only alternative I can see is to create Expectations for my @Injectable class and map each method to my stub object.  Functional as a workaround, but not as clean as I would have liked.

**Comment by rliesenfeld** [comment]
You are making several mistakes:
1) "*without* using an Expectations() block": using an expectation block is the only way to record expectations on a mocked type/instance; otherwise, you are just not using the mocking API.
2) Either constructor injection or field injection will work fine; just use @Tested and @Injectable, and it should happen (provided the class under test has a matching constructor parameter or a field for each dependency to be injected).
3) Any type can be mocked (with a mocking annotation such as @Mocked or @Injectable), whether it has a separate interface or not.
4) There is no difference between "mocks" and "stubs" in the JMockit mocking API; there are only "mocks", for which a test can record and/or verify expectations, which in turn can be "regular", strict, or non-strict.
4) The "Mocking" chapter is about the mocking API; MockUp is discussed *only* in the "Faking" chapter, as it belongs to an entirely separate and independent API, which is not meant to be used in a test which uses any part of the mocking API.
5) "... map each method to my stub object": using the mocking API, you create a "stub"/"mock" with one of the mocking annotations (@Injectable, in case you want it to be injected into a @Tested object); there is no "mapping of methods"; instead, the test records and/or verifies the expectations that it needs (and nothing more).

Finally, if the Tutorial is not sufficient, there are hundreds of fully working and realistic tests in the sample test suites (http://jmockit.org/samples.html).
