### ISSUE TITLE
withArgThat(Matcher) require a specific type of Hamcrest Matcher only

### ISSUE THREAD

**Issue by benze** [jmockit/jmockit1#212]
I get the following error message when using some Hamcrest matchers with JMockit Verifications.

```
The method create(String) in the type WorkItemRepository is not applicable for the arguments (Iterable<capture#1-of ? extends String>)
```

The Verification javadoc indicates:
```
protected final <T> T withArgThat(org.hamcrest.Matcher<? super T> argumentMatcher
```

But the Hamcrest Matchers have changed their signatures in v1.3 from just "Matcher<T>", but got changed to "Matcher<? super T>" in recent versions.

A related issue is https://code.google.com/p/hamcrest/issues/detail?id=176.

Also see [this Google Groups thread] (https://groups.google.com/forum/#!topic/jmockit-users/MpPg9AHg8VI).

**Comment by rliesenfeld** [comment]
After analysis, it seems this was a false alarm.
