### ISSUE TITLE
Generics doesn't work properly in chained method calls

### ISSUE THREAD

**Issue by ChristophLu** [jmockit/jmockit1#213]
With JMockit 1.19 I have the following test code:

```java
public class MockTest {
    public interface Baz {
    }

    public interface Bar {

        public Baz getBaz(String name);
    }

    public interface Foo {

        public <DataT> Bar getBar(DataT model); // this does not work: "baz" is null
        // public Bar getBar(String model); // this works!
    }

    @Test
    public void test_cascading_class(@Mocked Foo foo) {
        assertNotNull(foo);
        final Bar bar = foo.getBar("blah");
        assertNotNull(bar);
        final Baz baz = bar.getBaz("foo"); // "baz" is null
        assertNotNull(baz);
    }
}
```

The third assertion is null if using `getBar()` with generics. If I use the method without generics all works fine.

**Comment by SimFirehawk** [comment]
I can confirm it. The problem should still be existing in version 1.20. It is related to MockedTypeCascade in method getGenericReturnType specific in line 105. 
The return value of getInternalReturnTypeCodeAndName(..) is used, but it should return only the name without the type code.
