### ISSUE TITLE
@MockClass annotation

### ISSUE THREAD

**Issue by PatrickSauts** [jmockit/jmockit1#216]
With @MockClass annotation it was possible to make a class extend the same super class than the mocked class.

So it was possible to call methods or variables of the super class in the mocked class.
Variables form the super class could be overriden. 

How do you do that now ?

**Comment by rliesenfeld** [comment]
The only choice now is `MockUp`.

**Comment by PatrickSauts** [comment]
So it's not possible anymore to mock while still extending the superclass ?

Well except with default interface implementation for java 8 which is not the same.

May I ask what motivated the deletion of @MockClass.
I have to admit that I found Jmockit a lot less interesting compare to its competitors now...
I have been using it from 2005 to 2013 because I loved it.
I'm back to intensive testing and wanted to use it again with Java 8... 
I guess I'll use PowerMock/mockito from now one which has the same capabilities and is easier to use.

Thank you for your answers.
