### ISSUE TITLE
Invalid try/catch statement inside expectations block

### ISSUE THREAD

**Issue by benze** [jmockit/jmockit1#221]
I have some pretty straight forward code for which I am writing expectations that works fine:

```
    @Test
    public void test(final @Mocked WorkItemCount counter) {
        new Expectations() {
            {
                    counter.getCount((State) any);
                    result = 10;
            }
        };

        Assert.assertEquals(counter.getCount(null), 10);
    }
```

However, my problem is that I now have an aspect with the following defn:

```
@Around( "call( public int WorkItemCount.getCount(..))")
    public Object around(ProceedingJoinPoint pjp) throws Throwable{
        Object o = null;
        try {
            o = pjp.proceed();
        } catch (IOException e) {
            return -1;
        }
        return o;
    }
}
```

This effectively advises my Expectations() block and throws the Invalid try/catch error.

Is there anything that can be done for this?  I would rather not put in some conditional pointcuts in my aspect to ignore specific testing framework.   Or can I rewrite my expectations in such a manner that a try/catch won't throw the error?

Ideally, however, I would like to maintain the aspect in my tests and have the try/catch block in my expectations so I can properly test/mock my object.  My aspect does exception handling, so it would be logical way for me to validate it's functionality.

For instance, I would want to be able to do:

```
    @Test
    public void test(final @Mocked WorkItemCount counter) {
        new Expectations() {
            {
                    counter.getCount((State) any);
                    result = new IOException();
            }
        };

        Assert.assertEquals(counter.getCount(null), -1);
    }
```

**Comment by rliesenfeld** [comment]
You should get AspectJ to ignore all test classes when applying aspects; they are only intended for production code, right?

Now, I don't know how to do that. AspectJ documentation should have something about it.

**Comment by benze** [comment]
There are 2 issues with that:

1) Ideally, I would like my aspect to still wrap my mocked expectation.  I am trying to mock the API and still want my aspect to wrap the mocked API (otherwise I am changing expected functionality)

2) It would mean putting some conditional logic in my aspectj pointcut that says "ignore jMockit Tests", which doesn't seem appropriate.

Is there a specific design reason why one cannot have try/catch in the Expectations block?

**Comment by rliesenfeld** [comment]
Why do you want the aspect to apply to recorded expectations? In this case, what the aspect does is to catch an eventual IOException from `getCount(...)` and then return -1 instead. But recording an expectation will never throw an exception, so what's the point?

And my suggestion was to tell AspectJ to ignore *all* test code, not just JMockit tests. In general, I don't see why one would want to apply aspects to *test code*; normally, aspects only apply to production code.

The design reason for disallowing try/catch in expectation blocks was to avoid API misuse.

**Comment by benze** [comment]
Respectfully, I disagree. Aspects have their place in unit/integration tests as well.

If I am recording an expectation on a mocked element, I still want to validate that my ClassUnderTest responds appropriately to an exception thrown by my Mock (handled under certain circumstances by an aspect).

**Comment by rliesenfeld** [comment]
If aspects have their place in tests, which place is that? Can you give a realistic example?

In this case, you should be able to write the desired test just fine: JMockit will modify `WorkItemCount` in order to mock it, AspectJ will modify the `ClassUnderTest` which calls the mocked object, and the test class will be left alone; there will be no interference between JMockit and AspectJ. I haven't written the code, but this should work fine unless I am missing something.

**Comment by benze** [comment]
The problem is that the AspectJ pointcut is examining all classes for calls to the getCount() method.  In this case, there is a call within the Expectations() block, so AspectJ is correctly trying to place its aspect at that location.  And since the Expecations/Verifications classes do not allow for try/catch handling, there are errors thrown.

I agree that if the aspect was advising the CUT, there wouldn't be this issue.

A realistic and concrete example of Aspects in tests can be for profiling or credential handling. 
Another example is for Mixins (ex: Spring ROO) where you use Aspects to inject interfaces and implementations to classes (although these would not affect any JMockit functionality).
