### ISSUE TITLE
Issue with withCapture

### ISSUE THREAD

**Issue by beluchin** [jmockit/jmockit1#230]
I encountered an issue (?) with `withCapture` that, although I did not manage to reproduce with an isolated test, I feel I should drop a note just in case it rings a bell.

In essence, calls to `withCapture` return `null` for no apparent reason. When I use `withCapture` on all arguments (3 args) on a call, even though the call was made in the prod code with non-null args, `withCapture` returns `null` for all args. If I instead use `any` on all args except one, `withCapture` returns the correct value.

That is, in the following block all args end up being `null`:

```java
new Verifications() {{
    Foo1 arg1;
    Foo2 arg2;
    Foo3 arg3;

    someObject.someMethod(arg1 = withCapture(), arg2 = withCapture(), arg3 = withCapture());

    makeSomeAssertion(arg1);
    // nothing is done with arg2 or arg3
}};
```
However, if I use `any` for `arg2` and `arg3`, `arg1` ends up being non-null:

```java
new Verifications() {{
    Foo1 arg1;

    someObject.someMethod(arg1 = withCapture(), (Foo2) any, (Foo3) any);

    makeSomeAssertion(arg1);
}};
```

Hopefully, I was clear enough. Otherwise, drop me a note if you want more clarification

jmockit 1.17

**Comment by rliesenfeld** [comment]
It's clear, but I can't reproduce the problem.
