### ISSUE TITLE
Mocking static methods doesn't seem to respect the invocation arguments

### ISSUE THREAD

**Issue by omerio** [jmockit/jmockit1#237]
The following code fails in jMockit, I've tried with the exact string, withEquals, with..., but seems to always return back the object regardless of the parameter. Note App.getCustomer(String) is a static method. This behaves correctly in PowerMockito:
```java
	@Test
	public void testMockStatic(final @Mocked App unused) {
		final Customer customer = new Customer();
		new NonStrictExpectations() {{
			App.getCustomer(withEqual("john"));  result = customer ;
		}};
		
		assertSame(customer, App.getCustomer("john"));
		assertNull(App.getCustomer("Mark")); //<--- this assertion fails
	}
```

The equivalent in PowerMockito works as expected:
```java
	@Test
	@PrepareForTest({App.class})
	public void testMockStatic() {
		Customer customer = new Customer();
		PowerMockito.mockStatic(App.class);
		when(App.getCustomer("john")).thenReturn(customer);
		
		assertSame(customer, App.getCustomer("john"));
		assertNull(App.getCustomer("Mark")); //<--- this assertion works file
	}
	
```

**Comment by rliesenfeld** [comment]
Note that, as the API documentation for `@Mocked` describes, mocking automatically *cascades* from non-void methods, where applicable.

So, what that call to `App.getCustomer("Mark")` is returning is a *cascaded instance* of `Customer`, not the same `customer` instance.
If you need the method to return `null` for any argument value other than `"john"`, then you need to explicitly record it:

        new Expectations() {{
            App.getCustomer("john"); result = customer;
            App.getCustomer(anyString); result = null;
        }};

**Comment by omerio** [comment]
Aha, now I understand it, thanks for your help, jMockit rocks
