### ISSUE TITLE
Error when using path coverage with an active aspect

### ISSUE THREAD

**Issue by jajohansen** [jmockit/jmockit1#239]
When I add Path coverage to the code i get  IndexOutOfBounds Index: 4, Size: 2
The problem seems to desapear when i remove the aspect and even if I remove the two unused poincuts.

I have reduced the failing code to the following code:
aspectj:
package com.sxp.common.validation;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.SuppressAjWarnings;
import org.aspectj.lang.reflect.ConstructorSignature;
import org.aspectj.lang.reflect.MethodSignature;
import java.util.Formatter;

/**
 * Aspect to support the NotNull annotation on parameters
 * Created by jaj on 30-04-2015.
 */
public aspect NotNullParameter {
	//we have to define each position of parameters independently as of thes version of aspectj
	pointcut parameter1NotNull(Object o) :execution(* com.sxp..*(@javax.validation.constraints.NotNull (*),..)) && args(o,..);
	pointcut parameter2NotNull(Object o) :execution(* com.sxp..*(*,@javax.validation.constraints.NotNull (*),..)) && args(*,o,..);
	pointcut parameter3NotNull(Object o) :execution(* com.sxp..*(*,*,@javax.validation.constraints.NotNull (*),..)) && args(*,*,o,..);

	@SuppressAjWarnings({"adviceDidNotMatch"})
	before(Object o): parameter1NotNull(o) {
		methodTest(o, thisJoinPoint, 0);	}
	@SuppressAjWarnings({"adviceDidNotMatch"})
	before(Object o): parameter2NotNull(o) {
		methodTest(o, thisJoinPoint, 1);	}
	@SuppressAjWarnings({"adviceDidNotMatch"})
	before(Object o): parameter3NotNull(o) {
		methodTest(o, thisJoinPoint, 2);	}

	private void methodTest(Object o, JoinPoint thisJoinPoint, int position) {
		if(o == null) {
			StringBuilder stringBuilder = new StringBuilder();
			Formatter formatter = new Formatter(stringBuilder);
			MethodSignature signature = (MethodSignature) thisJoinPoint.getSignature();
			formatter.format("Argument \"%1$s\" to \"%2$s\" is null at \"%3$s\" %4$s",
				signature.getParameterNames()[position],
				signature.getName(),
				signature.getDeclaringTypeName(),
				thisJoinPoint.getSourceLocation());
			throw new IllegalArgumentException(stringBuilder.toString());
		}
	}

}

source code:
package com.sxp.common;

import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;

import javax.sql.DataSource;
import javax.validation.constraints.NotNull;
import java.util.Formatter;
import java.util.HashMap;

public class ResourceContainer {

	private static HashMap<Pair<String, String>, Class> types = new HashMap<>();
	private static HashMap<Pair<String, String>, Object> resources = new HashMap<>();

	public static boolean containsResource(Class type) {
		return containsResource(type,null);
	}

	public static boolean containsResource(Class type, String name){
		return resources.containsKey(new ImmutablePair<>(type.getCanonicalName(), name));
	}

	public static void registerResource(Class type, String name, @NotNull Object object) {
		ImmutablePair<String, String> pair = new ImmutablePair<>(type.getCanonicalName(), name);
		if (resources.containsKey(pair))
			throw new RuntimeException(String.format("Resource '%1$s' is already registered", type.getName()));
		else
			resources.put(pair, object);
	}

	public static void unregisterResource(@NotNull Class type){
	}
}

the test class:
package com.sxp.common;

import org.testng.annotations.Test;

/**
 * Created by JAJ on 26-10-2015.
 */
public class ResourceContainerTest {
  @Test
  public void testfails(){
    Object o2 = new Object();

    ResourceContainer.registerResource(Object.class, "named", new Object());
  }
}

**Comment by rliesenfeld** [comment]
I will see if it's possible to detect and ignore bytecode inserted by AspectJ, when modifying classes to gather code coverage.
