### ISSUE TITLE
StackOverflow when running Pitest with jmockit 1.10

### ISSUE THREAD

**Issue by ColinHebert** [jmockit/jmockit1#24]
After updating to the latest version of jmockit I noticed that my Pitest run started failing.

I did a bit of research and figured out that the problem has been introduced between r2822 (successful) and r2825 (failing). See https://code.google.com/p/jmockit/source/list
The intermediary revisions fail to compile so I couldn't get a more precise position of the introduction of the regression.

The result is a successful run against r2822 while r2825 gives the following stacktrace

> java.lang.StackOverflowError
>        at mockit.integration.testng.internal.TestNGRunnerDecorator$MockParameters.getInjectedParameter(TestNGRunnerDecorator.java:46)
>        at org.testng.internal.Parameters.getInjectedParameter(Parameters.java)
>        at mockit.integration.testng.internal.TestNGRunnerDecorator$MockParameters.getInjectedParameter(TestNGRunnerDecorator.java:46)
>        at org.testng.internal.Parameters.getInjectedParameter(Parameters.java)
>        at mockit.integration.testng.internal.TestNGRunnerDecorator$MockParameters.getInjectedParameter(TestNGRunnerDecorator.java:46)

Now this is the (horrible) protocol I used to run my test:

``` bash
#!/bin/sh
set -ex

#I didn't bother with a temporary repository
# I just removed the "org/jmockit/jmockit/1.10/" when I was done
jmockit_dir=~/Documents/jmockit1
raven_dir=~/Documents/raven-java

#Jmockit 1.9 needs Java7
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home

cd "$jmockit_dir/main"
mvn clean package -DskipTest -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
mv -f target/jmockit-1.9.jar ~/.m2/repository/org/jmockit/jmockit/1.10/jmockit-1.10.jar
cd "$raven_dir/raven"
mvn org.pitest:pitest-maven:mutationCoverage -P pitest
```

against the current master of my project (getsentry/raven-java@4df7dba5ecb8269e0a669f0749d5aaaa665dc635)

I would love to be able to provide more details, unfortunately Pitest is a bit of a black box for me ATM

**Comment by estekhin** [comment]
It seems that including modified `org.junit.runner.Runner ` into JMockit causes the problem.

Could you remove this modified `org.junit.runner.Runner ` from JMockit and instead use instrumentation to detect when (and if) it is being loaded and modify it on the fly? I think that this approach could also drop the requirement that JMockit jar should be placed before JUnit jar in classpath.

**Comment by rliesenfeld** [comment]
I would love to remove the modified `Runner`, but that would force JUnit users to either use "-javaagent:jmockit.jar" *or* add `@RunWith(JMockit.class)` to every JUnit test class using JMockit. The actual problem the modified `Runner` solves is that it allows JMockit to initialize itself at the start of the test run, which is needed for several aspects of the mocking API to work properly.

This issue does not exist with TestNG, which supports startup listeners. I once requested this feature be added to JUnit ([issue 80](https://github.com/junit-team/junit/issues/80)), but the idea was not accepted.

**Comment by hcoles** [comment]
This is believed to be fixed in release 1.1.4 of pitest which contains a fix suggested by @rliesenfeld to sidestep the issue by checking for a class other then Runner when looking for junit on the classpath.

**Comment by estekhin** [comment]
Sadly, not fixed.
Pitest-1.1.4 fixes the problem with being able to run testing-based tests at all, and after that testng+jmockit+pitest produce StackOverflowError (alterating between `org.testng.internal.Parameters.getInjectedParameter(Parameters.java)` and `mockit.integration.testng.internal.TestNGRunnerDecorator$MockParameters.getInjectedParameter(TestNGRunnerDecorator.java:45)`) when some tests use data providers and mocked/injected objects.

It happens with 100% probability in my working project, but i am trying to reproduce this with the minimal amount of code.

**Comment by estekhin** [comment]
Reproduced in https://github.com/estekhin/sandbox-gradle-testng-jmockit-pitest.

Running `gradle clean pitest` will fail due to `java.lang.StackOverflowError` due to `getInjectedParameter()` chain, but running `gradle clean test` will work OK.

**Comment by hcoles** [comment]
@estekhin thanks, I'll try and dig into that when I get chance. Don't know much/anything about the jmockit side though so may be slow going.

**Comment by hcoles** [comment]
I can reproduce from @estekhin's repo with the combination of ValueHolderBasicTest and ValueHolderDataTest.

It does seem to be related to DataProviders, but the ValueHolderDataTest on it's own does not reproduce the problem.

The issue can still be reproduced if I disabling the insertion of coverage probes etc.

Pitest will [create an instance of TestNG + suite for each test class](https://github.com/hcoles/pitest/blob/master/pitest/src/main/java/org/pitest/testng/TestNGTestUnit.java#L80).

Is this breaking an assumption made by JMockit?

**Comment by rliesenfeld** [comment]
JMockit relies on TestNG's SPI mechanism. Inside jmockit.jar, there is a META-INF/services/org.testng.ITestNGListener file, pointing to the implementation class "mockit.integration.testng.Initializer". When instantiated by TestNG, it loads a Java agent in order to obtain a java.lang.instrument.Instrumentation object, and adds a listener to the object returned by TestNG.getDefault().

So, if Pitest is creating additional TestNG objects, it might conflict with other tools like JMockit which use TestNG's SPI.

**Comment by estekhin** [comment]
`TestNG.getDefault()` seems to be deprecated for quite some time. Should't mockit use `ISuiteListener` or something similar to bind to TestNG?

**Comment by rliesenfeld** [comment]
Maybe; I will have to try reimplementing it with ISuiteListener; it should work, in principle.

**Comment by hcoles** [comment]
Issue goes away if I reuse the TestNG instance by sticking it in a static member. Very ugly though as I need to synchronize and constantly add and remove listeners.

Delving into the TestNG code I see it sets a static member when you call it's constructor anway. Nice.
