### ISSUE TITLE
Delegate<T> should be a FunctionInterface

### ISSUE THREAD

**Issue by KidCrippler** [jmockit/jmockit1#245]
Java 8 introduced a FunctionlInterface annotation, which seems to aling perfectly with JMockit's Delegate<T> interface.
One should implement a delegate() method whose return type is T, instead of requiring "exactly one non-private instance method".

The pros of this approach would be a more elegant and robust code, which doesn't yield a warning 
(The method delegate() from the type new Delegate>(){} is never used locally) as the current Delegate interface does.

**Comment by rliesenfeld** [comment]
Sure, but it can only be done in JMockit 2.0, otherwise existing tests using a Delegate would break.
