### ISSUE TITLE
Invocation count constraints with jUnit Theories

### ISSUE THREAD

**Issue by ArWellX** [jmockit/jmockit1#253]
The use of Invocation count constraints does not function together with jUnit-Theories.
Example:
@Theory
public void testLoginContext(LoginData data){

    new MockUp<LoginContext>(){
        @Mock(invocations = 1)
        void login() {}
    };

     ....
}
This Invocation count constraint - statement never fails for any constraint-value.

**Comment by rliesenfeld** [comment]
Indeed, the JUnit "Theories" API is not supported by JMockit.

If you want to add support for it, it can be done by submitting PRs to the project. I don't use Theories myself.

**Comment by ArWellX** [comment]
What are PR`s?

**Comment by rliesenfeld** [comment]
"Pull Requests"
