### ISSUE TITLE
Deencapsulation#setField can't set final fields

### ISSUE THREAD

**Issue by Spookyguy** [jmockit/jmockit1#257]
It would be great if the deencapsulation api could do this. It could be easily implemented like this:

public static void setFinalField(final Field field, final Object newValue) {
        field.setAccessible(true);
        final Field modifiersField = Field.class.getDeclaredField("modifiers");
        modifiersField.setAccessible(true);
        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
        field.set(null, newValue);
    }

**Comment by rliesenfeld** [comment]
The `setField` methods *already* are capable of setting final fields. Try the following example test:

```
static class Temp {
    final BigDecimal num = new BigDecimal("123.45");
    static final StringBuilder text = new StringBuilder("test");
}
    
@Test
public void setFinalFields() {
    Temp temp = new Temp();

    Deencapsulation.setField(temp, new BigDecimal("5.6"));
    Deencapsulation.setField(Temp.class, new StringBuilder("new text"));

    assertEquals(5.6, temp.num.doubleValue(), 0);
    assertEquals("new text", Temp.text.toString());
}
```
