### ISSUE TITLE
IDE can't auto discover tests

### ISSUE THREAD

**Issue by fzakaria** [jmockit/jmockit1#259]
The test runner that IntelliJ uses won't re-run failed tests that have `@Mocked` in the method signature (through a parameter).

Is there something that I can do with JMockit to alleviate this ?
It breaks the re-run workflow of running failed tests in the IDE

**Comment by rliesenfeld** [comment]
I am using IntelliJ IDEA 15.0.0, but the "Rerun Failed Tests" button seems to be working fine (for a failed @Test with a @Mocked parameter).
