### ISSUE TITLE
Documentation Expectation API example error

### ISSUE THREAD

**Issue by florianschmitt** [jmockit/jmockit1#261]
Hey, [on this page](http://jmockit.org/tutorial/Introduction.html#anExample) in the code example of the class **MyBusinessService_ExpectationsAPI_Test**

`   @Mocked SimpleEmail anyEmail;`
is given, but in the following here
`(4)   new Verifications() {{ email.send(); times = 1; }};`
and here
`(3)      email.addTo((String) withNotNull()); result = new EmailException();`
the variable is referenced as 'email'. 

Compare with [the source code](https://github.com/jmockit/jmockit1/blob/master/samples/tutorial/test/jmockit/tutorial/domain/MyBusinessService_ExpectationsAPI_Test.java) Thanks!

**Comment by rliesenfeld** [comment]
Fixed, thanks.
