### ISSUE TITLE
withCapture invoke private methode always returning null

### ISSUE THREAD

**Issue by lordgit** [jmockit/jmockit1#262]
Please provide the following information:

`classToTest.someMethode.execute()
 new Verifications() { {  
    SomeObject object;
    invoke(classToTest,"privateExecute", object  = withCapture());
 }};
`

* Version of JMockit that was used: 
1.21, 1.22

* Description of the problem or enhancement request:
  withCapture() alway return null. 
`   Verifications.protected final <T> T withCapture()
   {
      verificationPhase.addArgMatcher(AlwaysTrueMatcher.ANY_VALUE);
      //noinspection ConstantConditions
      return null;
   }`

**Comment by rliesenfeld** [comment]
The Deencapsulation.invoke(Object, String, Object... nonNullArgs) method expects to be passed non-null argument values, but withCapture() only "returns" the captured value *after* the target method is invoked (by the call to "invoke").

So, you need to use the Deencapsulation.invoke(Object, String, Class[] parameterTypes, Object...) overload method instead.
