### ISSUE TITLE
Concurrent Exception during Test Clean up

### ISSUE THREAD

**Issue by draukadin** [jmockit/jmockit1#270]
Please provide the following information:
Is this a known bug that has been fixed in a later version of JMockit  (newer then 1.14) or will upgrading not gain me anything until this is fixed in the next version?

* Version of JMockit that was used: 1.14

* Description of the problem or enhancement request:
java.util.ConcurrentModificationException
    at java.util.IdentityHashMap$IdentityHashMapIterator.remove(IdentityHashMap.java:748)
    at java.util.IdentityHashMap$EntryIterator.remove(IdentityHashMap.java:849)
    at mockit.internal.state.MockFixture.restoreRedefinedClasses(MockFixture.java:302)
    at mockit.internal.state.SavePoint.rollback(SavePoint.java:40)
    at mockit.integration.internal.TestRunnerDecorator.discardTestLevelMockedTypes(TestRunnerDecorator.java:123)
    at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:41)
    at mockit.integration.junit4.internal.MockFrameworkMethod.invokeExplosively(MockFrameworkMethod.java:40)

**Comment by rliesenfeld** [comment]
I don't know. How would I reproduce this failure?

**Comment by per-neiderud** [comment]
Hi,

Using version 1.31, I run into the same problem. 
It occures from time to time, and I also haven't been able to create a useful test case that reproduces the problem each time it runs.

However, I have spotted the problem in the code :)

It seems that in MockFixture, an item can in some cases be removed from an iterator while iterating over the elements of that same iterator. This causes the ConcurrentModificationException.

The problem is in this method, the 3rd line from the bottom,
"itr.remove();"

Could you please have a look?

Thanks,
Per


    void restoreRedefinedClasses(@Nonnull Map<?, byte[]> previousDefinitions) {
        if(!this.redefinedClasses.isEmpty()) {
            RedefinitionEngine redefinitionEngine = new RedefinitionEngine();
            Iterator itr = this.redefinedClasses.entrySet().iterator();

            while(itr.hasNext()) {
                Entry<Class<?>, byte[]> entry = (Entry)itr.next();
                Class<?> redefinedClass = (Class)entry.getKey();
                byte[] currentDefinition = (byte[])entry.getValue();
                byte[] previousDefinition = (byte[])previousDefinitions.get(redefinedClass);
                if(currentDefinition != previousDefinition) {
                    redefinitionEngine.restoreDefinition(redefinedClass, previousDefinition);
                    if(previousDefinition == null) {
                        this.restoreDefinition(redefinedClass);
                        this.discardStateForCorrespondingMockClassIfAny(redefinedClass);
                        itr.remove();
                    } else {
                        entry.setValue(previousDefinition);
                    }
                }
            }
        }
    }
