### ISSUE TITLE
mockit.internal.ClassFile$NotFoundException

### ISSUE THREAD

**Issue by samuelliang** [jmockit/jmockit1#272]
* Version of JMockit that was used: 
OS : Windows 7 x64
JDK : 1.7.80 x64
jmockit.version : 1.22
maven.version : 3.3.9

* This is source code : [JMockitDemo.zip](https://github.com/jmockit/jmockit1/files/214465/JMockitDemo.zip)

I found this situation is under mockup, not expectations style. When I manual run test case is always fine. But run under maven(mvn clean test), always happened this issue. So, I suggest whether maven impact jmockit. Have any advise?

I got below messages : 

> [WARNING]
> useSystemClassloader setting has no effect when not forking
> Running jmockit.tutorial.domain.DomainTestSuite
> JMockit: Reinitializing under custom class loader IsolatedClassLoader{roleName='test'}
> Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.453 sec <<< FAILURE! - in jmockit.tutorial.domain.DomainTestSuite
> doBusinessOperationXyzWithInvalidEmailAddress(jmockit.tutorial.domain.MyBusinessService_MockupsAPI_Test)  Time elapsed: 0.016 sec  <<< ERROR!
> java.lang.Exception: Unexpected exception, expected<org.apache.commons.mail.EmailException> but was<mockit.internal.ClassFile$NotFoundException>
> 	at jmockit.tutorial.domain.MyBusinessService_MockupsAPI_Test.doBusinessOperationXyzWithInvalidEmailAddress(MyBusinessService_MockupsAPI_Test.java:70)
> 
> doBusinessOperationXyz(jmockit.tutorial.domain.MyBusinessService_MockupsAPI_Test)  Time elapsed: 0 sec  <<< ERROR!
> mockit.internal.ClassFile$NotFoundException: Unable to find class file for org.apache.commons.mail.$Subclass_Email
> 	at jmockit.tutorial.domain.MyBusinessService_MockupsAPI_Test.doBusinessOperationXyz(MyBusinessService_MockupsAPI_Test.java:51)

**Comment by samuelliang** [comment]
Second action:
Perhaps I uncompleted understand MockUp use case. I suggest whether mockup thirdparty apache mail class cause this issue. So, I try got source code of apache mail then import to this project. Run mvn test again, but still got the same result. Hope anybody give me help.

**Comment by rliesenfeld** [comment]
Just remove the extraneous configuration elements for maven-surefire-plugin in pom.xml (forkCount, reuseForks, and argLine); the tests then work fine. Also, move the "jmockit" dependency before "junit", as noted in JMockit's documentation.

**Comment by samuelliang** [comment]
Dear rliesenfeld:
I had followed your instruction, this time happened my test no run and build failure, below is my logs : 

> Results :
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 2.737 s
> [INFO] Finished at: 2016-04-13T08:18:00+08:00
> [INFO] Final Memory: 14M/226M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project JMockitDemo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was cmd.exe /X /C "D:\javatools(x64)\jdk\jdk1.7.0_80\jre\bin\java -jar D:\works\mylabs\JMockitDemo\target\surefire\surefirebooter438642484915590702.jar D:\works\mylabs\JMockitDemo\target\surefire\surefire9024709274831069346tmp D:\works\mylabs\JMockitDemo\target\surefire\surefire_05767468769503547359tmp"
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by samuelliang** [comment]
Again, I post debug output : 

> [DEBUG] boot classpath:  C:\Users\A00731\.m2\repository\org\apache\maven\surefire\surefire-booter\2.19.1\surefire-booter-2.19.1.jar  C:\Users\A00731\.m2\repository\org\apache\maven\surefire\surefire-api\2.19.1\surefire-api-2.19.1.jar  D:\works\mylabs\JMockitDemo\target\test-classes  D:\works\mylabs\JMockitDemo\target\classes  C:\Users\A00731\.m2\repository\org\jmockit\jmockit\1.22\jmockit-1.22.jar  C:\Users\A00731\.m2\repository\org\jmockit\jmockit-coverage\1.22\jmockit-coverage-1.22.jar  C:\Users\A00731\.m2\repository\javax\persistence\persistence-api\1.0.2\persistence-api-1.0.2.jar  C:\Users\A00731\.m2\repository\javax\mail\mail\1.4.7\mail-1.4.7.jar  C:\Users\A00731\.m2\repository\org\apache\commons\commons-email\1.4\commons-email-1.4.jar  C:\Users\A00731\.m2\repository\com\sun\mail\javax.mail\1.5.2\javax.mail-1.5.2.jar  C:\Users\A00731\.m2\repository\junit\junit\4.12\junit-4.12.jar  C:\Users\A00731\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar  C:\Users\A00731\.m2\repository\org\apache\maven\surefire\surefire-junit4\2.19.1\surefire-junit4-2.19.1.jar
> [DEBUG] boot(compact) classpath:  surefire-booter-2.19.1.jar  surefire-api-2.19.1.jar  test-classes  classes  jmockit-1.22.jar  jmockit-coverage-1.22.jar  persistence-api-1.0.2.jar  mail-1.4.7.jar  commons-email-1.4.jar  javax.mail-1.5.2.jar  junit-4.12.jar  hamcrest-core-1.3.jar  surefire-junit4-2.19.1.jar
> Forking command line: cmd.exe /X /C "D:\javatools(x64)\jdk\jdk1.7.0_80\jre\bin\java -jar D:\works\mylabs\JMockitDemo\target\surefire\surefirebooter7213245287267836103.jar D:\works\mylabs\JMockitDemo\target\surefire\surefire1685738297619779898tmp D:\works\mylabs\JMockitDemo\target\surefire\surefire_08984791721302916169tmp"
> 'D:\javatools' ���O�����Υ~���R�O�B�i���檺�{���Χ妸�ɡC
> 
> Results :
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.049 s
> [INFO] Finished at: 2016-04-13T08:26:26+08:00
> [INFO] Final Memory: 15M/226M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project JMockitDemo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> [ERROR] Command was cmd.exe /X /C "D:\javatools(x64)\jdk\jdk1.7.0_80\jre\bin\java -jar D:\works\mylabs\JMockitDemo\target\surefire\surefirebooter7213245287267836103.jar D:\works\mylabs\JMockitDemo\target\surefire\surefire1685738297619779898tmp D:\works\mylabs\JMockitDemo\target\surefire\surefire_08984791721302916169tmp"
> [ERROR] -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project JMockitDemo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> Command was cmd.exe /X /C "D:\javatools(x64)\jdk\jdk1.7.0_80\jre\bin\java -jar D:\works\mylabs\JMockitDemo\target\surefire\surefirebooter7213245287267836103.jar D:\works\mylabs\JMockitDemo\target\surefire\surefire1685738297619779898tmp D:\works\mylabs\JMockitDemo\target\surefire\surefire_08984791721302916169tmp"
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> Command was cmd.exe /X /C "D:\javatools(x64)\jdk\jdk1.7.0_80\jre\bin\java -jar D:\works\mylabs\JMockitDemo\target\surefire\surefirebooter7213245287267836103.jar D:\works\mylabs\JMockitDemo\target\surefire\surefire1685738297619779898tmp D:\works\mylabs\JMockitDemo\target\surefire\surefire_08984791721302916169tmp"
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 21 more
> Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> Command was cmd.exe /X /C "D:\javatools(x64)\jdk\jdk1.7.0_80\jre\bin\java -jar D:\works\mylabs\JMockitDemo\target\surefire\surefirebooter7213245287267836103.jar D:\works\mylabs\JMockitDemo\target\surefire\surefire1685738297619779898tmp D:\works\mylabs\JMockitDemo\target\surefire\surefire_08984791721302916169tmp"
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:590)
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	... 22 more
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by samuelliang** [comment]
I had found problem cause. Because my folder name has "(" & ")" characters which impact maven-surefire-plugin forking failure. So, when I trim these two illegal characters, just ok. Whatever thank you provide fast advise for me.

**Comment by UchihaYong** [comment]
> I had found problem cause. Because my folder name has "(" & ")" these two special characters which impact maven-surefire-plugin forking failure. So, when I trim these two illegal characters, just ok. Whatever thank you provide fast advise for me.

Hello！ Have you solved the problem? The same problem appears in my project. I don't write forkCount, reuseForks in my maven-surefire-plugin, argline is "-javaagent:*****Jmockit.1.49.jar".
