### ISSUE TITLE
@Mocked and JDK8_77

### ISSUE THREAD

**Issue by karthikpromontory** [jmockit/jmockit1#273]
Please provide the following information:

* Version of JMockit that was used: 
1.16

* Description of the problem or enhancement request:
We have been using the @Mocked annotation for a while in our unit tests now. With JDK8_45 all tests were passing successfully. However, with an upgrade to JDK 8_77, we are getting lots of errors. Example, when using (@Mocked System ), it creates a cascading effect with errors like UnsatisfiedLinkException on java.lang.nanotime() and at other times NoClassDefFoundError. Similarly in cases where we have an @Mocked OurClass, then all future instances of OurClass are using the Mocked version. Again, this did not happen in 8_45 (running on Windows 7, Enterprise, SP 1)

Is there something that needs to change in our tests. 

Thank you
Karthik

**Comment by rliesenfeld** [comment]
I upgraded my JDK installation to 1.8.0_77, but everything is fine; all tests are still passing.
