### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by marcdonovan** [jmockit/jmockit1#275]
Please provide the following information:

* Version of JMockit that was used: 
1.23

* Description of the problem or enhancement request:
Very similar to your post here: http://stackoverflow.com/questions/30502304/how-to-create-a-mocked-by-jmockit-spring-bean

```Java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { ApplicationConfiguration.class } )
public class CoachMarkControllerTests {

    @Tested
    CoachMarkController controller;

    @Injectable
    CoachMarkRepository repository;

    @BeforeClass
    public static void setUpMocksForSpringConfiguration() {
        new MockUp<CoachMarkRepository>() {
            @Mock
            public CoachMark findByCoachMarkId(long coachMarkId){
                return new CoachMark();
            };
        };
    }

    @Test
    public void testGetRouteHappyPath() throws Exception {
        new Expectations() {{
            repository.findByCoachMarkId((long)any);
            result = new CoachMark();
        }};
        controller.getCoachMarkById("1");

    }
}
```

I get a null pointer exception on the first line of Expectations.

**Comment by rliesenfeld** [comment]
The "any" field (used in the recorded expectation) is of type "Object" and has a value of "null". So, trying to cast it to a long with "(long) any" is always going to give you an NPE...

Note the JMockit API has a full set of "any" fields, including "anyLong".

**Comment by marcdonovan** [comment]
Ohhhhh, I didn't realize. 

```
ToStringHelper.toS((Request) any);
```

Is in some existing test that has worked for years. Why does this not throw NPE?

Is it because the cast is an Object type rather than a builtin?

**Comment by marcdonovan** [comment]
could have sworn I tried casting to Object Long, but maybe auto-boxing is causing the same problem.

**Comment by marcdonovan** [comment]
regardless, I will try AnyLong to fix this.
