### ISSUE TITLE
Deencapsulation.setField() is broken for JDK8 after I upgrade to v1.24

### ISSUE THREAD

**Issue by prashant999** [jmockit/jmockit1#281]
Please provide the following information:

* Version of JMockit that was used: v1.24

* Description of the problem or enhancement request:Deencapsulation.setField() is broken for JDK8 after I upgrade to v1.24. My tests started to fail with the following error message:

java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set static final java.util.HashMap field xxx.xxx.xxx to java.util.HashMap
Caused by:
        java.lang.IllegalAccessException: Can not set static final java.util.HashMap field xxx.xxx.xxx to java.util.HashMap
            at java.lang.reflect.Field.set(Field.java:764)
            ... 3 more

**Comment by prashant999** [comment]
Same tests worked fine with JMockit v1.20 and JMockit v1.23

**Comment by rliesenfeld** [comment]
I am unable to reproduce the problem. Could you show an example failing test?

**Comment by prashant999** [comment]
import java.util.HashMap;

public class MyClass {
  private static final int SOME_CONSTANT = 12;

  private static final HashMap map = new HashMap();
}

import org.junit.Test;

import mockit.Deencapsulation;

import static org.junit.Assert.assertEquals;

public class MyClassTest {
  @Test
  public void jMockitBug() {
    MyClass clz = new MyClass();
    int orig = Deencapsulation.getField(MyClass.class, "SOME_CONSTANT");
    Deencapsulation.setField(MyClass.class, "SOME_CONSTANT", 20);
    int updated = Deencapsulation.getField(MyClass.class, "SOME_CONSTANT");
    assertEquals(20, updated);
    Deencapsulation.setField(MyClass.class, "SOME_CONSTANT", orig);
    assertEquals(orig, (int) Deencapsulation.getField(MyClass.class, "SOME_CONSTANT"));
  }
}

There was 1 failure:
1) jMockitBug(MyClassTest)
java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set static final int field MyClass.SOME_CONSTANT to java.lang.Integer
	at MyClassTest.jMockitBug(MyClassTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.IllegalAccessException: Can not set static final int field MyClass.SOME_CONSTANT to java.lang.Integer
	at java.lang.reflect.Field.set(Field.java:764)
	... 3 more

FAILURES!!!
Tests run: 1,  Failures: 1

java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by Vampire** [comment]
Why did you drop that support? This was essential for some of our tests and it worked fine up to 1.24. :-(

**Comment by Vampire** [comment]
Ok, I updated our tests to use a MockUp instead. This is cleaner anyway.

**Comment by rliesenfeld** [comment]
Deencapsulation.setField indeed does *not* support setting a `static final` field.
