### ISSUE TITLE
class redefinition failed: invalid class

### ISSUE THREAD

**Issue by amyroh** [jmockit/jmockit1#282]
Please provide the following information:
* Version of JMockit that was used: 

 0.999 & 1.20

* Description of the problem or enhancement request:

I have a unit test which uses JMockit 1.20.  When I backport the test to a source line with JMockit 0.999, I get a bunch of "class redefinition failed: invalid class" errors.  Adding a simple declaration "@Mocked AppDeployment dep1;" seems to cause this error but I can't seem to find what's missing that is required in 0.999. 

    [junit] Exception in thread "main" java.lang.InternalError: class redefinition failed: invalid class
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
    [junit] 	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:150)
    [junit] 	at mockit.internal.RedefinitionEngine.redefineMethods(RedefinitionEngine.java:232)
    [junit] 	at mockit.internal.RedefinitionEngine.redefineMethods(RedefinitionEngine.java:226)
    [junit] 	at mockit.internal.RedefinitionEngine.restoreOriginalDefinition(RedefinitionEngine.java:263)
    [junit] 	at mockit.internal.state.MockFixture.restoreAndRemoveRedefinedClasses(MockFixture.java:147)
    [junit] 	at mockit.internal.state.SavePoint.restoreClassesRedefinedAfterSavepoint(SavePoint.java:55)
    [junit] 	at mockit.internal.state.SavePoint.rollback(SavePoint.java:35)
    [junit] 	at mockit.internal.state.SavePoint.rollbackForTestClass(SavePoint.java:69)
    [junit] 	at mockit.integration.TestRunnerDecorator.cleanUpMocksFromPreviousTestClass(TestRunnerDecorator.java:76)
    [junit] 	at mockit.integration.junit4.internal.RunNotifierDecorator.discardCurrentTestClassIfNoLongerValid(RunNotifierDecorator.java:54)
    [junit] 	at mockit.integration.junit4.internal.RunNotifierDecorator.fireTestStarted(RunNotifierDecorator.java:35)
    [junit] 	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java)
    [junit] 	at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.startTest(JUnit38ClassRunner.java:35)
    [junit] 	at junit.framework.TestResult.startTest(TestResult.java:155)
    [junit] 	at junit.framework.TestResult.run(TestResult.java:107)
    [junit] 	at junit.framework.TestCase.run(TestCase.java:124)
    [junit] 	at junit.framework.TestSuite.runTest(TestSuite.java:232)
    [junit] 	at junit.framework.TestSuite.run(TestSuite.java:227)
    [junit] 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:79)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:743)

**Comment by rliesenfeld** [comment]
If the failure occurs with JMockit 0.999, then there is nothing to do; problems are only fixed in the current version.
