### ISSUE TITLE
Some tested classes are not included in coverage report

### ISSUE THREAD

**Issue by eoghanoh1** [jmockit/jmockit1#284]
Please provide the following information:

* Version of JMockit that was used: 
1.24

* Description of the problem or enhancement request:
Using jmockit for mocking with JUnit 4 as test runner. Also using jmockit for code coverage.
The issue I am having is that when running coverage some classes are not being outputted to the html coverage report. Other source files in this directory are being outputted to the html. The test suite is testing the classes that are not being outputted.

I do not have any jmockit 'excludes' system JVM arguments set.

Are there any reasons that some classes in a package would be included and some classes would not?

**Comment by rliesenfeld** [comment]
At the very least, if a class is loaded by the JVM during a test run, it should appear in the coverage report, provided it isn't excluded *and* it doesn't come from a jar file (which would usually mean a class from a library used by the code under test).

**Comment by eoghanoh1** [comment]
Apologies I was on vacation for the last two weeks. I do not have any excludes and the class should definitely be loaded by the JVM during the test run. The class is not part of a library (jar). The classes not being included in the coverage report are in the same package as classes that are included in the coverage report. Do you have any other ideas? Thanks.

**Comment by rliesenfeld** [comment]
The "coverage-classes" property is *not* being set, right? If it is, then it needs to include all desired classes.

**Comment by eoghanoh1** [comment]
On jmockit v1.21 I did not have the property set. On upgrade to 1.24, I did set the -Djmockit-coverage-classes property to specify one of the packages that I was having issues with. I thought I read this was a necessary property with the latest version of jmockit? I specified it in the format;
-Djmockit-coverage-classes="a.b.c.src.*"

In either case I was having the same problem.

**Comment by eoghanoh1** [comment]
![eclipserunconfig_tests](https://cloud.githubusercontent.com/assets/17784668/16304376/0b233f74-394d-11e6-9d8f-ea2b9ab60c81.PNG)

Above is a screen shot of the Eclipse run configuration that I am currently using for the tests, showing the VM arguments. I am using JUNIT 4 as the test runner. Are there any other details that would be helpful to identify the problem?

**Comment by eoghanoh1** [comment]
I also just ran the test suite using the -verbose:class VM argument to display all loaded classes. The classes that are not being included in the coverage report are being loaded in the test run.

**Comment by rliesenfeld** [comment]
It should work. You could also try *without* specifying the "coverage-classes" property, to let JMockit uses its defaults. Either way, though, I don't see why it wouldn't include the class in the report.

**Comment by eoghanoh1** [comment]
On v1.24, if I do not have the coverage-classes property set, then no coverage report is outputted at all. It must be required.

**Comment by rliesenfeld** [comment]
If any one of "coverage-output", "coverage-metrics", or "coverage-classes" is set, coverage is activated; this was a change introduced in 1.24, where jmockit-coverage.jar no longer exists.

**Comment by eoghanoh1** [comment]
Ok, thanks. I tried with the coverage-metrics property only and got the same result.

**Comment by rliesenfeld** [comment]
Look, it's no use to keep saying it doesn't work. To me, it is working fine, so I will need a reproducible test case to verify the root cause of the problem on your end.

**Comment by eoghanoh1** [comment]
I have 43 classes in a package, 39 are being included in coverage and 4-5 are not. All 43 classes in the package are being loaded in the test suite run (proven). How am I supposed to reproduce this with a test case? I have no idea what the problem is, that is why I am posting on this site (to try and figure this out). My conclusion is that the coverage is not working as I would expect it to work. How can you say it is working fine from the above information? If there is no way to debug this, then I am probably going to have to move off this coverage tool as I need all classes to be included in the coverage report.

**Comment by eoghanoh1** [comment]
The jmockit jar is before the junit jar in the classpath (see screenshot below of the classpath for the junit test run configuration in Eclipse). 

![image](https://cloud.githubusercontent.com/assets/17784668/16376664/5da897c6-3c59-11e6-85db-069a0f185cc6.png)

**Comment by eoghanoh1** [comment]
Hi, 
What are the next steps we need to take to debug this? Do you give me a debug build or what is required? Thanks for your help, 
Eoghan

**Comment by rliesenfeld** [comment]
It's up to you to provide some reproducible test case, or enough technical information that I can create one. I am aware of certain problems in the coverage tool (see open issues), but not any problem that causes some classes to not appear in the HTML report.

**Comment by eoghanoh1** [comment]
As I said I dont know how I could come up with a test case to reproduce this if I do not have any idea of the the cause of the problem. What technical information are you are looking for?
In your previous comment, you mentioned putting a breakpoint in ClassModification.java to debug, is this a possibilty? 
If not and there is no other way to get to the bottom of this, then unfortunately I will be moving to another tool for code coverage. Honestly I dont have any more spare time to figure this out, I need all classes to be included in the coverage report and I dont really feel like we are getting anywhere.

**Comment by rliesenfeld** [comment]
Yes, you can set a breakpoint anywhere inside JMockit source code (the jmockit.jar file from the zip distribution file contains ".java" files, and for Maven there is the jmockit-sources-1.xx.jar artifact), by using the Eclipse IDE.
