### ISSUE TITLE
@Autowired must come with @Injectable?

### ISSUE THREAD

**Issue by cqsuper** [jmockit/jmockit1#285]
Please provide the following information:
```java
import org.springframework.beans.factory.annotation.Autowired;


public class ServiceA {
    @Autowired
    InterfaceA interfaceA;
    @Autowired
    InterfaceB interfaceB;

    public String hi(){
        return interfaceA.a();
    }

    // other code ...

    public interface InterfaceB {
    }

    public interface InterfaceA {
        String a();
    }
}
```
TestClass:
```java
import org.testng.Assert;
import org.testng.annotations.Test;

import mockit.Expectations;
import mockit.Injectable;
import mockit.Tested;

public class ServiceATest {
    @Tested
    ServiceA serviceA;
    @Injectable
    ServiceA.InterfaceA interfaceA;

    @Test
    public void test1(){
        new Expectations(){
            {
                interfaceA.a();
                result = "aa";
            }
        };
        Assert.assertEquals(serviceA.hi(),"aa");
    }

}
```

Then throw Exception:
java.lang.IllegalStateException: Missing @Injectable for field ServiceA#interfaceB, of type mockit.test.ServiceA$InterfaceB

When i have a class has many @Autowired, then i must add @Injectable.
may be i just want test some methods, but i have to add all @Autowired..

* Version of JMockit that was used: 
1.23

* Description of the problem or enhancement request:

**Comment by rliesenfeld** [comment]
Yes, @Autowired fields have to be satisfied when using @Tested. This can be achieved by providing suitable @Injectable's, or by using @Tested(fullyInitialized = true).

**Comment by chao-luo** [comment]
@rliesenfeld As I read the last code, the `fullyInitialized` is only working some interface, How to handle our interface ? thanks
