### ISSUE TITLE
JMockit Initialization on WildFly

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#286]
It would be great if JMockit would be better usable in Arquillian Integration Test - resp. Application Server - scenarios.

We are about to implement integration tests with Arquillian against a running WildFly application server.
To use JMockit in this situation, the only option is to start the WildFly server with the `-javaagent` option.

There were some problems with the other methods.

1. JMockit does not correclty find its JAR file, as it is not available on disk, but only in a virtual file system (`vfs:`) of WildFly, so what JMockit gives to `loadAgent` the path `D:/Programme/wildfly-8.1.0.Final/content/mod-cm-integTest-2016R2.ear/lib/jmockit-1.24.jar` which does not exist of course and leads to the error `Error opening zip file or JAR manifest missing: D:/Programme/wildfly-8.1.0.Final/content/mod-cm-integTest-2016R2.ear/lib/jmockit-1.24.jar`.  
It could even be that there is not even a real file system present which is prefectly fine according to the Java EE specification.

 It would be nice if JMockit would check for the presence of the `jmockit.jar` path it determined.  
 If the check is positive, the current method can go on, if not, maybe the needed `jmockit.jar` can be created on-disk (if a disk is present) and then this generated file being used as argument for the `loadAgent` method.

2. Some automatic initialization in this context would be nice, as you cannot really influence the order on the classpath and thus cannot make sure that JMockit is in the classpath before JUnit. But using `JMockit` as runner is also not an option, as the runner has to be `Arquillian`, so some other means of initialisation like some "on deploy hook" would be nice.

3. JMockit is tried to be initialized mutiple times if you do undeploy / deploy cycles which is the case with Arquillian as for every test class the EAR is newly deployed and after the test undeployed. This leads to multiple problems.

 The first problem is, that the JVM can load a native library only from one class loader at a time. This means, if you run the second deployment without restarting the WildFly, you get `java.lang.UnsatisfiedLinkError: Native Library C:\Program Files\Java\jdk1.8.0_77\jre\bin\attach.dll already loaded in another classloader`, as it is already loaded in the classloader of the former deployment. Actually I guess the mocking would still work if the former call did succeed and thus did initialize JMockit, but I don't know, as it doesn't work at all.

 Maybe it would be an idea to not use static fields to determine whether JMockit is initialized already, but some means that is controlled by the JMockit Java Agent, like rewriting a hard-coded `final` `boolean` that is `false` at compile time to `true` at runtime and then check this boolean or something like that, then the determination whether JMockit is already initialized should probably work better even in this case of multiple class loaders.

 Actually this would also eliminate the native library on multiple class loaders problem in most cases, as long as not something else did use the attach api already in this VM, but I guess this is not too likely to happen and at least it would improve the situation much.

**Comment by rliesenfeld** [comment]
Good points. Regarding each one:

1. I will investigate a way to auto-load the Java agent when jmockit.jar is inside another jar file (like an EAR or WAR file).

2. When using JUnit 4, I don't see any other way than to have jmockit.jar first in the runtime classpath, or using @RunWith(JMockit). TestNG doesn't have this problem, though, neither JUnit 5.

3. I suspect there is no simple change (or even any set of changes) that can be made to JMockit in order to work in such anomalous cases. The real problem here is the way that Arquillian works.

The solution I would recommend is to *not* use Arquillian. Of course this is my biased opinion, but Arquillian is really an awful testing tool. I tried it in the past, and came to the conclusion that in-container integration testing is just not the way to go. In particular, the need to generate a war/ear file every time you want to execute a test run is just not viable.

In real-world projects, I favor integration tests, so support was added in JMockit for *out-of-container* integration testing. Bottom-line: I have Spring- and Java EE-based projects with hundreds of integration tests, which can be promptly executed from the IDE (without noticeable startup time), are clean, reliable, and fast to execute. In my experience, this would simply not be possible if I used Arquillian.

**Comment by Vampire** [comment]
> 1) I will investigate a way to auto-load the Java agent when jmockit.jar is inside another jar file (like an EAR or WAR file)

Keep in mind, not only inside another JAR, or even deeper nested.
In the case of WildFly it is even only available in a virtual filesystem and not on disk.
And if I don't recall the Attach API wrongly, you can only give it a file system path.
So I guess it is really the only way to check whether the determined `jmockit.jar` exists with `new File(...).exists()` and if not, trying to create a JAR at the filesystem with the needed classes, maybe already prepared inside the JMockit JAR and then extracted to a temporary file.
If that was successful it can be loaded with `loadAgent()`, if not there is probably no filesystem around to write the file onto as is perfectly fine for JEE.

> 2) When using JUnit 4, I don't see any other way than to have jmockit.jar first in the runtime classpath, or using @RunWith(JMockit). TestNG doesn't have this problem, though, neither JUnit 5.

And why could not JMockit be teached to initialize itself on EAR deployment, e. g. by adding a @javax.ejb.Startup bean that does the `initializeIfPossible()` call? Usually in such situations the actual test that use JMockit should not be run until after the deployable deployed completely.

For WARs that get tested this way, maybe a `javax.servlet.ServletContextListener` can be provided that does the initilization call and has to be defined in the SUTs `web.xml`.

> 3) I suspect there is no simple change (or even any set of changes) that can be made to JMockit in order to work in such anomalous cases. The real problem here is the way that Arquillian works.

What is anomalous in undeploying and redeploying an EAR?  

And I'm curious, what in particular do you think is bad with my idea of not depending on static fields that get reset with a new class loader in a new deployment but instead checking some JMockit-manipulated field `initialized`?

> The solution I would recommend is to not use Arquillian. Of course this is my biased opinion, but Arquillian is really an awful testing tool. I tried it in the past, and came to the conclusion that in-container integration testing is just not the way to go. In particular, the need to generate a war/ear file every time you want to execute a test run is just not viable.

> In real-world projects, I favor integration tests, so support was added in JMockit for out-of-container integration testing. Bottom-line: I have Spring- and Java EE-based projects with hundreds of integration tests, which can be promptly executed from the IDE (without noticeable startup time), are clean, reliable, and fast to execute. In my experience, this would simply not be possible if I used Arquillian.

Well, not using Arquillian is out of question currently. Our architects decided it is the way to go for now, and I don't have any evidence to tell them they are wrong. I'm just having the task to get it run properly currently. Maybe we will see in the near future that it is bullshit and will step away from it, but for now I have to get it going.

The out-of-container integration tests that you do are simply a different kettle of fish, doing more mocks and less real-world testing. Of course the in-container tests are more time-consuming, especially with the EAR-manipulation and stuff, but for now it is the way to go here and we will see where it leads us to.

**Comment by rliesenfeld** [comment]
Actually, my out-of-container tests do no mocking at all (except for mocking the JSF FacesContext object, or mock-ups for things like Struts integration).

Anyway, after some more thought I came back to the same conclusion reached on previous requests for adding Arquillian support: it's just not something that can be done without a lot of work, and since I would never use it myself, I prefer to close the issue as "won't fix". This is something that should be done by other developers, who actually use Arquillian for testing.

**Comment by Vampire** [comment]
Well, actually the requests here are not so much about Arquillian, but about WildFly, or any other similar environment.

**Comment by rliesenfeld** [comment]
Ok, but then I would need to understand the use case to the point I can write a small sample test case as a starting point for development.

**Comment by Vampire** [comment]
Well, for 1. I guess the test would be to mock the JAR finding to return an invalid path, so that then the production code has to create the agent jar on disk somehow and load that.
For 2. I'm not sure how to test this best without actually deploying an EAR and a WAR in an application server.
For 3. It is certainly possible to write a test, but I'm not sure whether it will be small. I think you need a custom classloader that completely replaces the system classloader like it can be found in the IntelliJ IDEA Community sourcecode, then make two instances of this classloader and try to initialize JMockit on those classloaders. I think you should then get the error that you cannot load the native attach API library from two classloaders. If you then do the "already initialized" check in the way I suggested, the test should probably become green and a second test could make sure that JMockit is not initialized again via Attach API if it is already loaded via `-javaagent` parameter.

**Comment by rliesenfeld** [comment]
Out of curiosity, what is the actual need, in your real-world project, for tests to run inside a Java EE app server? Is it having access to JMS queues? REST/web service endpoints? Or just simpler things like the JPA EntityManager? Or is it about WebDriver/HtmlUnit-based tests?

**Comment by rliesenfeld** [comment]
Coming back to the original post, it says "To use JMockit in this situation, the only option is to start the WildFly server with the -javaagent option." So, that's the best solution I can think of. This whole issue is too confusing, with much discussion about imagined solutions when the problem to be solved is not clear.

**Comment by Vampire** [comment]
I cannot tell you the reasoning for running the tests with Arquillian inside the appserver, as it was not my decision. I just have to make it work. You'd have to discuss this with our architects. ;-)
Maybe they think this way the tests are as realistic as possible, which would not be too wrong. :-)

Actually I think the problem is pretty clear. :-(

And starting WildFly with `-javaagent` option is a pretty bad option, as it tremendously increases the cost of updating JMockit frequently as new releases are brought out. Because you will always have to make sure the developer executing the tests has the correct JMockit version configured in his WildFly for the branch he is testing currently and also the server where the CI server is testing against has to be kept in sync, ....
If it would be possible to just use the one included with the deployable, all this problems would be gone instantly and it would just work.
