### ISSUE TITLE
Possibility to inject productive instances instead of mocks, or at least partial mocks

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#287]
I'm in the process of upgrading our JMockit 1.8 based tests to JMockit 1.24.
With 1.8 only the fields that were needed during the test had `@Injectable` annotations to be injected into the `@Tested` instance.
Now with the new JMockit version, all DI-injected stuff needs an injectable available, which I find ok and reasonable basically.

But now I have a problem. Before I was able to manually inject real unmocked objects. For this I had something like 

```
public class SessionFilterTest extends BaseHttpTest
{
   @Tested
   private SessionFilter sessionFilter;
   @Injectable
   private HttpSession httpSession;
   @Injectable
   private HttpServletRequest servletRequest;
   @Injectable
   private HttpServletResponse servletResponse;

   private RequestLogger requestLogger = new RequestLogger();

   @Test
   public void doTest() throws Exception
   {
      // some code

      // inject the requestLogger
      Deencapsulation.setField(sessionFilter, "requestLogger", requestLogger);

      // the actual SUT method
      sessionFilter.doFilter(servletRequest, servletResponse, filterChain2);

      // check assertions against requestLogger
   }
}
```

Now with the new JMockit you have to provide the request logger as `@Injectable`, as it bears `@Inject` in the `SessionFilter`.
So I thought I might do the following:

```
public class SessionFilterTest extends BaseHttpTest
{
   @Tested
   private SessionFilter sessionFilter;
   @Injectable
   private HttpSession httpSession;
   @Injectable
   private HttpServletRequest servletRequest;
   @Injectable
   private HttpServletResponse servletResponse;

   @Injectable // <=== add annotation
   private RequestLogger requestLogger = new RequestLogger();

   @Test
   public void doTest() throws Exception
   {
      // some code

      // inject the requestLogger
      // Deencapsulation.setField(sessionFilter, "requestLogger", requestLogger); // <=== comment this out

      // the actual SUT method
      sessionFilter.doFilter(servletRequest, servletResponse, filterChain2);

      // check assertions against requestLogger
   }
}
```

But this did not work, as now through the `@Injectable` the instance is made a mock without any way to make it partial. I tried adding `requestLogger` as parameter to `new Expectations()`, and other stuff. I've only seen three ways to do it, all more or less ugly. If there is another, more clean, way, please don't hesitate to tell me.

The three working methods I found were:

```
public class SessionFilterTest extends BaseHttpTest
{
   @Tested
   private SessionFilter sessionFilter;
   @Injectable
   private HttpSession httpSession;
   @Injectable
   private HttpServletRequest servletRequest;
   @Injectable
   private HttpServletResponse servletResponse;

   @Injectable // <=== add annotation to make JMockit happy
   private RequestLogger requestLogger;
   private RequestLogger requestLogger2 = new RequestLogger(); // <=== make a new unmocked instance to be manually injected

   @Test
   public void doTest() throws Exception
   {
      // some code

      // inject the requestLogger
      Deencapsulation.setField(sessionFilter, "requestLogger", requestLogger2); // <=== inject requestLogger2 to replace the mocked instance

      // the actual SUT method
      sessionFilter.doFilter(servletRequest, servletResponse, filterChain2);

      // check assertions against requestLogger
   }
}
```

and

```
public class SessionFilterTest extends BaseHttpTest
{
   @Tested
   private SessionFilter sessionFilter;
   @Injectable
   private HttpSession httpSession;
   @Injectable
   private HttpServletRequest servletRequest;
   @Injectable
   private HttpServletResponse servletResponse;

   @Injectable // <=== add annotation to make JMockit happy
   private RequestLogger requestLogger;

   @Test
   public void doTest() throws Exception
   {
      // some code

      new Expectations() // <=== create mock delegates for all needed methods, this way making a partial mock the other way around, defining which real methods should be called
      {
         {
            requestLogger.logHttpRequest(withAny(servletRequest));
            result = new Delegate()
            {
               void delegate(Invocation invocation)
               {
                  invocation.proceed(invocation.getInvokedArguments());
               }
            };

            requestLogger.logInfo(anyString);
            result = new Delegate()
            {
               void delegate(Invocation invocation)
               {
                  invocation.proceed(invocation.getInvokedArguments());
               }
            };
         }
      }

      // inject the requestLogger
      // Deencapsulation.setField(sessionFilter, "requestLogger", requestLogger); // <=== comment out

      // the actual SUT method
      sessionFilter.doFilter(servletRequest, servletResponse, filterChain2);

      // check assertions against requestLogger
   }
}
```

and, and I actually wonder why this actually worked and was not mocked away, can you explain this?

```
public class SessionFilterTest extends BaseHttpTest
{
   @Tested
   private SessionFilter sessionFilter;
   @Injectable
   private HttpSession httpSession;
   @Injectable
   private HttpServletRequest servletRequest;
   @Injectable
   private HttpServletResponse servletResponse;

   @Injectable // <=== add annotation to make JMockit happy
   private RequestLogger requestLogger = new RequestLogger() // <=== make a new subclass
   {
      // overwrite the needed real methods
      @Override
      public void logHttpRequest(HttpServletRequest request)
      {
         // copy production code here, calling super.logHttpRequest(request) does not work
         // also make every private method and field you need protected in the superclass or copy it below
      }

      @Override
      public void logInfo(String logString)
      {
         // copy production code here, calling super.logInfo(logString) does not work
         // also make every private method and field you need protected in the superclass or copy it below
      }
   };

   @Test
   public void doTest() throws Exception
   {
      // some code

      // inject the requestLogger
      // Deencapsulation.setField(sessionFilter, "requestLogger", requestLogger); // <=== comment out

      // the actual SUT method
      sessionFilter.doFilter(servletRequest, servletResponse, filterChain2);

      // check assertions against requestLogger
   }
}
```

**Comment by rliesenfeld** [comment]
I think you are missing the integration testing support in @Tested, activated by "@Tested(fullyInitialized = true)". This is a very sophisticated and powerful feature; it's what I use in my real-word projects, rather than the mocking API.

**Comment by Vampire** [comment]
Hm, from its JavaDoc I'm not really seeing how it applies, can you elaborate a bit more?
From the JavaDoc I don't get the impression that you can inject your own productive instances, but that each and everything will be filled by JMockit automatically. Also the Tutorial on the Website does not say anything about this parameter.

**Comment by rliesenfeld** [comment]
Taking the first test in the issue as example, the test would simply specify "@Tested(fullyInitialized = true) SessionFilter sessionFilter", which would cause a "new RequestLogger()" to get automatically injected to the proper field.

"fullyInitialized = true" gives full support for @Inject, @Autowired, @PersistenceContext, etc., and to un-annotated fields when that's the case.

The API documentation has all the details (I hope), but the chapter in the Tutorial ("Testing enterprise applications") hasn't been written yet (version 1.25 has some improvements for fullyInitialized and by release time the chapter should be written - sample test suites are already finalized).

**Comment by Vampire** [comment]
So you mean in this case I would do the fullyInitialized thing,
this would also initialize the `@Inject RequestLogger`, even without an `@Injectable RequestLogger` but with a real instance?
And then for verfying the result I have to use `Deencapsulation` to reach the created `RequestLogger` or how would this work? *confused*

**Comment by Vampire** [comment]
Is this also what should be done in the following situation?

I have a `@Tested Converter` field that gets an `@Injectable MessageFactory` injected. Now in one of the tests I need to influence what is returned by one of the methods of `MessageFactory`. If I write an `Expectations` block, it is ignored. If I write a `MockUp<MessageFactory>` it errors out saying the class is already mocked.



Btw. could you maybe answer the question in the original post right before the last example?

**Comment by rliesenfeld** [comment]
The API documentation for @Tested is still missing this fact, but it also looks for other @Tested objects when trying to satisfy injection points (fields or constructor parameters to receive injected values). So, simply add a "@Tested RequestLogger requestLogger;" to the test class; this same instance will be used for injection into other tested objects, where applicable.

As for recording expectations on @Injectable's that get injected into @Tested objects, you will need to record them in an @Before method if the expectation results are needed in @Tested constructors,  or in @PostConstruct or servlet init methods.

There is also "@Tested(availableDuringSetup = true)", which is useful to configure @Tested objects that get injected into other @Tested objects.

**Comment by Vampire** [comment]
> The API documentation for @Tested is still missing this fact, but it also looks for other @Tested objects when trying to satisfy injection points (fields or constructor parameters to receive injected values). So, simply add a "@Tested RequestLogger requestLogger;" to the test class; this same instance will be used for injection into other tested objects, where applicable.

Hm, either this is not yet in 1.24 or there is a bug. But actually adding `@Tested` *and* `@Injectable` made it work.

> As for recording expectations on @Injectable's that get injected into @Tested objects, you will need to record them in an @Before method if the expectation results are needed in @Tested constructors, or in @PostConstruct or servlet init methods.

Ah, that makes sense, thanks. Yep, if I write the expectations needed in `@PostConstruct` in `@Before` and the other ones in `@Test` both actually work fine.

Actually I'm still interested in the answer to the question in the original post right before the last example. Would you mind answering it? Is it a bug that this example actually worked? Is it an intended feature? Is this behaviour documented somewhere I didn't see?

**Comment by rliesenfeld** [comment]
The "why this actually worked and was not mocked away" question? I don't know; the test is weird, but I don't see why it wouldn't work.

**Comment by Vampire** [comment]
What I wonder is, why the calls to the overridden methods are not mocked away, but the real methods are called. If I do `new RequestLogger();`, all calls are mocked and replaced by standard implementations (if no `Expectations` are set), but if I do `new RequestLogger() { /* override some method here */ };` the overridden "production" method is used instead of the default mocked one.

**Comment by rliesenfeld** [comment]
You mean, why the real methods from class RequestLogger still get executed on a subclass of RequestLogger? Yes, that's to be expected when using @Injectable or @Mocked for the base class alone. @Capturing, OTOH, would also mock any subclass including the overridden methods.

**Comment by Vampire** [comment]
Ah, great thanks, that makes much more sense now, knowing (or having in mind) that `@Mocked` and `@Injectable` only mock the specific class and not subclasses and thus overridden methods. (Or should overridden methods be mocked maybe?)
