### ISSUE TITLE
Missing call verifyMissingInvocations

### ISSUE THREAD

**Issue by wagnjun** [jmockit/jmockit1#291]
Please provide the following information:

* Version of JMockit that was used: 
1.24

* Description of the problem or enhancement request:

`@Mock(minInvocations = x) ` is not working, I think blow code has bug at class `mockit.internal.mockups.MockState`
```
   boolean update()
   {
      if (proceedingInvocation != null) {
         MockInvocation invocation = proceedingInvocation.get();

         if (invocation != null && invocation.proceeding) {
            invocation.proceeding = false;
            return false;
         }
      }

      int timesInvoked;

      synchronized (invocationCountLock) {
         timesInvoked = ++invocationCount;
      }

      verifyUnexpectedInvocation(timesInvoked);
      return true;
   }
``` 

The code just call `verifyUnexpectedInvocation()`, but not `verifyUnexpectedInvocation()`

**Comment by rliesenfeld** [comment]
I would need to see an example test where it doesn't work. Can you provide that?
