### ISSUE TITLE
@Tested for parameters

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#293]
Maybe there is a reason that `@Tested` is only applicable to instance fields, not method parameters, but out of the blue I cannot come up with one, so I'd like to suggest opening up `@Tested` to method parameters.

**Comment by rliesenfeld** [comment]
But what would be the reason to *allow* @Tested in test method parameters? (Note all other mocking libraries, and several other testing tools, have some @Tested analog, but none allow it for parameters.) What would a legitimate and realistic example test look like?

**Comment by Vampire** [comment]
Well, `@Mocked` is also allowed in the parameters, isn't it? Why should `@Tested` not be? Especially if you use auxiliary `@Tested @Injectable` objects like you taught me about in #287.

Or maybe someone wants to test different SUTs in one test class and only wants the respective SUT in the scope of the test method. (while I guess this is bad practice)

Note: Why always do stuff like the others, be better and more flexible. ;-)

**Comment by rliesenfeld** [comment]
@Tested on parameters is now allowed (since 1.32).
