### ISSUE TITLE
Fail with 2 @Tests when mock JpaRepository

### ISSUE THREAD

**Issue by tianxialangui** [jmockit/jmockit1#295]
Please provide the following information:

* Version of JMockit that was used: 
1.23

* Description of the problem or enhancement request:
I use JMockit mock JpaRepository interface. but my test fail when there is more than 1 test.

I don't know how to descript it, so I put a test projects.
[jmockit-bug.zip](https://github.com/jmockit/jmockit1/files/320867/jmockit-bug.zip)

sometimes I get an error:
<img width="487" alt="2" src="https://cloud.githubusercontent.com/assets/4637503/16156919/ecea5406-34e8-11e6-86e9-77174ebfd656.png">

but sometimes I can success.

if I delete the function
```
@Test public void constructor(@Mocked MyCurdRepository rep)
```
I always success.

**Comment by rliesenfeld** [comment]
Same fix as #294.
