### ISSUE TITLE
IllegalArgumentException in withCapture(List)

### ISSUE THREAD

**Issue by krororo** [jmockit/jmockit1#307]
Please provide the following information:

* Version of JMockit that was used: 
1.25

* Description of the problem or enhancement request:

example code

```java
    public class Hoge {
        public void foo(List<String> arg) {
            return;
        }
    }

    @Test
    public void testSample(@Mocked final Hoge mock) {
        mock.foo(Arrays.asList("a", "b", "c"));
        mock.foo(Arrays.asList("d", "e", "f"));

        new Verifications() { {
            List<List<String>> actual = new ArrayList<>();

            mock.foo(withCapture(actual));

            assertThat(actual.get(0), contains("a", "b", "c"));
            assertThat(actual.get(1), contains("d", "e", "f"));
        } };
    }
```

It works on 1.24. But on 1.25, `java.lang.IllegalArgumentException: No class with name "java.util.List<Ljava.lang.String" found` occurred.

**Comment by rliesenfeld** [comment]
Thanks for reporting.
As a workaround until the regression is fixed, the problem can be avoided by moving the capturing variable outside the verification block.

**Comment by rliesenfeld** [comment]
Fixed.
