### ISSUE TITLE
Announcement to set attributes in @Mock to be deprecated should be reconsidered

### ISSUE THREAD

**Issue by UlrichLohrmann** [jmockit/jmockit1#312]
We use jMockit 1.25.
With jMockit 1.26 the attributes invocations, minInvocations and maxInvocations are announced to become deprecated. That should be reconsidered.
We use @Mock with the said attributes to verify whether private methodes of tested classes are called (invocations=1) or not (invocations=0).
With jMockit version 1.23 the use of invoke() to mock private methods was dropped and the use of the MockUp API was recommended to mock private methods.
If the attributes are dropped from the @Mock annotation, how can a call to a private methode can be verified then without support in the expectation API and without invocation count support in the MockUp annotation?

**Comment by rliesenfeld** [comment]
Well, mocking a private method in order to verify it got called is not something normally done.
Private methods are implementation details, so the standard advice is to test them through some public method.

The rationale for dropping features such as private method mocking, or the @Mock attributes, is that these features either do more harm than good or simply don't get used.

Could you show a realistic example test demonstrating a case where mocking a private method with a MockUp (and using the "invocations" attribute) is better than the alternative? That would go a long way in helping me decide if these attributes should be kept or not.

**Comment by UlrichLohrmann** [comment]
Our test philosophy is that a unit test only tests the code of ONE method. If the tested method calls other (private) methods, these calls are mocked and the test verifies whether the call to the (private) mocked methods has been executed within the test execution. The code of the called (private) methods is verified using separate tests.
We have thousands of tests that are based on this philosopy and about 50% use mocking private methods.
BTW The deprecation of mocking private methods using invoke() in jMockit 1.23 had big impact to our tests. We had to change nearly 4000 different tests to use MockUp() as suggested to mock the private methods which took us weeks of time. 
If the invocation of a private (mocked) method could not be verified with further versions of jMockit this would be a big limitation for the use of jMockit.

**Comment by UlrichLohrmann** [comment]
Sorry, clicked "close and comment" instead of only "comment".

**Comment by rliesenfeld** [comment]
What you describe is very much the kind of usage that prompted me to drop support for the mocking of private methods. If you search online or in books, you'll see that this is far from what "testing gurus" recommend. Kent Beck (creator of TDD) and Martin Fowler, in particular, don't even mock *public* methods (they favor "classical" state-based tests, with no mocking - as do I). And even those that advocate mocking are against mocking private methods, the reason essentially being that private methods/constructors/fields are *implementation details*, and good tests should not depend on implementation details as doing so makes them fragile (among other problems).

**Comment by UlrichLohrmann** [comment]
I think a tool like jMockit should give its users the freedom to implement their tests as they like not as "testing gurus" recommend. Even if private methods are "implementation" details they implement logic. If I implement a test I want to focus on the logic of the tested method. Calls to other methods or even other components called are not of interest in that test (at least for me).
You have to decide whether jMockit will be a tool that reflects ideas from "test gurus" but is useless in the real world or whether you listen to the users of your tool and their wished and ideas. If you continue to drop features from jMockit it is only a question of time until jMockit will become useless.

**Comment by rliesenfeld** [comment]
I use JMockit on real-world tests nearly every day. And beyond that, there's ~11 years of experience with JUnit/TestNG and other testing tools. After all this time, I can see the mistakes and bad ideas of the past. About private methods, I never feel the need to mock or fake them, and every time I see a test that does it, it is clearly (to me, anyway) a bad test. In my view, not supporting certain testing practices is doing a favor to less experienced developers, even if they don't currently see it that way.

In any case, MockUp's will always support @Mock's for private methods, as it's needed for testing infrastructure. The "invocation" attributes don't really make sense to exist in this API, though; but note they can be emulated without much trouble by having fields in the mock-up subclass.
