### ISSUE TITLE
Using invoke() on a partially-mocked @Tested object passes on JMockit 1.22, fails on JMockit 1.23+

### ISSUE THREAD

**Issue by Thunderforge** [jmockit/jmockit1#321]
I have a test that passes on JMockit 1.22, but fails on JMockit 1.23+ (including 1.26, the current release).

Consider a class that has one public method and two private methods. 

    public class JMockitIssueClass {

        public boolean publicBooleanMethod() {
            return privateBooleanMethod1() && privateBooleanMethod2();
        }

        public boolean privateBooleanMethod1(){
            return false;
        }

        public boolean privateBooleanMethod2(){
            return false;
        }
    }

Say that we want to write a test for this, and that involves mocking the two private methods using `invoke`

    public class JMockitIssueClassTest {

        @Tested
        private JMockitIssueClass jMockitIssueClass;

        @Test
        public void publicBooleanMethodTest() {

            new Expectations(jMockitIssueClass) {{
                invoke(jMockitIssueClass, "privateBooleanMethod1");
                result = true; //Exception happens here
                invoke(jMockitIssueClass, "privateBooleanMethod2");
                result = true;
            }};

            jMockitIssueClass.publicBooleanMethod();
        }
    }

On JMockit 1.22, the test passes without error. On JMockit 1.23+, the following error appears:

    java.lang.IllegalStateException: Missing invocation to mocked type at this point; please make sure such invocations appear only after the declaration of a suitable mock field or parameter
     	at com.example.JMockitIssueClassTest$1.<init>(JMockitIssueClassTest.java:28)
        at com.example.JMockitIssueClassTest.publicBooleanMethodTest(JMockitIssueClassTest.java:26)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
    	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

In this case, the line number actually points to the first use of `result = true;`. Given the message, it looks like it is complaining that `result` is not mocked, which is obviously in error.

In more complex situations, I have also seen errors where two private methods  mocked using `invoke()` have different return types...

    final Map<MyObject, Object> params = new EnumMap<>(MyObject.class);

    new Expectations(xmlResultsExporter) {{
        invoke(xmlResultsExporter, "isServiceOnline");
        result = true;
        invoke(xmlResultsExporter, "makeParamMap", 1);
        result = params; //Fails on this line
    }};

...which results in the second method, which properly mocks an `EnumMap`, says that it is instead returning a boolean, which the code above says that it is clearly not.

    java.lang.IllegalArgumentException: Value of type java.util.EnumMap incompatible with return type boolean of com.example.XmlResultsExporter#isServiceOnline()

Again, this works fine in JMockit `1.22`.

**Comment by rliesenfeld** [comment]
Yes, support for private method mocking was dropped in version 1.23, as noted in the [release notes](http://jmockit.org/changes.html#1.23) for that version.

**Comment by Thunderforge** [comment]
Didn't realize that. Thanks for pointing it out to me.

**Comment by Thunderforge** [comment]
@rliesenfeld Is it possible that the error message could be changed to something more usefu? Something like "mocking of private methods is not supported"? As is, the error message does not accurately describe the situation.

**Comment by rliesenfeld** [comment]
It's possible, but too costly to implement, I am afraid.

**Comment by rliesenfeld** [comment]
The requested enhancement has now been implemented.
