### ISSUE TITLE
Method refactoring causes tests to fail

### ISSUE THREAD

**Issue by KidCrippler** [jmockit/jmockit1#323]
This is not really a bug, more like an anecdote.

When a method is being mocked using the MockUps API (`@Mocked` annotation), JMockit matches the mocked up method to the real one by the types of the input parameters.
When I change the signature of a mocked method, there's no way for the tested code to know that and the test will fail at runtime with the following:

> java.lang.IllegalArgumentException: Matching real methods not found for the following mocks:
> ...

This is not the case in the expectations API in which you actually call the method and get a compilation error if its signature has changed.

Is there anyway around it? Maybe using an eclipse plugin or anything like that?

Thanks

**Comment by rliesenfeld** [comment]
There is a 3rd-party Eclipse plugin for the MockUps API, but it hasn't been updated in a while, and AFAIK it isn't maintained anymore.
