### ISSUE TITLE
JMockit static method mockup scope

### ISSUE THREAD

**Issue by xeric** [jmockit/jmockit1#325]
Please provide the following information:
* Version of JMockit that was used: 
JMockit 1.26

* Description of the problem or enhancement request:
When use parallel execution for UT, and if one static method is call in both test case, the mockup will effect on both test case even the mockup is only written in one side.
Run parallel test case in JUnit is like this:
JUnitCore.runClasses(new ParallelComputer(true, true), {TestClasses});

Expectation:
The static method mockup effect scope can be controlled.

Found another similar post in Google Group:
https://groups.google.com/forum/#!topic/jmockit-users/vc-7J3lIrlM 

Sample TestCase:
```java
package com.xeric.test;

import mockit.Expectations;
import org.junit.Assert;
import org.junit.Test;
import org.junit.experimental.ParallelComputer;
import org.junit.runner.JUnitCore;

public class ParallelUnitTest {
  @Test
  public void mainTest() {
    Class[] cls = {ParallelTest1.class, ParallelTest2.class};

    JUnitCore.runClasses(new ParallelComputer(true, true), cls);
  }

  public static class ParallelTest1 {
    @Test
    public void a() throws InterruptedException {
      System.out.println("start to mock util begin 1111");
      SomeClass sc = new SomeClass();

      new Expectations(Util.class) {
        {
          Util.isTrue();
          result = false;
        }
      };

      Assert.assertEquals(false, sc.doSomething());
      Thread.sleep(10000L);
      System.out.println("stop mock util 1111");
    }
  }

  public static class ParallelTest2 {
    @Test
    public void a() throws InterruptedException {
      Thread.sleep(5000L);

      System.out.println("start 222");
      System.out.println(Util.isTrue());
      //failed here
      Assert.assertEquals(true, Util.isTrue());
      System.out.println("stop 2222");
    }
  }

  public static class Util {
    public static boolean isTrue() {
      return true;
    }
  }

  public static class SomeClass {
    public boolean doSomething() {
      return Util.isTrue();
    }
  }
}

**Comment by rliesenfeld** [comment]
This is normal: once a class is mocked in a test, it remains mocked until the end of the test. So, if another test running in another thread happens to call the mocked method, it will still be mocked.

**Comment by xeric** [comment]
When the parallel testing is more and more common in big project, such situation will be a very 'complex' scenario, someone who write test case will just mockup the static method for one business case of itself, for example, a static method with empty parameter to load a class by a configuration(xml), but in different case they will have different configuration, and return a different implementation(IoC), without scope limitation, and if these two cases run at same time, they will affect with each other and due to unexpected result. the worse thing is this is not stable for reproducing since no one can ensure they run at same time point every time, and make it hard to do troubleshooting.
If an thread-safe scope can be provided, the isolation of test case could be well controlled and let jmockit more powerful in such parallel testing environment.

**Comment by akarollil-impact** [comment]
I am pretty sure I ran into this when using the following `Mockup` from within a test. Another test running in parallel ended up using the mock.

```
new MockUp<ClassWithStaticMethod>() {

            @Mock
            public ClassWithStaticMethod staticMethod(HttpServletRequest request) {
                return null;
            }
        };
```
