### ISSUE TITLE
Path functionality

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#328]
Hello,

I have some questions on path functionality

>> Please provide the following information:

>>* Version of JMockit that was used: 
1.27

>>* Description of the problem or enhancement request:

for this example class under test
public class PathCoverage {

	public void pathCoverage(int i)
	{
		if(i == 0)
			return;
		
		i = i + 1;
		
		privMethod(i);
		return;
	}
	
	private int privMethod(int j)
	{
		for(int i = 0; i < j; ++i)
		{
			System.out.println("here");
		}

		return 0;
	}
}

and this test case

public class TestPathFunctionality {

	@Test
	public void test() {
		new PathCoverage().pathCoverage(3);
	}
}

Path information shows up for the public method but not for the private method. See attached image.

![path1](https://cloud.githubusercontent.com/assets/10885119/18264059/3a091a88-740e-11e6-86f9-ccda3a2e3ecd.PNG)

If I change the class under test to:
public class PathCoverage {

	public void pathCoverage(int i)
	{
		if(i == 0)
			return;
		
		i = i + 1;
		
		privMethod(i);
		return;
	}
	
	private int privMethod(int j)
	{
		for(int i = 0; i < j; ++i)
		{
			System.out.println("here");
		}
		if(j == 0)
		{
			System.out.println("here");
		}
		return 0;
	}
}
with the same test case, I now get some path information for the private method but it is incorrect.
see attached image for that.
![path2](https://cloud.githubusercontent.com/assets/10885119/18264110/9b840250-740e-11e6-8a1f-d25bd7f06fff.PNG)

Am I using the tool incorrectly or is something else wrong?

**Comment by rliesenfeld** [comment]
On my end, I get the expected result:

![image](https://cloud.githubusercontent.com/assets/200378/18296111/54342226-747d-11e6-8aca-da722d22214c.png)
