### ISSUE TITLE
user jmockit and junit,but compile fail for the same class junit.framwork.TestResult.class

### ISSUE THREAD

**Issue by mralong** [jmockit/jmockit1#329]
Please provide the following information:

* Version of JMockit that was used: jmockit 1.8

* Description of the problem or enhancement request:
hi, we prefer to user "jmockit" and "junit" for unit test with android project，but when we compile the project to run test, it fail because the two dependencies "jmockit" and "junit" has the same class define(junit.framwork.TestResult.class). is that some way to solve this problem?

thank you for your response

**Comment by rliesenfeld** [comment]
The jmockit jar does contain a slightly modified JUnit class (org.junit.runner.Runner), but it's not the "TestResult" class. In any case, I never observed a compilation failure caused by this. Maybe it's some Android-specific problem - I can't help here as I don't do Android development.

**Comment by rliesenfeld** [comment]
My bad, JMockit 1.8 *did* contain the "junit.framework.TestResult" class; it was removed in a later version.
