### ISSUE TITLE
Optional expectations no longer possible after removal of NonStrictExpectations

### ISSUE THREAD

**Issue by wigbam** [jmockit/jmockit1#335]
Suppose I have a mock with a(), b() and c() methods each returning some value. My class under test can *potentially* call any of those. Or any combination of those. Or none. The nature of calls and order of those is really down to implementation details and I don't want to replicate its logic in my test (and I really shouldn't). All I know is that invocations of a(), b() and c() or any combination of those are valid interactions and should return some values.

Used to be easily done with NonStrictExpectations, but now that is's gone there is no way to model this behavior. Expectations simply ignores minTimes as per stacktrace, while StrictExpectations enforces the order on invocations. So am I missing something or there is indeed no way of setting up such a scenario?

It has to be stated that a MockUp could be used, of course, with defined a(), b() and c(). But then I won't be able to specify other expectations on my mock using the Expectations syntax nor verify interactions using Verifications(), which is extremely useful.

Is there a solution? Especially unfortunate is that both jMock (via allowing) and Mockito (via VerificationMode) support this functionality.

**Comment by wigbam** [comment]
After further digging it seems that on version 1.25 it is still possible to set-up optional expectations by using Expectations along with minTimes=0. Version 1.26 no longer works, but looks as by design though?

**Comment by rliesenfeld** [comment]
"My class under test can potentially call any of those. Or any combination of those. "
Absolutely! But why should that be a problem?

"So am I missing something ..."
Yes, I think you are. Specifically, you are missing that a given test is not going to exercise *any* combination of calls to a(), b(), c(), but a *single* and *known* combination of such calls. Otherwise, what you have is simply not a valid test.

It would be better if an *actual* example use case was shown, so we could discuss the topic on more concrete terms. But even without that, my perception is the problem here is one of understanding what a test is supposed to be. To me, a proper, well-written unit/integration test aims to exercise a *single* and well-defined "business scenario", which executes a single set of paths through the methods under test. So, in this test, you *know* whether a(), or b(), or c() are *expected* to be called or not.

**Comment by rliesenfeld** [comment]
Even Mockito's owner already realizes that expectations with "minTimes = 0" by default is not such a great idea: https://github.com/mockito/mockito/issues/303

**Comment by wigbam** [comment]
Sure, I came up with a really trivial example. Let there be a class which represents a price with some extra attributes:

    class Price {
        double getBid();
        double getAsk();
        long getTimesTamp();
        String getSource;
    }

Suppose the class under test receives an instance of the above and does some checks on the price to determine if it is valid. For example:

    private boolean isPriceValid(Price p) {
        return !Double.isNaN(p.getBid()) && !Double.isNaN(p.getAsk());
    }

Now, as per above if `getBid()` returns NaN then `getAsk()` is never going to be called, but this is an implementaion-specific detail and the validation method might have been implemented in a reveresed order:

    private boolean isPriceValid(Price p) {
        return !Double.isNaN(p.getAsk()) && !Double.isNaN(p.getBid());
    }

or even:

    private boolean isPriceValid(Price p) {
        final Double bid = p.getBid();
        final Double ask = p.getAsk();
        return !Double.isNaN(bid ) && !Double.isNaN(ask);
    }

Now, requiring a programmer to know how exactly the method carries out the price validation internally so that to prepare Expectations which would suit the *internal* implementation details is rejecting the idea of black-box-testing as a concept. As a user of this class I don't really care how the validation is carried out and in which order methods are called. All I care that if either bid or ask or both are NaN then the validation should fail.

**Comment by rliesenfeld** [comment]
Here is a full test class proving that the tests can be written without any "minTimes", and that they are implementation-independent:

```
import mockit.*;
import org.junit.*;
import static org.junit.Assert.*;

public final class TempTest {
    static class Price {
        double getBid() { return 1.0; }
        double getAsk() { return 2.0; }
        long getTimesTamp() { return 5L; }
        String getSource() { return "WTV"; }
    }

    static class CUT {
        public boolean doSomething(Price p) {
            return isPriceValid(p);
        }

        private boolean isPriceValid(Price p) { // uncomment one or another version
            // Version 1:
            return !Double.isNaN(p.getBid()) && !Double.isNaN(p.getAsk());

            // Version 2:
            //return !Double.isNaN(p.getAsk()) && !Double.isNaN(p.getBid());

            // Version 3:
            //final Double bid = p.getBid();
            //final Double ask = p.getAsk();
            //return !Double.isNaN(bid ) && !Double.isNaN(ask);
        }        
    }

    @Tested CUT cut;

    @Test
    public void doSomethingWithValidPrice() {
        Price validPrice = new Price();
        
        boolean b = cut.doSomething(validPrice);

        assertTrue(b);
    }

    @Test // bad test as it mocks a "value object"
    public void doSomethingWithPriceHavingAnInvalidBid(@Injectable final Price priceWithInvalidBid) {
        // Don't do this in a real test; instead, initialize a suitable Price object.
        new Expectations() {{ priceWithInvalidBid.getBid(); result = Double.NaN; }};
        
        boolean b = cut.doSomething(priceWithInvalidBid);
        
        assertFalse(b);
    }

    @Test // bad test as it mocks a "value object"
    public void doSomethingWithPriceHavingAnInvalidAsk(@Injectable final Price priceWithInvalidAsk) {
        // Don't do this in a real test; instead, initialize a suitable Price object.
        new Expectations() {{ priceWithInvalidAsk.getAsk(); result = Double.NaN; }};

        boolean b = cut.doSomething(priceWithInvalidAsk);
        
        assertFalse(b);
    }
    
    // The tests above work with ANY of the three "isPriceValid" versions. 
}
```

**Comment by wigbam** [comment]
Thanks for the quick response. Yes, the approach in your example will work and it is essentially equivalent to using a MockUp as I mentioned in the initial post. But it has a few major disadvantages as compared to using a mock, the main one being not being able to assert on any interactions which class under test is performing on the provided value object =\

My final thoughts on this are that it is better to provide more functionality than restrict functionality by design. I mean jMockit already allows to do so much cool nasty stuff (like mocking static or private methods), that the argument of limiting some functionality because of a conceptual approach concerns seems quite strange.

**Comment by rliesenfeld** [comment]
Not sure what you mean by "not being able to assert on any interactions which class under test is performing on the provided value object"... A "Verifications" block, perhaps? But that would not be the case, as the verification block would be allowed.

The change regarding "minTimes" was an enhancement that leads to better tests. There is no question in my mind about it. I never seen a legitimate use of NonStrictExpectations or "minTimes = 0" in a test method, and I chalenge anyone to show such a test (including one written with EasyMock or whatever). I cannot prove a negative, but I can be proved wrong by being shown a single test.

**Comment by wigbam** [comment]
Suppose the `Price` had another method, let's say, for the sake of the example, `addValidationResult(String)`. This method would be called by our class under test if price was valid or invalid:

    void checkPrice(Price p) {
        if(!isPriceValid(p)) {
            p.addValidationResult("Price is bad");
        } else {
            p.addValidationResult("Price is good");
        }
    }

Obviously, not the best example, but I hope the problem is clear: how would you assert that `addValidationResult` was called? `Price` is a POJO so Verifications would not work in this case.

**Comment by rliesenfeld** [comment]
In that case, you could add a
`new Verifications() {{ price.addValidationResult("Price is bad"); }};` block (or similar, as needed).

JMockit doesn't know whether something is a POJO or not, and verifications can always be added except for expectations which have been recorded in the same test.

**Comment by wigbam** [comment]
I am not sure I understand you on verification part. How can you verify an invocation on something that is not a mock?

```
import mockit.*;
import org.junit.*;
import static org.junit.Assert.*;

public class JMockitTest {

    interface Price {
        double getBid();
        double getAsk();
        void addValidationResult(String str);
    }

    static class CUT {
        public boolean doSomething(Price p) {
            if (isPriceValid(p)) {
                p.addValidationResult("good");
                return true;
            } else {
                p.addValidationResult("bad");
                return false;
            }
        }

        private boolean isPriceValid(Price p) { // uncomment one or another version
            return !Double.isNaN(p.getBid()) && !Double.isNaN(p.getAsk());
        }
    }

    @Tested CUT cut;

    @Test
    public void doSomethingWithValidPrice() {
        class TestPrice implements Price {
            public double getBid() { return 1.0; }
            public double getAsk() { return 2.0; }
            public void addValidationResult(String str) {};
        }
        final Price validPrice = new TestPrice();
        assertTrue(cut.doSomething(validPrice));
        new Verifications() {{
            validPrice.addValidationResult("this verification is ignored");
        }};
    }
}
```

The above test passes fine since validPrice is a POJO and jMockit is not aware of it in Verifications block.

But OK, suppose even, if we could verify invocations on our class somehow. This approach dictates that for every test a separate concrete Price class would need to be created suiting a particular test case. It might OK for trivial classes with several methods, but what if I want to throw in something more complex with a dozen methods. Do I start creating test classes purely for testing? If I have many tests, I probably would want to start making them reusable, adding some conditional logic etc. Almost if as I was.. mocking their behavior! :)

Once again, returning to my original point, I think mocking the data object here was absolutely fine and I really really don't understand the reason why the below code, which worked perfectly in 1.25, suddenly became politically incorrect in 1.26 onwards:

```
    @Test
    public void testGoodOld_1_25_Days(@Injectable final Price p) {
        new Expectations() {{
            p.getBid(); result = Double.NaN; minTimes = 0; maxTimes = -1;
            p.getAsk(); result = 1d; minTimes = 0; maxTimes = -1;
        }};
        assertFalse(cut.doSomething(p));
        new Verifications() {{
            p.addValidationResult("bad");
        }};
    }
```

**Comment by rliesenfeld** [comment]
In your previous comment, it does not say that "Price" was not being mocked anymore. I assumed it was.

But ok, let's say Price isn't mocked (and indeed it shouldn't be mocked). The answer then is that you do *state* verification, not *behavior* verification. So, the test would look as follows:

```
public class JMockitTest {
    interface Price { // weird this being an interface, but ok...
        double getBid();
        double getAsk();
        void addValidationResult(String str);
        String getValidationResult(); // added, as it would probably have a means of checking the result
    }

    static class CUT { // unchanged
        public boolean doSomething(Price p) {
            if (isPriceValid(p)) {
                p.addValidationResult("good");
                return true;
            } else {
                p.addValidationResult("bad");
                return false;
            }
        }

        private boolean isPriceValid(Price p) {
            return !Double.isNaN(p.getBid()) && !Double.isNaN(p.getAsk());
        }
    }

    @Tested CUT cut;

    @Test
    public void doSomethingWithValidPrice() {
        class TestPrice implements Price {
            private String validationResult;
            public double getBid() { return 1.0; }
            public double getAsk() { return 2.0; }
            public void addValidationResult(String str) { validationResult = str; }
            public String getValidationResult() { return validationResult; }
        }
        Price validPrice = new TestPrice();

        boolean result = cut.doSomething(validPrice);

        assertTrue(result);
        assertEquals("good", validPrice.getValidationResult());
    }
}
```

In your original example, "Price" was a class, and it very much looked like a "value object" with its state stored in instance fields which can be set through parameters passed in a constructor, or through setter methods. If you search around (try googling for "mocking value objects"), you'll see that there's general agreement that mocking such classes is to be avoided. It's not something new.

**Comment by wigbam** [comment]
A few questions/notes:

1. Why `Price` shouldn't be mocked?
As in philosophically and conceptually, what is the reason not to mock something that your class under test is using? I thought this is exactly the case where mocking should be used.

2. What if I don't have control over the interfaces, i.e. they are provided by a third-party?
I can't add/remove methods. I guess I can extend the provided interface and create a test-only version, but that is bad for obvious reasons. Also on third-party interface change I have potentially go and revisit all my test cases to add/remove/update signatures and methods.

This in turn leads to..

3. What if the interface has a decent amount of methods, for example, 10+?
But only 2 are expected to me interacted with for a particular test scenario? My test method becomes cluttered and hard to read with all those empty declarations. Again, I could introduce a dummy abstract implementing test class which would return some default values, but isn't that what jMockit already can do? Feels wrong re-inventing the wheel.

4. What if I need to verify more than one interaction, interaction sequence etc.?
Again, in your example, there is a sense of re-inventing the wheel, i.e. capturing an argument and storing it locally for test verification purpose. But this is what jMockit already can do, and do much better, isn't it? For trivial cases like above it might seem acceptable, but it will become apparent that this approach is quick;y getting out of control for more complex test cases.

The prevailing feeling I have, is that both new and old approaches are imperfect, but at least the old approach gave developers more flexibility and much clearer written test cases.

**Comment by rliesenfeld** [comment]
`Price` shouldn't be mocked if it is a "value object". Note even Mockito's project [says](https://github.com/mockito/mockito/wiki/How-to-write-good-tests) "don't mock value objects". Plenty more authors say this. Also, it's often said to "not mock everything". Personally, I believe the less you mock in a test, the better.

Anyway, you can mock `Price` or just about anything else if you really want. This issue was opened in relation to "minTimes = 0" not being allowed in test methods anymore. It woud be better if the discussion here was kept focused on that. Specifically, I would like to see an example test where the need for an "optional expectation" is demonstrated.

**Comment by wigbam** [comment]
As per previous posts, I guess it was demonstrated there is no absolute 'need' for that. Yes, there is a way to get around it. But the 'get around it' code and constructs are less readable, more clunky and definitely less flexible than the old mock way. Speaking of which your last example does not utilize any jMockit functionality at all.

**Comment by wigbam** [comment]
And, yes, I could have probably created a real-life good example which would utilizing some common chunky interface containing some redundant methods. For example, http://docs.oracle.com/javaee/6/api/javax/jms/Message.html with its `getPropertyNames` and `propertyExists` springs to mind, but I have to get rest too sometimes :) So I rest my case with this one for now.

**Comment by rliesenfeld** [comment]
In the case of the JMS Message interface, it's not a value object and could very well be mocked.

In my view, having optional recorded expectations for this interface would imply a bad test, where the behavior to be tested is being obscured through unclear, undefined "inputs". (From the [xUnit Test Patterns](http://xunitpatterns.com) book, mocks are a way to provide for *indirect* inputs and/or outputs in a unit test.)

So, our disagreement here is in the way we understand what a test is supposed to be. To me, a (good) unit test verifies a single, clearly understood behavior (or scenario) that a given "unit under test" provides. There is no room for "optional" expectations in such a test. Having such an expectation implies the developer writing/reading the test does not fully understand what the test is supposed to be testing. At least, that's my understanding. Maybe it's incorrect, but before I can change my mind I would need to see either a logical counter-argument or a valid counter-example.
