### ISSUE TITLE
false-positive java.lang.IllegalArgumentException: Attempted to record expectation on unmockable method

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#340]
Having the attached example project [test.zip](https://github.com/jmockit/jmockit1/files/487220/test.zip)  (unzip and run `gradlew test -i`), you get an error `Attempted to record expectation on unmockable method`.

The `String` `@Injectable` is necessary to satisfy the `Logger` constructor argument. But as far as I understand the `Injectable` JavaDoc, no other instances of `String` should be affected in any way. Yet this error occurs while actually no expectation for this method is recorded, its return value is just used as argument matcher.

**Workaround:** Do the `getBytes()` call before the `Expectations` block

**Comment by rliesenfeld** [comment]
String is not being mocked at all. It is correct to use it with @Injectable, though, provided the string value is given. The following test passes:

    @Tested(fullyInitialized = true) Foo sut;
    @Injectable String nameForLogger = "foo";

    @Test
    public void test() {
        assertEquals("foo", sut.logger.getName());
    }

Alternatively, the value can be provided by writing `@Injectable("foo") String nameForLogger`, which can also be done in a test method parameter.

**Comment by Vampire** [comment]
If you look at the provided MVCE together with my description, you will see that I do not even try to record an expectation on a String. I just use an unmocked String instance in an expectation as parameter for or as return value for some other expectation.

**Comment by Vampire** [comment]
I guess this has to do with #344. If in the provided test-case I change `@Injectable` to `@Injectable("")` (which is the default value anyway), it still fails with the same error. If I change it to `@Injectable("f")` it suddenly works fine. `@Injectable String nameForLogger = "f";` again fails with the error, `@Injectable final String nameForLogger = "f";` works fine.

**Comment by rliesenfeld** [comment]
There is indeed a bug here, that I just noted after some experimentation. The real issue is that an "@Injectable String" *field* seems to be getting partially mocked, when it should not be mocked at all. With a test method *parameter*, there is no problem. So, it's probably a bug specific to mock fields.
