### ISSUE TITLE
No way to fullyInitialize a SUT if naming is unfortunate

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#342]
Having the following SUT

```
public class Foo {
    String foo;
    @Inject
    Bar bar;

    static class Bar {
        public Bar(String foo) {
        }
    }
}
```

I see no way to create this `fullyInitialized`. With the test class

```
public class FooTest {
    @Tested(fullyInitialized = true)
    Foo sut;

    @Injectable("foo")
    String foo;

    @Injectable("bar")
    String bar;

    @Test
    public void test() {
    }
}
```

It doesn't matter how I name or order the injectables, I'll always get the error `java.lang.IllegalArgumentException: No injectable value available for parameter "foo" in constructor Foo$Bar#Bar(String foo)`, just with varying parameters, in the example `foo`.

If one injectable is named `foo`, no matter where it is in the order, the field `foo` consumes it and the constuctor also depends on the name-matched injectable which is already consumed.

If no injectable is named `foo`, both - the field injection and the constructor injection - only try to use the first field which is already consumed by the field and the constructor looses with said error message.

If no name-match is found, I guess the fix for #341 will kick in and the next field tried.

But if a name-match is found, the fix for #341 will not help here either. So maybe if a name-matched injectable is found that is already consumed, the mechanism could fall back to trying available injectables maybe?

**Comment by rliesenfeld** [comment]
It can be done, actually:

    public class Foo {
        String foo;
        @Inject Bar bar;

        static class Bar {
            final String foo;
            Bar(String foo) { this.foo = foo; }
        }
    }

    public class FooTest {
        @Tested Foo.Bar bar = new Bar("bar");
        @Tested(fullyInitialized = true) Foo sut;
        @Injectable String foo = "foo";

        @Test
        public void test() {
            assertEquals("foo", sut.foo);
            assertSame(bar, sut.bar);
            assertEquals("bar", sut.bar.foo);
        }
    }

**Comment by Vampire** [comment]
Ah, ok, right.
In my real case it was a bit more complex, as I also needed a `MockUp<Bar>` and with that solution it would say `Bar` is already mocked, wouldn't it`?

**Comment by rliesenfeld** [comment]
`Bar` isn't mocked in my example test, nothing is actually.

If there are two (or more) injectables of the same type, I don't see how to only use their common type for injection point matching. The rule is to use type+name matching in such cases. The only alternative possibility would be to rely on the textual order the injectables appear, but this woud be very confusing and unreliable.

**Comment by Vampire** [comment]
Isn't that how constructor parameter injection points are searched also? Besides that only the first value is taken into consideration.

**Comment by rliesenfeld** [comment]
"@Injectable String bar" is considered, but no matching (by type *and* name) injection point is found: the String parameter in Bar is named "foo", and the "foo" injectable was already used.

**Comment by Vampire** [comment]
I mean the first example of #341 where you said this indeed is a bug. How does the constructor find injection point candidates if no name-match is found?
