### ISSUE TITLE
"GenericArrayTypeImpl cannot be cast to Class" when MockUp<GENERIC_AS_SUPER>

### ISSUE THREAD

**Issue by YangZhong** [jmockit/jmockit1#347]
Please provide the following information:

* Version of JMockit that was used: 
1.28 1.27 1.26 1.25
Java "1.8.0_102"

* Description of the problem or enhancement request:
"java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.GenericArrayTypeImpl cannot be cast to java.lang.Class" when `MockUp<GENERIC_AS_SUPER>`.
That's a regression because 1.24 works perfectly.

public class GENERIC_AS_SUPER extends `SUPER<GENERIC>`
{...}
public class TEST extends Assert
{

> 

    @BeforeClass  //  jUnit 4.12
    static public void SET_UP() throws Exception
    {
        new MockUp<GENERIC_AS_SUPER>()
        {
            @Mock
            void $init()
            {}
            ...
        };
    }
    ...
}

**Comment by rliesenfeld** [comment]
I cannot reproduce the problem. How are the "SUPER" and "GENERIC" types defined?

**Comment by YangZhong** [comment]
Thanks to Rogério for trying to reproduce. A "SUPER<GENERIC>" example is "HashMap<Object,Collection<Object>[][]>". In order to simplify regression reproducing & any fix verification, here's a simplified Test Case and could you remove "could not reproduce" tag please:

```
public class Regression {
  @Test  //  jUnit 4.12
  public void works1_24() {
    new MockUp<HashMap<Object,Collection<Object>[][]>>(){};
  }
}
```

**Comment by rliesenfeld** [comment]
Thanks.

Note there is no need to use the full generic type declaration in the `new MockUp<T>()` call.
Writing `new MockUp<HashMap<?, ?>>()` works (that said, `HashMap` should never be mocked/faked).

**Comment by YangZhong** [comment]
Thank *you* Rogério actually.

Just want to clarify some potential misunderstanding. We do *not* use the full generic type declaration in the `new MockUp<T>()` call. We do `MockUp<GENERIC_AS_SUPER>` as mentioned above. GENERIC_AS_SUPER is our own class we have to mock in only some of our Test Cases.

Also as commented above, above Test Case is purposely simplified for regression reproducing & any fix verification. While ourselves do *not* have any Test Case mocking/faking HashMap (yet), we don't choose the sides of HashMap ever needs mocking/faking vs. should never.
