### ISSUE TITLE
Constructor Injection not working with v1.28

### ISSUE THREAD

**Issue by henryken** [jmockit/jmockit1#348]
Please provide the following information:

* Version of JMockit that was used: 1.28

* Description of the problem or enhancement request:
The below test works in 1.27 but not in 1.28.
It returns the following exception message:

> java.lang.IllegalStateException: Invalid single replacement of a mocked instance for class java.util.Date

`public class SystemClockTest {  

    @Mocked
    private Date date;

    @Test
    public void testNow() {
        new Expectations() {{
            new Date();
            result = date;
        }};

        Date now = new SystemClock().now();

        assertThat(now).isEqualTo(date);
    }

}`

**Comment by rliesenfeld** [comment]
With 1.27 (and replacing the "isEqualTo" with "assertEquals", as I don't know where that comes from), I get the following test failure:

`java.lang.AssertionError: expected: java.util.Date<java.util.Date@50fcf2c1> but was: java.util.Date<java.util.Date@50fcf2c1>
`

Anyway, that expectation recording (`new Date(); result = date;`) is indeed invalid.
This [section in the Tutorial](http://jmockit.org/tutorial/Mocking.html#futureInstancesByConstructor) is relevant.

**Comment by henryken** [comment]
"isEqualTo" is AssertJ API. I'm not sure why the "assertEquals" doesn't return true while it seems that the object reference is the same from your error message.

I still don't get, how can we mock "new Date()" that is being called inside SystemClock?
From what I understand from the tutorial, I don't see anything different.
Can you advice me, as this has been working since so many previous versions before?

**Comment by rliesenfeld** [comment]
Ah, yes, that error message is misleading - I didn't notice it at first. The `java.util.Date` class has a custom `toString()` method, which gets mocked. So, `now` and `date` are actually two different instances, although the string returned from `toString()` is the same. A better assertion is `assertSame(date, now)`, which also fails.
