### ISSUE TITLE
Web page does not invite gradle use

### ISSUE THREAD

**Issue by paulirotta** [jmockit/jmockit1#351]
The http://jmockit.org/ main page does not invite Android and other gradle users with the following example line:

    testCompile 'org.jmockit:jmockit:1.28'

This would be easier to offer as a pull request if it were editable with github pages. Perhaps I missed something.

And- big thanks, the library works great and relieves the considerable tedium of the alternatives!

**Comment by rliesenfeld** [comment]
Ok, added to the main page now.
