### ISSUE TITLE
JMockit-1.28 and Robolectric 3.0 intergation issue

### ISSUE THREAD

**Issue by moulinwang** [jmockit/jmockit1#356]
When I use Robolectic 3.0 together with JMockit 1.28, I found use static block in RobolectricTestRunner subclass did not resolve the intergration issue.

```
import mockit.internal.startup.Startup;

public class MyTestRunner extends RobolectricTestRunner {
   static { Startup.initializeIfPossible(); }
    public MyTestRunner(Class testClass) throws InitializationError {
        super(testClass);
    }
}
```

I got the error message as below:

> java.lang.IllegalStateException: Invalid place to record expectations

the test code is as below:
```
@RunWith(MyTestRunner.class)
@Config(manifest = "./src/main/AndroidManifest.xml")
public class HttpRequestTest {

    @Mocked
    HttpUriRequest request;

    @Test
    public void test2() throws IOException {
        new Expectations() {  //this line throws the exception
            {
                request.getAllHeaders();  
                result = new Header[]{};
            }
        };
        request.getAllHeaders();
    }
}
```

When I debuged into JMockit source, I found JMockit use @Mocked class by app class loader while Robolectric use the InstrumentingClassLoader, which is a thread context class loader, so JMockit can not found the  "@Mocked HttpUriRequest request " field. (TestRun.getFieldTypeRedefinitions() = null)

When I add JMockit initial method in @Before,  this issue disappeared.
```
@RunWith(MyTestRunner.class)
@Config(manifest = "./src/main/AndroidManifest.xml")
public class HttpRequestTest {

    @Mocked
    HttpUriRequest request;

    @Before
    public void setUp() {
        Startup.initializeIfPossible();
    }
    @Test
    public void test2() throws IOException {
        new Expectations() {  //this line throws the exception
            {
                request.getAllHeaders();  
                result = new Header[]{};
            }
        };
        request.getAllHeaders();
    }
}   
```

**Comment by rliesenfeld** [comment]
Yes, it's known that JMockit and Robolectric don't work together.

I don't do Android development, but even so in the past some attempts were made to allow for JMockit usage under the Robolectric custom classloader. It worked in some simple cases, but not in others, so the little support that existed was removed.

If you want to submit PRs that add Robolectric support, I am willing to evaluate them for inclusion in some future release.

**Comment by zcmgyu** [comment]
Could you support JMockit for Android testing? I think Android Testing's also important
