### ISSUE TITLE
How to mock static final method of class?

### ISSUE THREAD

**Issue by abhiSYSOUT** [jmockit/jmockit1#357]
* Version of JMockit that was used:  1.21

* Description of the problem or enhancement request: There is a class which has static final method.
I am trying to mock those method like this:

class ClassA{
      public static final void getInfo(Object inputOne, Object inputTwo) {
          
       }
}

new MockUp<ClassA>() {
       @Mock
       public void getInfo(Object inputOne, Object inputTwo) {
          
       }
};

During test execution, mocked getInfo method is not getting invoked.

**Comment by rliesenfeld** [comment]
You can find documentation about mock-ups in the [API documentation](http://jmockit.org/api1x/mockit/MockUp.html), as well as in the [Tutorial](http://jmockit.org/tutorial/Faking.html).

**Comment by abhiSYSOUT** [comment]
@rliesenfeld Can you provide specific example of mentioned scenario?

**Comment by rliesenfeld** [comment]
There isn't a specific example for this scenario in the documentation, but the [relevant section in the Tutorial](http://jmockit.org/tutorial/Faking.html#mockableMethods) should be clear enough.
