### ISSUE TITLE
Allow mocking of javax.persistence classes

### ISSUE THREAD

**Issue by shollander** [jmockit/jmockit1#360]
Please provide the following information:

* Version of JMockit that was used: 
1.29

* Description of the problem or enhancement request:

I recently tried upgrading to jmockit version 1.29 and some of my units tests started blowing up with the following error:
```
java.lang.IllegalArgumentException: Invalid mocking of @Entity-annotated class ...
```
Looking through the jmockit source code it appears that a check was put in with commit 8314ac3b82bfd5c63e8684d499e0d62322855d2f to prevent mocking of `@Entity` classes. Would you please remove that check? Why is this restriction needed? I should be able to mock any class.

**Comment by rliesenfeld** [comment]
The restriction was added because all evidence points to the mocking of entity classes being a bad practice leading to bad tests. In order for the decision to be reconsidered, *evidence* (not opinions) that mocking/faking of entity classes is useful in good tests would need to be shown.
