### ISSUE TITLE
How to call method of interface field

### ISSUE THREAD

**Issue by zcmgyu** [jmockit/jmockit1#362]
* Version of JMockit that was used: 1.21
* Description of the problem:

I have interface like this.
**TestInterface:**
```
public interface TestInterface {
    boolean callMethod();
}
```

A TestClass have field is a instance of that interface
**TestClass:**
```
public class TestClass {
    private final TestInterface inner = new TestInterface() {
        @Override
        public boolean callMethod() {
            subMethod();
            return false;
        }
    };
        public void subMethod() { System.out.println("Sub method");
    };
}
```

This test case manages to verify call method subMethod from that field/
**TestInterfaceTest:**
```
public class TestInterfaceTest {
    @Mocked TestClass sut;
    @Test
    public void mockAllClassesImplementingAnInterface(@Mocked final TestInterface testInterface) {
        Deencapsulation.setField(sut, "inner", testInterface);
        // what we expect to be invoked
        new NonStrictExpectations() {
            {
                Deencapsulation.invoke(sut, "subMethod");
            }
        };
        // Actual invoke
        Deencapsulation.invoke(Deencapsulation.getField(sut, "inner"), "callMethod");
       // verify that we did invoke the expected method of collaborator
        new Verifications() {
            {
                Deencapsulation.invoke(sut, "subMethod"); times = 1;
            }
        };
   }
}
```

**This is result:**

> mockit.internal.MissingInvocation: Missing 1 invocation to:
> helloandroid.examples.helloandroid.TestClass#subMethod()
> on mock instance: helloandroid.examples.helloandroid.TestClass@e50a6f6

I think that issue here is that _Deencapsulation.invoke(Deencapsulation.getField(sut, "inner"), "callMethod")_ call to this method _TestInterface#callMethod()_. So, can't verify that i did invoke to subMethod() method

---------
Could you give me some ideas to resolve this problem. Thanks you.

**Comment by rliesenfeld** [comment]
You can find information and example tests for cases like this in the JMockit Tutorial .

**Comment by zcmgyu** [comment]
Thanks for response from you @rliesenfeld.
I'm sorry to bother you, could I ask you something more.
I also tried your suggestion but I've received another exception like below:

**Test method**

```
@Test
    public void mockAllClassesImplementingAnInterface() {
                  
        TestInterface testInterface = new MockTestInterface<TestInterface>() {
            @Mock
            public boolean callMethod(Invocation inv) {
                inv.proceed(); // throw exception here -> Will my expected method  be called here?
                return true;
            }
        }.getMockInstance();

        Deencapsulation.setField(sut2, "INTER2", testInterface);

        new NonStrictExpectations() {
            {
                Deencapsulation.invoke(sut2, "subMethod");
            }
        };

        Boolean result = Deencapsulation.invoke(Deencapsulation.getField(sut2, "INTER2"), "callMethod");

        assertTrue(result);

        new Verifications() {
            {
                Deencapsulation.invoke(sut2, "subMethod"); times = 1;
            }
        };
    }

```

> java.lang.IllegalArgumentException: No class with name "ndroid.examples.helloandroid.$Impl_TestInterface" found

Thanks a lot
