### ISSUE TITLE
How to generate a coverage report that include all production codes?

### ISSUE THREAD

**Issue by catkeeper1** [jmockit/jmockit1#363]
Please provide the following information:

* Version of JMockit that was used: 
JMockit 1.29
JMockit-Coverage 1.23

* Description of the problem or enhancement request:
We want to supply UT for some existing production codes. Now, I found the JMockit Coverage only generate coverage report for the classes that have been loaded during test. I want to have a report to show how many programs are still not covered by any UT. Is it possible to do this? Now, my walk-around approach is I build a UT test case to load all the production class when Maven run test.

**Comment by rliesenfeld** [comment]
All classes are already included in the coverage report, by default. It gets restricted to only loaded classes if and only if "coverage-classes=loaded".

Also, see http://jmockit.org/changes.html#1.24
