### ISSUE TITLE
Can't verify method of class under test if it was mocked by expectations

### ISSUE THREAD

**Issue by zcmgyu** [jmockit/jmockit1#367]
* Version of JMockit that was used: 1.29

I mentioned about this bug in the ticket below. 
https://github.com/jmockit/jmockit1/issues/366
However, at that time I could not reproduce the bug with simple example.
But now, could you define this issue. When i debug, it seems like could not jump into actual method (reason cause I've mocked class under test?)

**Class under test:**

```
public class Foo {
    public Foo() {
    }

    public void methodTest(String arg) {
        if (arg == null) {
            arg = "Updated";
        }
        subMethod(arg);
    }
    private void subMethod(String arg2) {
        System.out.println("Call subMethod" + arg2);
    }
    
} 
```

**Test case**

```
public class FooTest {
    Foo sut;
    @Before
    public void setUp() {
        sut = Deencapsulation.newInstance(Foo.class);
    }
    @Test
    public void methodTest() throws Exception {
        // Record
        new Expectations(Foo.class) {
            {
                sut.methodTest(null);
            }
        };

        // Actual invocation
        sut.methodTest(null);
        // Verify
        new Verifications() {
            {
                String params;
                sut.methodTest(params = withCapture());
                assertThat(params, is("Updated"));
            }
        };
    }
}
```

This condition seems like didn't run:
```
if (arg == null) {
     arg = "Updated";
}
```

Result:

> java.lang.AssertionError: 
> Expected: is "Updated"
>      but: was null
> Expected :is "Updated"
>      
> Actual   :null

**Comment by rliesenfeld** [comment]
The test makes no sense, since it mocks the same method it's trying to test.
