### ISSUE TITLE
Support measuring code coverage for integration tests and manual tests

### ISSUE THREAD

**Issue by gengcheng** [jmockit/jmockit1#368]
Please provide the following information:

* Version of JMockit that was used: 
1.29

* Description of the problem or enhancement request:
Currently, I can use jmockit to measure code coverage for unit tests with junit,  I also wish the jmockit can support the integration tests and measuring code coverage when running the application under test environment, so that we can know how many methods/codes are tested by the engineer, thank you.

**Comment by rliesenfeld** [comment]
It's already provided by ["Standalone mode"](http://jmockit.org/tutorial/CodeCoverage.html#standalone).
