### ISSUE TITLE
Partial Mocking of Thread.sleep

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#370]
Please provide the following information:

* Version of JMockit that was used: 

 1.29

* Description of the problem or enhancement request:
I want to mock only Thread.sleep within one test case

I did the following
@Test
	public void testThreadSleepPartialMock() throws InterruptedException
	{
		new Expectations(Thread.class)
		{
			{
				Thread.sleep(anyLong);
			}
		};
		
		Thread.sleep(5000);
	}
But it still delays for 5 seconds. Am I missing something on how partial mocking works?

**Comment by brucetrask** [comment]
I forgot to mention that I am using  the partial mocking in combination with other @Mocked params so cannot use the MockUp (as far as I understand)

**Comment by brucetrask** [comment]
Such as 
@Test
	public void testThreadSleepPartialMock(@Mocked AnotherClass ac) throws InterruptedException
	{
		new Expectations(Thread.class)
		{
			{
				Thread.sleep(anyLong);
			}
		};
		
		Thread.sleep(5000);
	}

**Comment by rliesenfeld** [comment]
Partial mocking (using the `Expectations(Object...)` constructor) does not apply to `native` methods such as `Thread.sleep`. (This limitation is mentioned in the constructor's API documentation.)
