### ISSUE TITLE
non-jmockit, duplicate classes inside the jmockit jar

### ISSUE THREAD

**Issue by wilem82** [jmockit/jmockit1#374]
Please provide the following information:

* Version of JMockit that was used: 
1.29

* Description of the problem or enhancement request:

[WARNING] Found duplicate and different classes in [com.sun:tools:1.8, org.jmockit:jmockit:1.29]:
[WARNING]   com.sun.tools.attach.AgentInitializationException
[WARNING]   com.sun.tools.attach.AgentLoadException
[WARNING]   com.sun.tools.attach.AttachNotSupportedException
[WARNING]   com.sun.tools.attach.AttachPermission
[WARNING]   com.sun.tools.attach.VirtualMachine
[WARNING]   com.sun.tools.attach.VirtualMachineDescriptor
[WARNING]   com.sun.tools.attach.spi.AttachProvider
[WARNING]   sun.tools.attach.HotSpotVirtualMachine
[WARNING]   sun.tools.attach.WindowsVirtualMachine

[WARNING] Found duplicate and different classes in [junit:junit:4.12, org.jmockit:jmockit:1.29]:
[WARNING]   org.junit.runner.Runner

We don't allow duplicates on the classpath as it paves the road to unpredictable bugs. Is there a workaround to this, perhaps a non-bundled jar version?

**Comment by novaterata** [comment]
@wilem82 How would an implementer of an interface like org.junit.runner.Runner as in jmockit, JUnitParams, etc. implement that interface without including it?

**Comment by rliesenfeld** [comment]
You can always remove the classes from your copy of jmockit.jar.

**Comment by wilem82** [comment]
True, but creating a patched artifact for JMockit makes updates real painful. Would you consider separating the bundled JMockit jar into core and the tools/junit classes as a separate dependency (something like `org.jmockit:jmockit` that depends on `org.jmockit:jmockit-deps`)? That way it could easily be excluded in Maven. That would benefit everyone, as bundling classes like that creates conflicts for different versions of JUnit and tools.jar.
