### ISSUE TITLE
Mocked file.getAbsolutePath()  NullPointerException

### ISSUE THREAD

**Issue by novaterata** [jmockit/jmockit1#376]
Please provide the following information:

* Version of JMockit that was used: 

1.30

* Description of the problem:
Sorry this isn't fleshed out, but imagine you have an interface Bar that has a getFile method that is used to report an error with the file path in the error message. Basically, when file.getAbsolutePath() is called, the Expectation is completely ignored, so that the actual isAbsolutePath() code is run so that tons of stuff are null.  I suspect this is more of these filtered out java.* classes which I simply don't understand.

```java
    @Test
    public void shouldFoo(@Mocked Bar bar, @Mocked File file, @Mocked Path path) {
        String pathStr = "/some/test";

        new MockUp<Paths>(Paths.class) {
            @Mock
            Path get(String first, String... more) {
                return path;
            }
        };

        new MockUp<Files>(Files.class) {
            @Mock
            boolean exists(Path path, LinkOption... options) {
                return false;
            }
        };

        new Expectations() {{
            bar.getFile();
            result = file;
            file.getAbsolutePath();
            result = pathStr;
        }};

        assertThat(bar.getMessage(), is(equalTo("baz" + pathStr)));
    }
```

**Comment by novaterata** [comment]
I was able to workaround this using a MockUp<File>(File.class)

**Comment by novaterata** [comment]
I think I understand what is going on. So if the object is a java.* object then we are supposed to use MockUp<Foo> instead of an Expectation step.

**Comment by rliesenfeld** [comment]
To avoid the problem, simply don't mock File or Path.

**Comment by novaterata** [comment]
How is that an answer? Why should I not be able to mock such a common
dependency as a File? Where are all your fatwas documented?

On Fri, Dec 23, 2016, 4:53 PM Rogério Liesenfeld <notifications@github.com>
wrote:

To avoid the problem, simply don't mock File or Path.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jmockit/jmockit1/issues/376#issuecomment-269049649>,
or mute
the thread

**Comment by rliesenfeld** [comment]
Mocking of "File#getAbsolutePath()" restored.

**Comment by novaterata** [comment]
Thanks, I will encourage my devs to avoid injecting File and Path directly so stuff like this won't be such a blocker, but it's hard for a n00b to convince old-timers to do anything
