### ISSUE TITLE
mockups system property does not appear to work

### ISSUE THREAD

**Issue by ryansgot** [jmockit/jmockit1#378]
Please provide the following information:

* Version of JMockit that was used: 
1.26

* Description of the problem:
Adding -Dmockups=com.my.MockupClass1,com.my.MockupClass2 to the test JVM did not cause a call to the no-arg constructor of my mockup class. From the documentation on Global mock-ups, it appears this should have called their no-arg constructors at some point.

I should add that I'm using gradle, and the build.gradle code was as follows:
```groovy
tasks.withType(Test).all { t ->
    t.systemProperties['mockups'] = 'com.my.MockupClass1,com.my.MockupClass2'
    println t.name + " jvmArgs = " + t.allJvmArgs
}
```

**Comment by rliesenfeld** [comment]
Does it work from the IDE (for example, if running a test suite from Eclipse or IntelliJ with the "-Dmockups=..." parameter)?

**Comment by ryansgot** [comment]
I apologize for missing this comment. I verified that the -Dmockups=com.my.MockupClass1,com.my.MockupClass2 argument was getting sent on the call to java runtime via the command line. The IDE behavior doesn't help because it must run on the continuous integration build.

However, we have decided to move away from using JMockit.
