### ISSUE TITLE
@Injectable doesn't work for @Tested without initialisation

### ISSUE THREAD

**Issue by avaysberg** [jmockit/jmockit1#380]
Please provide the following information:
since v.1.28 @Injectable and @Mocked doesn't work for Enum

* Version of JMockit that was used: 
v.1.28 - v.1.30

* Description of the problem:
since v.1.28 @Injectable and @Mocked doesn't work for Enum and I received this exception:
`
FAILED: testGetEtumType
java.lang.IllegalArgumentException: No injectable value available for parameter "enumType" in constructor testng.enumeration.JMockitUsedEnum#JMockitUsedEnum(testng.enumeration.EnumType enumType, String test)

FAILED: testGetTest
java.lang.IllegalArgumentException: No injectable value available for parameter "enumType" in constructor testng.enumeration.JMockitUsedEnum#JMockitUsedEnum(testng.enumeration.EnumType enumType, String test)
`
I prepare the Test for this:
`
public class TestJMockitUsedEnum {
    @Injectable
    private String test;
    @Injectable
    private EnumType enumType;
    @Tested
    private JMockitUsedEnum jMockitUsedEnum;

    /**
     * Test method for {@link testng.enumeration.JMockitUsedEnum#getEnumType()}.
     */
    @Test
    public void testGetEtumType() throws Exception {
        Assert.assertNotNull(jMockitUsedEnum.getEnumType());
    }

    /**
     * Test method for {@link testng.enumeration.JMockitUsedEnum#getTest()}.
     */
    @Test
    public void testGetTest(@Mocked EnumType enumType) throws Exception {
        JMockitUsedEnum jMockitUsedEnum = new JMockitUsedEnum(enumType, "test");

    }

}`

and one Enum:
`public enum EnumType {
    TYPE_ONE,
    TYPE_TWO;
}
`
and one class, that used Enum:
`
 public class JMockitUsedEnum {
    private final EnumType enumType;
    private final String test;

    public JMockitUsedEnum(EnumType enumType, String test) {
        super();
        this.enumType = enumType;
        this.test = test;
    }

    public EnumType getEnumType() {
        return enumType;
    }

    public String getTest() {
        return test;
    }
}
`
The solution exists only for @Injectable in Test with initialisation, like this: 
` 
   @Injectable
    private String test = "test";
    @Injectable
    private EnumType enumType = EnumType.TYPE_ONE ;`

**Comment by rliesenfeld** [comment]
See the API documentation for `@Injectable`:

> When the type of the injectable is String, a primitive wrapper, a number type, or an enum, it is not mocked. A non-empty value must then be provided, except in the first case where the empty string is used by default.

**Comment by avaysberg** [comment]
ok, since v1.28 the behaviour is changed. Will be good its to write in release note :)

**Comment by avaysberg** [comment]
since version 1.28 the behaviour is totally changed. Everything what works, now don't work. It's very difficult found out the solution :(

**Comment by avaysberg** [comment]
the sample
...` new StrictExpectations() {
            {
                 client.call();
                 result = responseMock();
            }
}`
that get error,
but this work:
...`   Response response = reponse();
        new StrictExpectations() {
            {
                 client.call();
                 result = response;
            }
}`
Why?
