### ISSUE TITLE
Coverage tool: line coverage reported as ">99%" in white

### ISSUE THREAD

**Issue by printingin3d** [jmockit/jmockit1#386]
Please provide the following information:

* Version of JMockit that was used: 
1.23, 1.30

* Description of the problem:
I built my project JavaSCAD (https://github.com/printingin3d/javascad) and there were two classes where the line coverage reported as ">99%" in white. I inspected it a bit and interestingly the line coverage states "Line segments: 17/15", which means there were 17 lines covered out of the 15 possible.

I have a quick and dirty, but working solution for this problem: changing the output to 100% in green when the number of covered lines is more then the number of total lines. The perfect solution would be to find the root cause of the miscalculated line numbers, but I don't understand the code enough to do that. Yet.

I couldn't find any information about how to contribute to the project. If someone can share this information I'm happy to fix this issue (and probably more, because I use the coverage tool a lot and found several issues with it - this is just my first touch of it in the process to understand the codebase)

**Comment by rliesenfeld** [comment]
Might be related to issue #134.

The [API documentation summary page](http://jmockit.org/api1x/overview-summary.html) talks about contributions at the end. Beyond that, see [GitHub's guide](https://guides.github.com/activities/contributing-to-open-source).
