### ISSUE TITLE
Coverage for Abstract Base class methods with bodies

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#394]
Please provide the following information:

* Version of JMockit that was used: 

1.29

* Description of the problem:

I am not seeing coverage information generated for Abstract Base classes that have some functions with implementations. That is no coverage generated for non abstract member function within an Abstact Base class.

* Please avoid reporting a problem that cannot be reproduced by project members.
  Instead, include enough information (typically, an example test or more, perhaps accompanied by a
  Maven/Ant/Gradle build script) so that other developers can verify the problem in their own environments.
  Otherwise, there is a good chance the issue will be immediately closed with the "could not reproduce" tag.

**Comment by rliesenfeld** [comment]
I tested this scenario (a test calling a method implemented in an abstract class), and said method does show as covered in the report.
