### ISSUE TITLE
Deencapsulation.setField throws IllegalAccessException for static final field

### ISSUE THREAD

**Issue by JChrist** [jmockit/jmockit1#398]
Please provide the following information:

* Version of JMockit that was used: 
1.30 (but any version 1.25+ does this, 1.24 and below work)
* Description of the problem:

Having a class:
```
public class Foo {
    private static final int PSFI = 5;
}
```
and a test similar to:
```
public class FooTest {
    @Test
    public void decapsulate() {
        Deencapsulation.setField(Foo.class, "PSFI", 10);
    }
}
```
It will fail with an exception:

> java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set static final int field Foo.PSFI to java.lang.Integer

**Comment by rliesenfeld** [comment]
See #281
