### ISSUE TITLE
Possible to mock a static method in an interface

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#401]
* Version of JMockit that was used: 
1.29
* Description of the problem:

I am looking at an interface that has a static method with a body. Something like this contrived example. 

public interface TestJMockitWithStatic {

	public static int getInt(String str)
	{
		return 1;
	}
}
Is it possible to mock this? I tried using a MockuUp as follows:

public class MockTestJMockitWithStatic extends MockUp<TestJMockitWithStatic>{

	@Mock
	int getInt(String str)
	{
		return 0;
	}
}

but at runtime I get 

java.lang.IllegalArgumentException: Matching real methods not found for the following mocks:
.test.MockTestJMockitWithStatic#getInt(String)

Thanks,
Bruce

* Please avoid reporting a problem that cannot be reproduced by project members.
  Instead, include enough information (typically, an example test or more, perhaps accompanied by a
  Maven/Ant/Gradle build script) so that other developers can verify the problem in their own environments.
  Otherwise, there is a good chance the issue will be immediately closed with the "could not reproduce" tag.

**Comment by jbotuck** [comment]
http://jmockit.org/tutorial/Faking.html#mockableMethods

_Methods to be faked need to have an implementation, though not necessarily in bytecode (in the case of native methods). Therefore, an abstract method cannot be faked directly, and the same applies to the methods of a Java interface. (That said, as shown later the Mockups API can automatically create a proxy class that implements an interface.)_

**Comment by brucetrask** [comment]
@jbotuck . Thanks but the static function in my interface has an implementation (see my example code above) and therefore should be able to be mocked, correct?

**Comment by rliesenfeld** [comment]
It can be mocked just like any class or interface, by using `@Mocked`.
