### ISSUE TITLE
JDK9 Internal API references

### ISSUE THREAD

**Issue by sdfelts** [jmockit/jmockit1#402]
When running 1.25 and 1.30 (see output below) with Jigsaw b162 with --permit-illegal-access, the following warnings are displayed.  I'm not sure if there is code there to handle the failure and re-try an alternative approach.

WARNING: Illegal access by mockit.internal.state.MockFixture (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.25/a5df18d2bfb13e3ba20fdccb2351ac5554c7b178/jmockit-1.25.jar) to method java.lang.Object.registerNatives() 
WARNING: Illegal access by mockit.internal.state.MockFixture (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.25/a5df18d2bfb13e3ba20fdccb2351ac5554c7b178/jmockit-1.25.jar) to method java.lang.Thread.registerNatives() 

WARNING: Illegal access by mockit.internal.state.MockFixture (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.30/3945abb0591b9775736ee208f6f73331d63d7ff9/jmockit-1.30.jar) to method java.lang.System.registerNatives() 
WARNING: Illegal access by mockit.internal.state.MockFixture (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.30/3945abb0591b9775736ee208f6f73331d63d7ff9/jmockit-1.30.jar) to method java.lang.Thread.registerNatives() 
WARNING: Illegal access by mockit.internal.util.Utilities (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.30/3945abb0591b9775736ee208f6f73331d63d7ff9/jmockit-1.30.jar) to field java.io.ObjectInputStream.bin 
WARNING: Illegal access by mockit.internal.util.Utilities (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.30/3945abb0591b9775736ee208f6f73331d63d7ff9/jmockit-1.30.jar) to field java.io.ObjectInputStream$BlockDataInputStream.end 
WARNING: Illegal access by mockit.internal.util.Utilities (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.30/3945abb0591b9775736ee208f6f73331d63d7ff9/jmockit-1.30.jar) to field java.io.ObjectInputStream.defaultDataEnd 
WARNING: Illegal access by mockit.internal.util.Utilities (file:gradle_cache/caches/modules-2/files-2.1/org.jmockit/jmockit/1.30/3945abb0591b9775736ee208f6f73331d63d7ff9/jmockit-1.30.jar) to method java.lang.ClassLoader.getPackages()

**Comment by rliesenfeld** [comment]
I ran my tests on JDK 9 build 163 (the latest as of Apr 1), with "--permit-illegal-access", but all I got was the "WARNING: --permit-illegal-access will be removed in the next major release" message.

Anyway, if and when those calls to Java internal API become an actual problem on JDK 9, it will be addressed.

**Comment by sdfelts** [comment]
jmockit1-master/main/src/mockit/internal/state/MockFixture.java calls setAccessible without catching RuntimeException (JDK9 actually throws InaccessibleObjectException but since that's a new exception in JDK9, you might want to just catch RuntimeException and ignore it).
