### ISSUE TITLE
Jmockit migration result on slower test

### ISSUE THREAD

**Issue by javiertoja** [jmockit/jmockit1#406]
Hi, 

I'm facing a strange behaviour after migrating Jmockit.
I'm migrating a large application with several modules, in small steps and after upgrade jmockit from version 0.999.15 to 1.21 the testing phase require a lot of time to execute. Before the migration we where able to run over 1000 integration test on 3-10 minutes each module, now they require over 20 minutes each one, so our building times where increased to hours (from less than 1 hour to 8+).

i cannot provided a reproducible project with the situation but on this link i post  more information [http://stackoverflow.com/questions/43179070/jmockit-migration-result-on-slower-test](http://stackoverflow.com/questions/43179070/jmockit-migration-result-on-slower-test)

 - The project use junit 4.10  in a spring web based application running the test with spring runner.
 - The context is loaded on the first test, non before each test. 
 - The context has over 700 beans spreed in 36 modules.
 - The main issue comes when testing the top module which is deployed when running the integration tests
 - The test use mocks declared with @Mocked and some new MocKup<> that didn't change on the migration.
 - Some test use over 30 mocked objects since other use only 1 or 2.
 - The project use api's that didn't change over the versions so the code of the test didn't change either.

My doubt is about someone faced this issue before or have some idea about where i can look to have more information and tackle this problem.

Thanks.

**Comment by rliesenfeld** [comment]
JMockit's own test suite (about 1400 tests) is also used for performance evaluation, and it has not shown any significant slowdown in successive versions. So, without a reproducible example test suite which shows such an slowdown, I am afraid there is nothing we can do.

**Comment by knut-forkalsrud** [comment]
Related issue: 390

**Comment by javiertoja** [comment]
Ok, Thanks for your reply, i will try to create a reproducible example. But would you mind to tell me which is the better way of use jmockit in terms of speed of execution of the test, i mean it's better to use new Mockup<> than @Mocked annotation or extend the Expectations class.

**Comment by javiertoja** [comment]
@knut-forkalsrud thanks for relate the issue 390. After review the issue i can confirm that we have the same problem, we use mainly @Mocked annotation, and i think as on issue 390 is the root of our performance problems.

In order to tackle the situation we are going to migrate our "@mocked" mocks into "new MockUps" and check the performance.

Thanks for your help

**Comment by johan-roets** [comment]
Hi Javier,

Please do share your results, looking forward to see your findings. I would
still like the jmockit team to consider / reply to the performance
considerations ito the caching I set forth in issue 390.

Kind regards
Johan
