### ISSUE TITLE
Exception when using Proxy Classes

### ISSUE THREAD

**Issue by graben** [jmockit/jmockit1#407]
Versions since 1.25 including latest 1.31 does throwing an Exception when using Proxy Classes. There is a line of code commented under "https://github.com/jmockit/jmockit1/commit/754d3326d840a74a3e0b29606f5c8e2993a211c2" that is causing this behavior. It's not reasonable to me why this has been introduced.

**Comment by rliesenfeld** [comment]
?! What do you mean "using Proxy Classes"? Which exception is thrown? An example test would help...

**Comment by graben** [comment]
Well, I'm using Weld (CDI) which is using Proxies at runtime. Those classes are not found by ClassFile throwing intgernal NotFoundException. I'm still not sure why this method (https://github.com/jmockit/jmockit1/commit/754d3326d840a74a3e0b29606f5c8e2993a211c2) is called. No return value, no inner state?

**Comment by graben** [comment]
Example test:
[test.zip](https://github.com/jmockit/jmockit1/files/908040/test.zip)

**Comment by rliesenfeld** [comment]
Thanks. Weld generates a synthetic subclass for each test class using `CdiRunner`, and JMockit attempts to read it to extract method parameter names. Naturally, in the case of synthetic subclass, JMockit should instead take the superclass, which is the actual test class.
