### ISSUE TITLE
Parallel Tests using JMockit [FEATURE REQUEST]

### ISSUE THREAD

**Issue by ddwolf** [jmockit/jmockit1#408]
can you provide a parallel jmockit? I found that   mockup annotation not work when testing in parallel   ways

**Comment by rliesenfeld** [comment]
I can't, sorry.

**Comment by harigopalpatelTR** [comment]
Parallel execution does not work with JMock 1.49 + JUnit 5, you have fixed this issue?

**Comment by rliesenfeld** [comment]
I run a JUnit 5 test suite of about 2000 tests, nearly all using JMockit, daily and in parallel without issues.
They are executed in multiple processes through Maven Surefire, with the following configuration parameters:

                    <forkCount>6</forkCount>
                    <reuseForks>true</reuseForks>

As reported in the project's Jenkins pipeline, the total (sequential) time is about 24-26 minutes, while real time with 6 processes is about 2 mins 40-50s.

As for parallel execution with multiple threads in a *single* process, I don't think it will ever be supported. Too problematic. And the use of Surefire (or the Gradle equivalent) already solves the actual problem very well.
