### ISSUE TITLE
$ symbol removed

### ISSUE THREAD

**Issue by vijayiiit137** [jmockit/jmockit1#409]
Please provide the following information:

* Version of JMockit that was used: 1.30

* Description of the problem:what is the alternate solution to the removal of $ symbol

**Comment by rliesenfeld** [comment]
That feature was deemed not useful, and probably almost never got used, so it was dropped. There is no alternative.

**Comment by vijayiiit137** [comment]
In our project  it occured so many times.so,how t resolve this problem?what is the impact if we remove that symbol.does it make any effect to project?
