### ISSUE TITLE
JMockit with JUnit 5.0.0-M4 interface mock - NullPointerException thrown

### ISSUE THREAD

**Issue by jvujcic** [jmockit/jmockit1#412]
Please provide the following information:

* Version of JMockit that was used: 
1.31

* Description of the problem:
Using JMockit 1.31 with JUnit 5.0.0-M4 and trying to mock an interface NullPointerException is thrown. Sample code that throws exception:

```java
public interface MyInterface {
    public int method(int x);
}

public class MyClass {
    private MyInterface myInterface;

    public MyClass(MyInterface myInterface) {
        this.myInterface = myInterface;
    }

    public int method() {
        return myInterface.method(5);
    }
}

@RunWith(JUnitPlatform.class)
public class MyClassTest {

    @Capturing
    private MyInterface myInterface;

    @Test
    void testing() {
        new Expectations() {{
            myInterface.method(anyInt); result = 1;
        }};

        MyClass myClass = new MyClass(myInterface);
        assertEquals(1, myClass.method());
    }
}
```

Exception is thrown on line `myInterface.method(anyInt); result = 1;`. I tried with M1, M2, and M3 and it works with all three as expected.

**Comment by marcphilipp** [comment]
BTW Instead of registering a "fake" `TestEngine`, starting with JUnit 5 M4, JMockIt can register its extension using ServiceLoader (cf. http://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic) directly. No more need to use "black magic".

**Comment by rliesenfeld** [comment]
Support for M4 is done for JMockit 1.32.

@marcphilipp No, that only works if tests are executed with "-Djunit.extensions.autodetection.enabled=true", which is something that cannot be expected from users.

**Comment by MichalMichalak** [comment]
Issue has been closed but problem is still there, it seems.

```java
public class AppTest {
    @Mocked
    Calc c;

    @Test
    public void t() {
        new Expectations() {{
            c.add(anyInt, anyInt); // <== NULL POINTER EXCEPTION HERE
            result = 999;

        }};

        App a = new App(c);
        int result = a.calculate();
        Assertions.assertEquals(7, result);
    }
}
```
