### ISSUE TITLE
@Capturing interface type of base causes real superclass constructor to be called with nulls

### ISSUE THREAD

**Issue by westonlast** [jmockit/jmockit1#417]
JMockit 1.31

```java
import mockit.Capturing;
import org.junit.Test;

public class JMockitTest{
    @Test
    public void test(@Capturing Interface type){
        new Base("1", "2");
    }
}

interface Interface{}

class Base extends Super implements Interface{
    Base(String one, String two){    //constructor never called, as expected
        super(one, two);
    }
}

class Super{
    Super(String one, String two){    //constructor unexpectedly called with null parameters
        System.out.println(one + " " + two);    //"null null"
    }
}
```

**Comment by rliesenfeld** [comment]
It's consistent with the API documentation: "... classes extending/implementing the mocked type will also get mocked". `Super` doesn't implement `Interface`, so it doesn't get mocked.

If the test instead uses `Super` as the capturing type, then the test works as expected.

**Comment by westonlast** [comment]
No, the API documentation is inconsistent with common sense.  Base implements Interface, and Base is-a Super.  If a library exposes Interface which happens to be a class with a type hierarchy, how is Interface supposed to be mocked when the instance is constructed inside the library?
