### ISSUE TITLE
times field doesn't seem to work with StrictExpectations

### ISSUE THREAD

**Issue by Karl-Sa** [jmockit/jmockit1#423]
Hi, I have this sample test that passes successfully (JMockit 1.32) when I thought it would only pass with `times = 1`:

    @Test public void dummyTest(@Mocked final String s) {
        String s1 = "s1";
        String s2 = "s2";
        
        new StrictExpectations() {{
            s1.compareTo(s2);
            times = 10;
        }};
        
        s1.compareTo(s2);
    }

Note that this is just an example, it just aims to illustrate a behavior that I find strange.
Maybe I'm setting up the test in the wrong way?

**Comment by rliesenfeld** [comment]
It works just fine when mocking a "regular" class:

    public class TempTest {
        static class ARegularClass implements Comparable<ARegularClass> {
           @Override public int compareTo(ARegularClass o) { return 0; }
        }

        @Test
        public void dummyTest(@Mocked ARegularClass s) {
            ARegularClass s1 = new ARegularClass();
            ARegularClass s2 = new ARegularClass();

            new StrictExpectations() {{ s1.compareTo(s2); times = 10; }};

            s1.compareTo(s2);
        }
    }

`String` should never be mocked, unless you really know what you're doing...
