### ISSUE TITLE
Java 9 compatibility 

### ISSUE THREAD

**Issue by rarathore** [jmockit/jmockit1#424]
Hi Team
	As you know Java9 release date is coming near (End of July 2017), So Please let me know whether you have any plan to incorporate Java 9 related changes in your libs, if yes pls share the version details.
Thanks a lot
Rajendra Rathore

**Comment by rliesenfeld** [comment]
JMockit already is compatible with JDK 9.

**Comment by rarathore** [comment]
can you please share the version details of JMockit. 
Thanks
Rajendra Rathore
