### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by per-neiderud** [jmockit/jmockit1#425]
Hi,

This is a follow-up of #270, and I'm just re-posting my comments there to make sure that it gets into the pipeline. My apologies if this means I'm causing a duplicate.

Using version 1.31, with Java 8u45 on Jenkins, I run into the same problem as in #270.
From time to time, I get an java.util.ConcurrentModificationException.
Unfortunately, I also haven't been able to create a useful test case that reproduces the problem each time it runs.

However, I have spotted the problem in the code :)

It seems that in MockFixture, an item can in some cases be removed from an iterator while iterating over the elements of that same iterator. This is very likely what causes the ConcurrentModificationException.

The problem is in this method, the 3rd line from the bottom,
"itr.remove();"

Could you please have a look?

Thanks,
Per

void restoreRedefinedClasses(@Nonnull Map<?, byte[]> previousDefinitions) {
    if(!this.redefinedClasses.isEmpty()) {
        RedefinitionEngine redefinitionEngine = new RedefinitionEngine();
        Iterator itr = this.redefinedClasses.entrySet().iterator();

        while(itr.hasNext()) {
            Entry<Class<?>, byte[]> entry = (Entry)itr.next();
            Class<?> redefinedClass = (Class)entry.getKey();
            byte[] currentDefinition = (byte[])entry.getValue();
            byte[] previousDefinition = (byte[])previousDefinitions.get(redefinedClass);
            if(currentDefinition != previousDefinition) {
                redefinitionEngine.restoreDefinition(redefinedClass, previousDefinition);
                if(previousDefinition == null) {
                    this.restoreDefinition(redefinedClass);
                    this.discardStateForCorrespondingMockClassIfAny(redefinedClass);
                    itr.remove();
                } else {
                    entry.setValue(previousDefinition);
                }
            }
        }
    }
}

**Comment by rliesenfeld** [comment]
Ok, it seems `MockFixture#addRedefinedClass(...)` is getting called concurrently, in some unknown situation.
Will make the map a concurrent map then.

**Comment by per-neiderud** [comment]
Great, thanks a lot!

/ Per
