### ISSUE TITLE
@Autowired must come with @Injectable with @tested(fullyInitialized = true) ?

### ISSUE THREAD

**Issue by chao-luo** [jmockit/jmockit1#430]
Jmockit Version: 1.33
Here is the relative [issue](https://github.com/jmockit/jmockit1/issues/285) 

And I add the `@Tested(fullyInitialized = true).` to the tested class, but I got another exception

java.lang.IllegalStateException: Missing @Tested instance of an implementation class for field "xxx'' in xxx

**Comment by chao-luo** [comment]
https://groups.google.com/forum/#!topic/jmockit-users/wMFZggsA8LM

Someone meet the same issue

**Comment by chao-luo** [comment]
A lot of the fields that in the tested class maybe no used in a test method, but I need to add all of them, That's quite strange and does not make sense.

**Comment by greenman0007** [comment]
Hi, @rliesenfeld Could you please tell me why this is invalid ? As the exception is telling about missing implement class, but you have removed the searching for implement class for interface in this [commit](https://github.com/jmockit/jmockit1/commit/d7c04d7509a5a07ee3e5735675309508dd07ccbb 

), thanks.

**Comment by xiaoyuxu1010** [comment]
111
