### ISSUE TITLE
@Tested in test subclass not initialized

### ISSUE THREAD

**Issue by maximmold** [jmockit/jmockit1#431]
* Version of JMockit that was used: 
1.33

* Description of the problem:
When I have a class that extends an abstract class and tests for both where each has an @Tested annotation, the @Tested of the subclass test does not get initialized if the superclass test runs first.

For example, here is the superclass:
```
public abstract class AbstractFoo {
    private FooService fooService;

    public boolean isSomething() {
        return fooService.isSomething();
    }
}
```
Here is its test which always passes:
```
public class FooTest {
    @Tested
    AbstractFoo foo;

    @Injectable
    FooService fooService;
    
    @Test
    public void isSomething () throws Exception{
        foo.isSomething();
    }
    
}
```

Here is the subclass
```
public class Bar extends AbstractFoo{
    private BarService barService;

    public boolean isSomethingElse() {
        return barService.isSomethingElse();
    }
}
```

Here is the subclass test
```
public class BarTest extends FooTest{
    @Tested
    Bar bar;

    @Injectable
    BarService barService;
    
    @Test
    public void isSomethingElse() throws Exception {
        barService.isSomethingElse();
    }

}
```

I get a NPE on the call to the barService when running TestSuite which places FooTest first in the order, but it works fine when I run TestSuite2 to which places BarTest first in the order. In my fork, I changed TestRunnerDecorator.handleSwitchToNewTestClassIfApplicable to do a `else if (!currentTestClass.equals(testClass)) {` instead of a `else if (!currentTestClass.isAssignableFrom(testClass)) {`. That seems to fix the problem, but probably slows things down a bit.

Test project available here:
[testedinheritance.zip](https://github.com/jmockit/jmockit1/files/1152994/testedinheritance.zip)

**Comment by rliesenfeld** [comment]
Simply don't do something like `class BarTest extends FooTest`. A test class can extend a reusable base test class (without any test methods of its own), but it's not supposed to extend another test class.

**Comment by maximmold** [comment]
Is this actually documented anywhere? It seems like if this is working as designed it should be documented and it also should have some kind of better runtime warning to explain as such. I feel like there are valid use cases for this kind of test where you want to ensure all methods overridden by  subclasses exhibit certain behavior. For instance, an overridden builder method always returns the instance passed in.
