### ISSUE TITLE
Add functionality to wait for asynchronous events

### ISSUE THREAD

**Issue by kwave** [jmockit/jmockit1#434]
The function I missed the most when switching from Mockito to JMockit was Mockito's `timeout()`. 

Example:
I am testing a class that fires an asynchronous callback after X seconds. Currently I have to implement a custom "wait for callback" function on my own. e.g. 

```
public void testCase(@Mocked MyCallback callbackMock){
   new MockUp<MyCallback> (){
            @mockit.Mock
            public synchronized  void onEventFired() {
                this.notify();
            }
   };
  testling.doSomethingAsynchronous(callbackMock);
  synchronized (callbackMock){
            callbackMock.wait(5000);
  }
   new Verifications(){{

            callbackMock.onEventFired();

        }};
}
```

Things get even more complicated if your add one or more "on-event" methods to your callback interface. Thats the point where you start to define a countdown-latch for each single one of your methods, and manually check whether they have been called. e.g.
```
public void testCase(@Mocked MyCallback callbackMock){
   new MockUp<MyCallback> (){
            @mockit.Mock
            public synchronized  void onEventFired() {
               //trigger latch 1
            }

            @mockit.Mock
            public synchronized  void onEventFired2() {
               //trigger latch 2
            }
   };
  testling.doSomethingAsynchronous(callbackMock);
  //Wait for both latches to trigger
   new Verifications(){{
            callbackMock.onEventFired();
            callbackMock.onEventFired2();
        }};
}
```
So why not add something like
```
 new Verifications(){{
            callbackMock.onEventFired();
            timeout(5000);
            callbackMock.onEventFired2();
             timeout(5000);
}};
```
To JMockit?

**Comment by rliesenfeld** [comment]
I don't know; a feature like this can be added, but it might encourage too much mocking, and/or bad design in the multithread/async code.

It's generally best to provide a way for client code to block (with a timeout) until the background task is completed/canceled. For example, by returning a `Future` object.

Real-world examples are hard to find, so it would help a lot if a realistic example could be shown.

**Comment by kwave** [comment]
One of my classes which can't be tested without this functionality. It uses a Wiremock Stub for mocking the web server.

```
public interface StatusCallback {
    void onDownloadStarted();
    void onDownloadProgress(int percent);
    void onDownloadFinished(File downloadedFile);
    void onDownloadFailed();
}

public class Downloader {     
     public void download(URL url,StatusCallback){
         //Download implementation
     }
}
```
The ugly test case (due the lack of a timeout function) looks like this:
```
public void testSucessfulDownload(@Mocked StatusCallback callbackMock){
   CountDownLatch startedSignal = new CountDownLatch(1);
   CountDownLatch progressSignal = new CountDownLatch(100);
   CountDownLatch finishedSignal = new CountDownLatch(1);
   new MockUp< StatusCallback > (){
            @mockit.Mock
            public void onDownloadStarted() {
               startedSignal.countDown();
            }

            @mockit.Mock
            public void onDownloadProgress(int progress) {
               progressSignal.countDown();
            }

             @mockit.Mock
            public void onDownloadFinished() {
               finishedSignal.countDown();
            }
   };
  testling.download(mockedWebserverUrl,callbackMock);
  startedSignal.await(5000,TimeUnit.MILLISECONDS);
  progressSignal.await(5000,TimeUnit.MILLISECONDS);
  finishedSignal.await(5000,TimeUnit.MILLISECONDS);
 
   new Verifications(){{
            callbackMock.onDownloadStarted();
            callbackMock.onDownloadProgress(any);
            times=100;
            callbackMock.onDownloadFinished();
        }};
}
```
With timeout functionality it could look as simple like this:
```
public void testSucessfulDownload(@Mocked StatusCallback callbackMock){
  testling.download(mockedWebserverUrl,callbackMock);
   new Verifications(){{
            callbackMock.onDownloadStarted();
            timeout=5000;
            callbackMock.onDownloadProgress(any);
            timeout=5000;
            times=100;
            callbackMock.onDownloadFinished();
            timeout=5000;
        }};
}
```

**Comment by rliesenfeld** [comment]
Thanks. But how is the `download` method implemented? I assume it creates a background task to perform the actual download? And how is the `Downloader` class used in client code? Is it a desktop (Swing/JavaFX) app or a web app? What task/concurrent API is used by `download` (threads, java.util.concurrent, something else)?

If `Downloader` provides a method like `void waitForCompletion(int timeout)`, then the test would simply call it before verifying the expected calls on the mock callback.

**Comment by kwave** [comment]
In my opinion, it doesn't really matter how the download method is implemented, because this is just an example use case.
Assume you got *any* asynchronous task that fires *only* callbacks, and has no option to wait synchronous for completition.

Changing your existing implementation just to be able to test it in a synchronous test scenario is never a good choice, because you are not actually testing the real-life scenario. Therefore any implementation needs to be testet as it is - as blackbox - without changing it just for test purposes.

Mockito provides methods to do so for asynchronous things, JMockit currently does not.
