### ISSUE TITLE
Mocked class with method that returns a Throwable subclass throws "not mockable" error

### ISSUE THREAD

**Issue by ogray58** [jmockit/jmockit1#437]
**Version**
JMockit: 1.33 (Note: I also tried building from the current head of the JMockit master branch and it also failed there)
JUnit: 4.11
Java: 1.8.0_66

**Description**
I'm guessing that it tries to return a cascaded mock, and since Throwable can't be mocked it throws an error. Note that this doesn't occur if TestClass.getMyThrowable() returns a Throwable instead of a MyThrowable.

**Code to Reproduce**
ExampleTest.java:
```
@Mocked private TestClass mockedTestClass = null;

@Test
public void test()
{
	mockedTestClass.getMyThrowable();
}

public static class TestClass
{
	public MyThrowable getMyThrowable()
	{
		return new MyThrowable();
	}
}

public static class MyThrowable extends Throwable {}
```

**Comment by Milbor** [comment]
Is
```
    @Injectable
    private IOException exception;

```
java.lang.IllegalArgumentException: Class java.lang.Throwable is not mockable

same bug or should I open new issue?

**Comment by rliesenfeld** [comment]
@Milbor  It's a feature, unless someone can show a legitimate need to mock an exception class, especially a standard one.

**Comment by Milbor** [comment]
No not just standard one, all of them. Even custom ones where their methods might be more complex than just simple getters. Why do you call it a feature if it's crippling jMockit functionality?
Where is it mentioned in release notes?
