### ISSUE TITLE
Collections not Mockable

### ISSUE THREAD

**Issue by DemonicTutor** [jmockit/jmockit1#451]
From jmockit 1.32 to 1.33 there has been a validation added that Java's collections should not be mocked.

This affects one of my Unit-Tests regarding java.util.Properties wich extend java.util.Hashtable<Object,Object>

I want to mock Properties because code is calling its Properites#load(Reader) function.
A shortened snipped of the code follows.

jmockit: 1.33
jdk 1.8

error message:
java.lang.IllegalArgumentException: Class java.util.Hashtable is not mockable

Code:
class PropertyProducer {

  PropertyProducer() {
    try {
      final Reader reader = Resources.asCharSource(Resources.getResource("test.properties"), Charsets.UTF_8).openStream();
      final Properties properties = new Properties();
      properties.load(reader);

      }  catch (final IOException e) {
          throw ShouldNeverHappenException.valueOf(e);
    }
  }
}

  @Test
  public void should_Rethrow_Load() throws IOException {
    new Expectations(Properties.class) {
      @Capturing
      Properties properties = new Properties();
      {
				this.properties.load((Reader) this.any);
				this.result = new IOException("FOOBAR");
      }
    };

    Assertions.assertThrows(ShouldNeverHappenException.class, () -> new PropertyProducer() );
  }

expected behaviour:
Mocks / Captures java.util.Properties
records .load(Reader) call
throws IOException("FOOBAR") on call from SUT

works with jmockit:1.32

best regards and thousand thanks for such an amazing library
Markus Spika

**Comment by rliesenfeld** [comment]
Instead of mocking `Properties`, the test could rename the local "test.properties" file to something else, so the test gets an `IOException` in a more realistic way.
