### ISSUE TITLE
Typo in tutorial example - Faking

### ISSUE THREAD

**Issue by epastoor** [jmockit/jmockit1#453]
On the tutorial page: [http://jmockit.org/tutorial/Faking.html#mockableMethods](url), there is a sample code block that appears to have a stray right parenthesis.

```
@Test
public void applyingAnAnonymousMockup() throws Exception
{
   new MockUp<LoginContext>() {
      @Mock void $init(String name) { /* do nothing */ }
      @Mock void login() {}
   });

   new LoginContext("test").login();
}
```

I believe there should not be a right parenthesis on the line after the login method before the semicolon

**Comment by rliesenfeld** [comment]
Fixed, thanks.
