### ISSUE TITLE
Using delegate with partial mock does not seem to work

### ISSUE THREAD

**Issue by ekalabs** [jmockit/jmockit1#455]
Please provide the following information:

* Version of JMockit that was used: 

1.20

* Description of the problem:

In below example, I except assert to succeed as them delegate method reset bean value to 2. However, I seems like delegate method is not being called and assertion fails. Am I doing something wrong.

    @Test
    public void testSample() throws Exception {

        class TestBean {
            private int val;
            public int getValue() {
                return val;
            }
            public void setValue(int val) {
                this.val = val;
            }
        };

        class TestBeanServer {
            public void refresh(TestBean bean) {
                System.out.println("-------------------->Actual refresh method is called");
            }
        };

        class Modifier {
            TestBeanServer server;
            public Modifier(TestBeanServer server){
                this.server = server;
            }
          public void methodToTest(TestBean bean) {
              privateMethodToTest(bean);
          }
          private void privateMethodToTest(TestBean bean) {
              server.refresh(bean);
          }
        };

        final TestBeanServer mockServerBean = new TestBeanServer();
        Modifier modifier = new Modifier(mockServerBean);

        new mockit.Expectations(mockServerBean) {{
            mockServerBean.refresh(withInstanceOf(TestBean.class));
            new mockit.Delegate() {
                void refresh(TestBean bean) {
                    bean.setValue(2);
                    System.out.println("-------------------->Mock refresh method is called");
                }
            };
        }};

        TestBean bean = new TestBean();
        bean.setValue(3);

        modifier.methodToTest(bean);

        assertEquals(bean.getValue(), 2);
 }

**Comment by rliesenfeld** [comment]
`Delegate` usage is described in the [Tutorial](http://jmockit.org/tutorial/Mocking.html#delegates), and also in the [API documentation](http://jmockit.org/api1x/mockit/Delegate.html). They both mention the detail that is missing in the test.

However, I see no reason for this test to use a delegate, or a partial mock, in the first place. Instead, the test could verify that `mockServerBean.refresh(bean)` was called on an `@Injectable mockServerBean`.
