### ISSUE TITLE
Verifications on MockUp object are not working

### ISSUE THREAD

**Issue by szymonprz** [jmockit/jmockit1#456]
Please provide the following information:

* Version of JMockit that was used: 1.34

* Description of the problem:
When i'm trying to do some verifications on mocked object created with MockUp i'm receiving exception (IndexOutOfBoundsException in this case). 

Test to reproduce: 

`    private class SimpleClass{
        private int value;

        public int getValue() {
            return value;
        }

        public void setValue(int value) {
            this.value = value;
        }
    }

    private final class MockSimpleClass extends MockUp<SimpleClass>
    {
        @Mock
        public int getValue() {
            return 1;
        }
    }

    @Test
    public void applyingAMockClass() throws Exception {
        MockSimpleClass mockSimpleClass = new MockSimpleClass();

        Integer value = new SimpleClass().getValue();

        new Verifications(){{
            mockSimpleClass.getValue();
            this.times = 1;
        }};
    }`

Maybe I'm using it in a wrong way?

**Comment by rliesenfeld** [comment]
"Maybe I'm using it in a wrong way?" Yes; see [this page](http://jmockit.org/gettingStarted.html) for documentation and example tests.

**Comment by szymonprz** [comment]
But was is wrong? Isn't it possible to use mockup object in verification? In previous version of jmockit we were using @Mocked with value attribute to mock some methods on the object used in logic, then we were cheking execution times in verification section. So how to do it now?
