### ISSUE TITLE
Cannot mock Exceptions/ Throwable with @Mocked annotation

### ISSUE THREAD

**Issue by Sebsen** [jmockit/jmockit1#457]
Please provide the following information:

* Version of JMockit that was used: Update from Version 1.30 to Version 1.34

* Description of the problem:
Since the update from JMockit version 1.30 to version 1.34 we're not able to mock any type of exception (standard JDK type neither custom created types) with JMockit's @Mock annotation - bug or feature?

From eclipse JUnit tests stop to run cause an StackOverflowError claiming a NoClassDefFoundError/ ClassNotFoundException when an exception type field is annotated with @Mocked annotation. From ANT execution crashes with an "JVM exited abnormally" error. @Tested on the other hand works fine though.

When an exception type is mocked with @Mocked annotation as method parameter the test just fails directly with the appropriate failure message: "java.lang.IllegalArgumentException: Class java.lang.Throwable is not mockable". Even though it's a standard JDK exception type or a custom one.

In JMockit version 1.32 the mocking of exception types worked fine, so I think the behaviour changed with the release of version 1.33 (which became extended features with the @Tested annotation).

Regards
Sebsen

**Comment by rliesenfeld** [comment]
Indeed, the outcome from `@Mocked SomeException` should be the same as `@Injectable SomeException`.

Thanks for reporting the bug!

**Comment by novaterata** [comment]
I still can't mock any Exception in 1.35 (but could in 1.33) I'm unclear on the status of this issue.
