### ISSUE TITLE
java.lang.IllegalArgumentException: Class java.time.Duration is not mockable when Injectable into Tested

### ISSUE THREAD

**Issue by novaterata** [jmockit/jmockit1#459]
Please provide the following information:

* Version of JMockit that was used: 
1.33-1.34
* Description of the problem:
I have a class with a couple of Duration fields injected through the constructor.

I'm trying to do a typical `@Tested` with `@Injectable` for all of the contsructor parameters like you do.

Because Duration is not mockable (it's as fundamental as String to those who use it),
I get an IllegalArgumentException: Class java.time.Duration is not mockable.

The thing is that I don't want to mock it, I just want to inject. I'm more than happy to provide a real Duration. How do I do this?

```java
class Foo {
    private final Duration duration;
    Foo(Duration duration) { this.duration = duration; }
    Duration getDuration(){ return duration;}
}

class FooTest {
    @Injectable Duration duration = Duration.ofSeconds(1); // how to do this or is this impossible?
    @Tested Foo foo;
    @Test public void whenGetDuration() { assertThat(foo.getDuration()).isEqualTo(Duration.ofSeconds(1)); }
}
```

**Comment by rliesenfeld** [comment]
Simply replace `@Injectable` with `@Tested`.

**Comment by novaterata** [comment]
@rliesenfeld thanks, I didn't know that `@Tested` was also injected.

**Comment by novaterata** [comment]
@rliesenfeld When I add the Duration as a `@Tested`, I get:
    java.lang.IllegalArgumentException: No constructor in tested class that can be satisfied by available tested/injectable values
      private java.time.Duration(long,int)
        disregarded because parameter names are not available

This happens even with a long and an int `@Injectable`, with an explicit value assigned, with fullyInitialized true or false. What am I doing wrong?
