### ISSUE TITLE
`@Mocked` instance replaces enum initialization parameters and impacts unrelated tests

### ISSUE THREAD

**Issue by novaterata** [jmockit/jmockit1#466]
Please provide the following information:

* Version of JMockit that was used: 
1.33-1.35
* Description of the problem:

I have a SupportedTimebases enum which injects a FrameRate object upon initialization of each value.
For example PAL_25 will inject a FrameRate with `25*1/1` and NTSC_30 will inject a FrameRate with `30*1000/1001`

I have a JUnit test that has a `@Mocked private FrameRate frameRate;` field.

A Heisenbug occurs where the SupportedTimebases values are created while JMockit is replacing all instances of FrameRate with the mocked instance.
Since enums are singletons, this means that when run with Gradle (where there is not an independent JVM per test class) even unrelated classes will receive an enum where all FrameRate are `0*0/0` (i.e. The mocked instance).

The fix is simply to change to an `@Injectable`; however, I would highly recommend that JMockit not replace instances used in enum constructors.
I can't convey how frustrating this was to debug and discover the cause.

**Comment by rliesenfeld** [comment]
Well, JMockit's `@Mocked` does not "replace" instances; rather, it mocks the class, which causes all of its methods *and constructors* to be mocked, affecting all present and future instances of the class inside the scope of the `@Mocked` field/parameter.

`@Mocked` does not know or care from *where* a mocked constructor gets executed (in this case, from the constructor of an enum element, if said element gets accessed for the first time during the test). So, it should not be surprising that the execution of `new FrameRate(...)` does get mocked; the annotation is only doing what its API documentation says it will do.

However, mocking the `FrameRate` class looks like a case of over-mocking, if it's "merely" a value-object class of which a real instance could be created instead. The mocking annotations are not meant to be used as a cheap way to create simple instances.

**Comment by novaterata** [comment]
@rliesenfeld I don't have time right now to properly write this up, but I wanted to let you know because I think this can be quite serious. I have this now occurring not because of an enum or other singleton getting "infected" by the `@Mocked` instance as was the case here, but in a `junitparams.Parameters` method with just a regular constructor of the mocked type. That is in a class that doesn't use JMockit at all. Something is not letting go when it should be. I'm going to try replacing all instances with Injectable for now, but this really is a minefield when it can impact completely unrelated test classes.
