### ISSUE TITLE
No alternative for Deencapsulation.invoke()

### ISSUE THREAD

**Issue by yrimal** [jmockit/jmockit1#467]
Please provide the following information:

* Version of JMockit that was used: 1.35

* Description of the problem:
In latest release of JMockit, Deencapsulation.invoke() methods have been deprecated. However, there is no any alternatives if we want to continue using JMockit.

**Comment by rliesenfeld** [comment]
Yes, there is no alternative to "invoke" within JMockit, since, as mentioned in the release note, such methods "are no longer useful in the overall context of JMockit APIs". There are no known use cases.
