### ISSUE TITLE
order of execution affecting the mock behavior

### ISSUE THREAD

**Issue by tlsuresh** [jmockit/jmockit1#470]
* Version of JMockit that was used: 1.35

* Description of the problem: 
If a class is loaded and instantiated for the first time in the context of a mock ( using @Mocked ), then the instance of the class is not getting reset to its proper state. 

I'll explain with an example.
There are two main classes (Application.java and DataService.java ) and a test class ( ApplicationTest.java )

```
package com.app;

public class Application {

    private static final DataService dataService;
    static {
        dataService = new DataService("db");
    }

    public String getData() {
        return dataService.fetchData();
    }
}
```

```
package com.app;

public class DataService {

    private String dataBaseUrl;

    public DataService(String dbUrl) {
        this.dataBaseUrl = dbUrl;
    }

    public String fetchData() {
        if(dataBaseUrl == null ) {
            throw new NullPointerException();
        } else {
            return "data";
        }
    }
}
```
Test code:
```
package com.app;

import mockit.Mocked;
import org.junit.Assert;
import org.junit.Test;

public class ApplicationTest {

    @Test
    public void testMock(@Mocked final DataService dataService) throws Exception {
        Application application = new Application();
        String data = application.getData();
        Assert.assertNull(data);
    }

    @Test
    public void testReal() throws Exception {
        Application application = new Application();
        String data = application.getData();
        Assert.assertNotNull(data);
    }
}
```

1. If we run the test cases individually, they work fine.

2. If we run them in the order testMock followed by testReal, it fails with NPE in testReal ( in DataService.fetchData method )

3. If we run them in the order [ testReal, testMock ], it works fine.

If the first time instance creation was done in the context of @Mocked (trial 2. above) , then the instance doesn't get reset to its proper state, when the mocking goes out of scope. ( when the control reaches the testReal method )

This could cause lot of intermittent errors depending on order of test execution Or order of class loading.

Let me know if i am missing something obvious.

**Comment by rliesenfeld** [comment]
It's normal Java behavior: see #188 for explanation.
