### ISSUE TITLE
Problem with instantiating mocks in a loop.

### ISSUE THREAD

**Issue by jmekaelthas** [jmockit/jmockit1#482]
The issue occured after I updated to version 1.36 (from 1.35). It also occurs in the recent version 1.36.3.

I create a loop in my test function to verify a method that takes several different input variables in varius configurations. The problem is that creating an instance of mocked interface somehow remembers only the first value that was set in the first iteration of the loop.

Here is an example of a code to reproduce the issue:

```
 @Test
public void testMockingInALoop() {
        String[] hosts = new String[] { "host1", "host2", "host3" };
        
        for(String host : hosts) {
            System.out.println("Setting: " + host);
            HttpServletRequest req = new MockHttpServletRequest(host).getMockInstance();
            System.out.println("Getting: " + req.getRemoteHost() + "\n");
        }
    }

   private static class MockHttpServletRequest extends MockUp<HttpServletRequest> {
        private String host;

        public MockHttpServletRequest(String host) {
            this.host = host;
        }

        @Mock
        public String getRemoteHost() {
            return host;
        }
    }
```

And here are the results for version 1.36.+:
Setting: host1
Getting: host1

Setting: host2
Getting: host1

Setting: host3
Getting: host1

When I switch to version 1.35 I get this:
Setting: host1
Getting: host1

Setting: host2
Getting: host2

Setting: host3
Getting: host3

My environment:
Jmockit 1.36
Java: 1.8_111 (64bit)
System: Windows 7 Professional 64bit

**Comment by rliesenfeld** [comment]
This behavior change from `MockUp#getMockInstance()` was an indirect consequence of the removal of the `MockUp(Object)` constructor in version 1.36, along with the support for "stateful" mock-ups.

Instead of using `MockUp` for `HttpServletRequest`, some existing implementation (for example, from the Spring framework) should be used, or an empty one can be created.
