### ISSUE TITLE
the demo test  PartialMockingTest at jmockit.org  can't pass

### ISSUE THREAD

**Issue by hzdavid** [jmockit/jmockit1#484]
Please provide the following information:

* Version of JMockit that was used: 

1.36

* Description of the problem:

According to the demo test at the official site  http://jmockit.org/tutorial/Mocking.html#partial
There are compile errors at PartialMockingTest.java.
1.at method  partiallyMockingAClassAndItsInstances 
Collaborator anyInstance = new Collaborator();  should be declared using final .
because it is referred  at the Expectation anonymous class
  
2.at method partiallyMockingASingleInstance  
Collaborator collaborator = new Collaborator(2); should be declared using final .
because it is referred  at the Expectation anonymous class

Furthermore, the test can't pass even when you add final to fix the problem above.

the test result is :

1.at method partiallyMockingASingleInstance at statement  assertEquals(123, collaborator.getValue());
java.lang.AssertionError: expected:<123> but was:<0> 

2.at method partiallyMockingAClassAndItsInstances at statement  assertEquals(123, c1.getValue());
	java.lang.AssertionError: expected:<123> but was:<0>

**Comment by hzdavid** [comment]
public class PartialMockingTest {
	static class Collaborator {
		final int value;

		Collaborator() {
			value = -1;
		}

		Collaborator(int value) {
			this.value = value;
		}

		int getValue() {
			return value;
		}

		final boolean simpleOperation(int a, String b, Date c) {
			return true;
		}

		static void doSomething(boolean b, String s) {
			throw new IllegalStateException();
		}
	}

	@Test
	public void partiallyMockingAClassAndItsInstances() {
		final Collaborator anyInstance = new Collaborator();

		new Expectations(Collaborator.class) {
			{
				anyInstance.getValue();
				result = 123;
			}
		};

		// Not mocked, as no constructor expectations were recorded:
		Collaborator c1 = new Collaborator();
		Collaborator c2 = new Collaborator(150);

		// Mocked, as a matching method expectation was recorded:
		assertEquals(123, c1.getValue());
		assertEquals(123, c2.getValue());

		// Not mocked:
		assertTrue(c1.simpleOperation(1, "b", null));
		assertEquals(45, new Collaborator(45).value);
	}

	@Test
	public void partiallyMockingASingleInstance() {
		final Collaborator collaborator = new Collaborator(2);

		new Expectations(collaborator) {
			{
				collaborator.getValue();
				result = 123;
				collaborator.simpleOperation(1, "", null);
				result = false;

				// Static methods can be dynamically mocked too.
				Collaborator.doSomething(anyBoolean, "test");
			}
		};

		// Mocked:
		assertEquals(123, collaborator.getValue());
		assertFalse(collaborator.simpleOperation(1, "", null));
		Collaborator.doSomething(true, "test");

		// Not mocked:
		assertEquals(2, collaborator.value);
		assertEquals(45, new Collaborator(45).getValue());
		assertEquals(-1, new Collaborator().getValue());
	}
}

**Comment by rliesenfeld** [comment]
The code in the tutorial is perfectly fine, just checked it. It both compiles and runs. Use of `final` for `anyInstance`, etc. is only needed with Java 7 or older; Java 8+ no longer requires it.

**Comment by hzdavid** [comment]
I am sure it does't run successfully. Here are the errors. 

![test_failed](https://user-images.githubusercontent.com/4660219/33354742-41a06b1e-d4ef-11e7-805e-1cf4320c9172.png)

**Comment by hzdavid** [comment]
JDK 1.8
JUnit 4

**Comment by hzdavid** [comment]
Eclipse: Mars.1

**Comment by rliesenfeld** [comment]
Ah, I get it now. JMockit wasn't yet initialized when the test got executed (and it no longer shows the warning message on console about this anymore...).

This is a JUnit 4-specific issue. See http://jmockit.org/tutorial/Introduction.html#runningTests for details.

**Comment by hzdavid** [comment]
It works now . Thanks for your help.
