### ISSUE TITLE
Code coverage not working on basic example

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#486]
Please provide the following information:

* Version of JMockit that was used: 1.34

* Description of the problem:

create simple java project in eclipse. create simplepackage, simple ClassUnderTest and simple Junit 4 TestCaseForClassUnderTest. Add jmockit jar file to project and first in class path. Add a system property for html output. Build with debug.

Get the following message: JMockit: No classes were instrumented for coverage; please make sure that classes exercised by tests are in a directory included in the runtime classpath, and that they have been compiled with debug information.

Test runs and all good but no coverage is generated. Not jar files being used other than jmockit jar file.

I must be missing something basic but think I am following the directions in the tutorial.

**Comment by brucetrask** [comment]
Sorry it is version 1.34

**Comment by rliesenfeld** [comment]
It's probably some trivial project misconfiguration, and probably not specific to Eclipse. Do you have a Maven pom.xml for the project? And if so, if tests are executed through Maven does the same error occurs?

Anyway, I would need some example project configuration that reproduces the problem. If it does occur with Maven, then just a pom.xml would be enough.

**Comment by brucetrask** [comment]
Ok.  Understood. Maven in certaintly involved here so I will dig in. Thanks.
