### ISSUE TITLE
Duplicate Classes copied from junit and com.sun:tools

### ISSUE THREAD

**Issue by qizy09** [jmockit/jmockit1#487]
Please provide the following information:

* Version of JMockit that was used: 1.19, 1.37

* Description of the problem:

We are developing a Repo with dependcy of both `jmockit`, `junit` and `com.sun:tools`, and found out that `jmockit` has a couple of duplicate classes, with `junit` and `com.sun:tools`, as fllowing.

```
Duplicate classes found:

  Found in: 
    org.jmockit:jmockit:jar:1.37:test
    com.sun:tools:jar:1.4.2:system
  Duplicate classes:
    com/sun/tools/attach/AttachPermission.class
    sun/tools/attach/BsdVirtualMachine.class
    com/sun/tools/attach/AttachNotSupportedException.class
    com/sun/tools/attach/AttachOperationFailedException.class
    sun/tools/attach/HotSpotVirtualMachine.class
    sun/tools/attach/BsdVirtualMachine$SocketInputStream.class
    com/sun/tools/attach/spi/AttachProvider.class
    com/sun/tools/attach/AgentInitializationException.class
    com/sun/tools/attach/VirtualMachine.class
    com/sun/tools/attach/VirtualMachineDescriptor.class
    com/sun/tools/attach/AgentLoadException.class

  Found in: 
    org.jmockit:jmockit:jar:1.37:test
    junit:junit:jar:4.12:test
  Duplicate classes:
    org/junit/runner/Runner.class
```

I doubt these classes were directly copied from `junit` and `com.sun:tools`.

References: [Upgraded embedded Attach API classes to those from OpenJDK 8](https://github.com/jmockit/jmockit1/commit/1a6511086dffbbff20dd21fdaa9032337f9c7e1b) and [through SVN](https://github.com/jmockit/jmockit1/commit/28ca7de6a9ca40f3ebff567d23d157096f5de8dc?diff=split)

I wonder, why not add these dependencies in pom.xml directly?

**Comment by rliesenfeld** [comment]
Those classes *were* directly copied from junit and from OpenJDK (the Attach API).

They cannot be pom.xml dependencies mainly because there is no Maven artifact with just those classes. (It's only one class from JUnit 4, and the Attach API is only made available in the JDK's giant tools.jar file - there isn't a Maven Central artifact with it.)

JMockit 1 relies on these classes being in its own jar so that users don't need to use the `-javaagent` JVM initialization parameter, or add tools.jar to the classpath. JMockit 2, BTW, will no longer bundle them.

**Comment by qizy09** [comment]
@rliesenfeld You stated that no Maven artifact was available for `JUnit 4`.

Could you check the [Maven Artifact](http://central.maven.org/maven2/junit/junit/4.12/junit-4.12.pom) from [Maven Repository](https://mvnrepository.com/artifact/junit/junit), or `Junit's` [Github Repo](https://github.com/junit-team/junit4/blob/master/pom.xml) ?

IMO, adding maven dependency is definitely possible in `pom.xml` like following.

```
     <dependency>                                                                
        <groupId>junit</groupId>                                                                                                                                                                                                                                             
        <artifactId>junit</artifactId>                                            
       <version>${junit.version}</version>                                       
     </dependency>     
```

Would you consider that?

**Comment by rliesenfeld** [comment]
Of course there is a JUnit Maven artifact... I meant there was no such artifact for the Attach API.
