### ISSUE TITLE
Unable to Deencapsulate the private constructor of an enum singleton

### ISSUE THREAD

**Issue by vlaguduva** [jmockit/jmockit1#496]
Please provide the following information:

* Version of JMockit that was used: 1.8
I have an enum singleton with private constructor; while I could get all my methods unit tested and covered by Jacoco but Jacoco coverage seemed low mainly because of the private constructor I believe; To get the better numbers, I have decided to give a go to Deencapsulate the private constructor and create the instance but JMocKIt complains that it cannot find the compatible constructor.

```
public enum Adapter implements HimTranscriptionFrameworkAdapter {
    /** Singleton Instance. */
    INSTANCE;

    /**
     * Initializes the Adapter.
     */
    private Adapter() {
        isStarted = false;
    }
    public void startup() throws Exception {}
}
```
and I have this in my test:

```
Adapter deencapsulatedAdapter =
            Deencapsulation.newInstance(Adapter.class);
        deencapsulatedAdapter.startup();
```

and I get this error:

> java.lang.IllegalArgumentException: No compatible constructor found: Adapter()

**Comment by rliesenfeld** [comment]
This is wrong in so many ways...:

1. If the enum constructor gets executed (and it should) then JaCoCo should show it as covered; if it does not, report as bug to JaCoCo project.
2. The enum constructor *does* have parameters.
3. Enums cannot be instantiated through Reflection, regardless of its constructors.
4. JMockit doesn't have a Deencapsulation.newInstance method in its recent versions.
