### ISSUE TITLE
compatibility with sbt-jupiter-interface

### ISSUE THREAD

**Issue by zghember** [jmockit/jmockit1#499]
Please provide the following information:

Version of JMockit that was used: 1.8

Description of the problem: 
I'm current working on a java project which use sbt. 
I also use Junit5 and use a sbt plugin sbt-jupiter-interface to discover tests. This plugin use a custom class loader to discover tests.
With Jmockit 1.7, I got a error sad Jmockit does not support custom class loader. With 1.8, I got the message below.

> java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider mockit.integration.junit5.JMockitTestEngine could not be instantiated
> 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
> 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
> 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
> 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
> 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
> 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
> 	at org.junit.platform.launcher.core.DefaultLauncher.validateUniqueIds(DefaultLauncher.java:63)
> 	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:58)
> 	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
> 	at net.aichler.jupiter.api.JupiterTestCollector.collectTests0(JupiterTestCollector.java:246)
> 	at net.aichler.jupiter.api.JupiterTestCollector.invokeWithCustomClassLoader(JupiterTestCollector.java:306)
> 	at net.aichler.jupiter.api.JupiterTestCollector.collectTests(JupiterTestCollector.java:73)
> 	at net.aichler.jupiter.sbt.JupiterPlugin$$anonfun$collectTests$1.apply(JupiterPlugin.scala:100)
> 	at net.aichler.jupiter.sbt.JupiterPlugin$$anonfun$collectTests$1.apply(JupiterPlugin.scala:88)
> 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
> 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
> 	at sbt.std.Transform$$anon$4.work(System.scala:63)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> 	at sbt.Execute.work(Execute.scala:237)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)

> 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
> 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.IllegalAccessError: tried to access class mockit.internal.startup.ClassLoadingBridgeFields from class mockit.internal.startup.Startup
> 	at mockit.internal.startup.Startup.initializeIfPossible(Startup.java:134)
> 	at mockit.integration.junit5.JMockitTestEngine.<init>(JMockitTestEngine.java:27)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
> 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
> 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
> 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
> 	at org.junit.platform.launcher.core.DefaultLauncher.validateUniqueIds(DefaultLauncher.java:63)
> 	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:58)
> 	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
> 	at net.aichler.jupiter.api.JupiterTestCollector.collectTests0(JupiterTestCollector.java:246)
> 	at net.aichler.jupiter.api.JupiterTestCollector.invokeWithCustomClassLoader(JupiterTestCollector.java:306)

> 	at net.aichler.jupiter.api.JupiterTestCollector.collectTests(JupiterTestCollector.java:73)
> 	at net.aichler.jupiter.sbt.JupiterPlugin$$anonfun$collectTests$1.apply(JupiterPlugin.scala:100)
> 	at net.aichler.jupiter.sbt.JupiterPlugin$$anonfun$collectTests$1.apply(JupiterPlugin.scala:88)
> 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
> 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
> 	at sbt.std.Transform$$anon$4.work(System.scala:63)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> 	at sbt.Execute.work(Execute.scala:237)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
> 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

The question is, how can I use sbt+Junit5+jmockit to test my project. If I don't use sbt-jupiter-interface, sbt can not find any test in my project. When I run tests in my IDE and without sbt, it works very well but I'm looking for a way to test in shell.

refer to sbt-jupiter-interface : https://github.com/maichler/sbt-jupiter-interface

**Comment by novaterata** [comment]
jmockit is on version 1.38 now. Is that the version you meant, or did you really mean 1.8?

**Comment by zghember** [comment]
sorry, I meant 1.38 and 1.37
