### ISSUE TITLE
JMockit.org is not working

### ISSUE THREAD

**Issue by mrprim** [jmockit/jmockit1#500]
The JMockit.org github-pages page is currently inaccessible.  It's giving a 404.

![image](https://user-images.githubusercontent.com/8786567/34779086-2d755446-f5ed-11e7-9ff2-729d52ecbd59.png)

**Comment by rliesenfeld** [comment]
The home page url has changed to [jmockit.github.io](http://jmockit.github.io).

**Comment by nwillc** [comment]
Should change the link in the readme to stop driving traffic to old local
