### ISSUE TITLE
Support includeTests coverage property

### ISSUE THREAD

**Issue by mark-malynn** [jmockit/jmockit1#502]
Please provide the following information:

* Version of JMockit that was used: 1.32

* Description of the problem:
I have an annotation processor that generates code. I want to get code coverage of the generated code in my tests. However, since my test classes that exercise the annotation that triggers code generation causes the generated to reside in target/generated-test-sources, jmocket coverage tool doesn't provide code coverage. 

I would like jmockit to support a new property, includeTests, that includes 'test' classes in its coverage report.

**Comment by rliesenfeld** [comment]
Including classes with "*Test" names as well as code from the "test-classes" directory is already supported, by setting the "coverage-classes" system property.
