### ISSUE TITLE
Exception when using JDK 9

### ISSUE THREAD

**Issue by lgLindstrom** [jmockit/jmockit1#505]
Please provide the following information:

* Version of JMockit that was used: 1.38

* Description of the problem:
When running unit tests I get this exception:
java.lang.IllegalStateException: Running on JDK 9 requires -javaagent:<proper path>/jmockit-1.n.jar or -Djdk.attach.allowAttachSelf at java.base/java.lang.Thread.run(Thread.java:844)  

Using JUnit 5.0 and org.testfx:testfx-core:4.0.10-alpha.

**Comment by rliesenfeld** [comment]
See #418
