### ISSUE TITLE
Not Git tags in GitHub

### ISSUE THREAD

**Issue by szpak** [jmockit/jmockit1#514]
It could be useful to have Git tags pushed (assuming you have them created locally on releases) to GitHub to see exactly if given commit (a change/fix) was incorporated into a given JMockit version.

**Comment by szpak** [comment]
It could be also used to get notification about the new released from GitHub.

**Comment by rliesenfeld** [comment]
Tags are not used for releases (no compelling use that I know of). The [release notes](http://jmockit.github.io/changes.html), together with commit messages containing issue numbers, are already supposed to let people track versions, fixes, and corresponding issues.

Same as #498, basically.
