### ISSUE TITLE
Debug not work in Eclipse4.7.3a, Intellij IDEA 2018.1 as well

### ISSUE THREAD

**Issue by zhyhang** [jmockit/jmockit1#516]
Please provide the following information:

* Version of JMockit that was used: 
1.39

* Description of the problem:
**Debug not work in Eclipse4.7.3a, Intellij IDEA 2018.1 as well.** All breakpoints skipped. When degrade to 1.38 is OK.

JDK1.8_144

JUnit4.12

Spring-boot 1.5.12

**Comment by rliesenfeld** [comment]
Same as #513.
