### ISSUE TITLE
@Mocked class behaviour changes between member and parameter (TestNG) 

### ISSUE THREAD

**Issue by TarekSaid** [jmockit/jmockit1#518]
Using: java 8, TestNG 6.14.2, jmockit 1.39

Given that I've written the following code and test that is supposed to fail (before fix):

**code**
```java
public void addBar(String fooName, Bar bar) {
  Foo foo = fooRepository.findByName(fooName);
  new Foo().addBar(bar); // line that should fail
  fooRepository.save(foo);
}
```
**test**
```java
@org.testng.annotations.Test
public class FooServiceTest {
  @Tested private FooService fooService;

  @Injectable private FooRepository fooRepository;

  @Mocked private Foo foo;

  public addBarShouldAddBarToFoo(@Mocked Bar bar) {
    new Expectations {{ fooRepository.findByName(anyString); result = foo; }};
    fooService.addBar("",bar);
    new Verifications() {{ foo.addBar(bar); }};
  }
}
```
Then the code should fail with `Missing invocations to: com.example.Foo#addBar`

But when I change the test to the following, then the code fails as expected:
```java
  public addBarShouldAddBarToFoo(@Mocked Foo foo, @Mocked Bar bar) {
    // same code as before
  }
```

I was expecting the test to fail using either a mocked member or a mocked parameter.

**Comment by rliesenfeld** [comment]
For me, both versions of the test do pass. But that is as expected, since all instances of class `Foo` are getting `@Mocked`. You probably meant to have an `@Injectable Foo foo`.
