### ISSUE TITLE
Constructor expectation not matching for 'withSameInstance' matcher

### ISSUE THREAD

**Issue by mnakhtar** [jmockit/jmockit1#520]
* Version of JMockit that was used: 
JMockit - 1.39, JUnit - 4.12, JDK - 1.7

Constructor expectation not matching when 'withSameInstance' matcher is used.

`
public class ClassA {
  public ClassA() {
  }
}

public class ClassB {
  private final ClassA classA;

  public ClassB(final ClassA classA) {
    this.classA = classA;
  }

  public void enable() {
    int counter = 0;
    counter++;
  }
}

public class ClassC {
  public void aMethod() {
    ClassA classA = new ClassA();         // this must be the mock instance as per Expectations
    ClassB classB = new ClassB(classA);   // this must be the mock instance as per Expectations
    classB.enable();
  }
}

@RunWith(JMockit.class)
public class TestClassC {
  @Tested
  ClassC classC;

  @Test
  public void aTest(final @Mocked ClassA classA,
                    final @Mocked ClassB classB) {
    new Expectations() {
      {
        new ClassA(); result = classA;
        new ClassB(withSameInstance(classA)); result = classB;
        classB.enable(); times = 1;
      }
    };

    // method under test
    classC.aMethod();
  }
}
`

In the above test, if 'withEqual' matcher or 'classA' mocked object is used, the test pass but that is neither the intention of the code under test nor the correct test.

**Comment by rliesenfeld** [comment]
That is not how `@Mocked` works. See [Getting started](http://jmockit.github.io/gettingStarted.html).

**Comment by mnakhtar** [comment]
The [following](http://jmockit.github.io/tutorial/Mocking.html#futureInstancesByConstructor) pattern was used with the only addition of 'withSameInstance'.

**Comment by rliesenfeld** [comment]
Yes, but `withSameInstance` only matches successfully if the two instances (the one used when recording and later the one received during replay) are actually the same, which they aren't. The "replacement instance" mentioned in the Tutorial doesn't actually replace the future created instance, but only gives it the mocked behavior specified for the recorded instance. (Perhaps I should find a different word than "replacement" for use in the Tutorial.)

**Comment by mnakhtar** [comment]
Reading your reply, is it correct that the above code segment is using 'withSameInstance' in the recording phase and never used in reply. If that is the case, the test case that I am trying to achieve is that the recording should match an expectation with 'withSameInstance'. 'withEqual' is not acceptable.
