### ISSUE TITLE
withCapture performs actual invocation in Expectations

### ISSUE THREAD

**Issue by caillette** [jmockit/jmockit1#521]
With JMockit 1.39, using `withCapture` twice on the same mock performs actual invocations when running in the `Expectations`. This doesn't happen when using `withCapture` only once.

```
public class JmockitCaptureBug {

  @Test
  public void captureBug( @Injectable Consumer< String > consumer ) {
    final List< String > captor = new ArrayList<>() ;
    new Expectations() {{
      consumer.accept( withCapture( captor ) ) ;
      consumer.accept( withCapture( captor ) ) ;
    }} ;
    consumer.accept( "1" ) ;
    consumer.accept( "2" ) ;
    assertThat( captor ).containsExactly( "1", "2" ) ;
  }
}
```

```
java.lang.AssertionError: 
Actual and expected should have same size but actual size was:
  <4>
while expected size was:
  <2>
Actual was:
  <[null, null, "1", "2"]>
Expected was:
  <["1", "2"]>
```

**Comment by rliesenfeld** [comment]
The test is incorrectly recording two identical expectations. Record it only once and everything works as expected. Also, using a verification block would be better:

```
   @Test
   public void verifyConsumedValues(@Injectable Consumer<String> consumer) {
      consumer.accept("1");
      consumer.accept("2");

      new Verifications() {{
         List<String> values = new ArrayList<>();
         consumer.accept(withCapture(values));
         assertEquals(asList("1", "2"), values);
      }};
   }
```

**Comment by caillette** [comment]
I am migrating tests from JMockit 1.20 and JMockit has evolved a lot, to say the least.

The test case I wrote is the smallest piece of code reproducing the behavior change. But my code is testing networking stuff with callback ran in other threads, and I want deterministic ordering for call sequence.

Here is the code I'm trying to migrate:
https://github.com/OTCdLink/Chiron-framework/blob/master/modules/chiron/integration/src/test/java/com/otcdlink/chiron/downend/DownendConnectorTest.java#L323

I've somewhat hijacked the `withCapture` to get some rendez-vous point that transfers a reference to a callback to the capturing list, then the test waits until the capturing list gets fed. This is the only reliable way I've found to make JMockit test heavily multithreaded code. This more or less worked as long as I could hook on several method calls using `withCapture`.

I wish I could write something like this:

```
  public void badCredentialThenCancel( 
      @Injectable( timeout = 1000 ) final SignonMaterializer signonMaterializer 
  ) throws Exception {

    new Verifications() {{
      signonMaterializer.readCredential( with( new Delegate< Consumer< Credential > >() {
        @SuppressWarnings( "unused" )
        void delegate( final Consumer< Credential > consumer ) {
          consumer.accept( CREDENTIAL_BAD ) ;
        }
      } ) ) ;  
      // Thanks to `timeout`, Verification waits until the method above gets called.

      signonMaterializer.setProgressMessage( "Signing in …" ) ; 
      // Verification waits here, too.

      signonMaterializer.setProgressMessage( null ) ; 
      // Verification waits here, too.

      signonMaterializer.setProblemMessage( SIGNON_FAILURE_NOTICE_INVALID_CREDENTIAL ) ;  
      // Verification waits here, too.

      assertThat( fixture.phaseGuide().waitForNextInbound().text() )
          .contains( "PRIMARY_SIGNON" ) ;
    
      signonMaterializer.readCredential( with( new Delegate< Consumer< Credential > >() {
        @SuppressWarnings( "unused" )
        void delegate( final Consumer< Credential > consumer ) {
          consumer.accept( null ) ;
        }
      } ) ) ;  
      // Verification waits here, too.

      signonMaterializer.done() ; 
      // Verification waits here, too.
    }} ;
```

The new `timeout` parameter on the `@Injectable` annotation tells to wait for method calls to happen. So something like `signonMaterializer.setProgressMessage( ... )` in the `Verifications` block won't fail immediately as not called. (An alternative approach would be to decorate each method call with `timeout`, as with `minTimes`.)

The `Delegate`-based approach is a bit verbose and I'd prefer to use a `with(Function<T,T>)` instead but this would make JMockit's API confusing. I can probably emulate that with a static method.


We already discussed about the `timeout` a long time ago:
https://groups.google.com/d/msg/jmockit-users/8LReig8A5FE/hpQfTrZchbAJ

Somebody else came with the same idea:
https://github.com/jmockit/jmockit1/issues/434

For now I'm trying to hack something with JMockit 1.39, but it will probably require a lot of explicit locks and `Delegate` objects in an `Expectation`.
