### ISSUE TITLE
MockUp java.io.FileInputStream cause failure in recording Expectation and new MockUp

### ISSUE THREAD

**Issue by jwaynez** [jmockit/jmockit1#525]
* Version of JMockit that was used: 1.38

* Description of the problem:
When the "FileInputStream" is mocked through "new MockUp<FileInputStream>" mechanism, it could be recorded but it will "hang" and not proceed into the next "new Expectation" or "new MockUp<some class>" encountered. I ran the JUnit4 test case in Eclipse in debug mode. After recording the MockUp for the FileInputStream, it could continue on other lines until the point there was new Expectation or MockUp. It was simply like hanging there. No error reported and no activities observed. 
```
import org.junit.Before;
import org.junit.Test;

import mockit.Expectations;
import mockit.Mock;
import mockit.MockUp;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.File;

public class TempTest {
    
    int myTest = 0;

    @Before
    public void setUp() throws Exception {
        
        new MockUp<FileOutputStream>() {
            @Mock
            public void $init(File file) {
                System.out.println("Mocked <FileOutputStream> class: " +file);
            }
        };
       
        new MockUp <FileInputStream>() {
            @Mock
            public void $init(File file) {
                System.out.println("Mocked <FileInputStream> class");
            }
        };

        myTest = 1;
    }

    @Test
    public void test() {
        myTest = 2;
        
        new Expectations() {
            {      
               myTest = 3;
            } 
        };
        
        myTest = 10;
    }
}
```

**Comment by rliesenfeld** [comment]
I get a 
```
java.lang.NullPointerException
	at java.io.FileInputStream.close(FileInputStream.java:316)
```
exception from executing the test, caused by the application of the `@Mock $init(File)` to `FileInputStream`.
That's not surprising. The real problem is trying to fake fundamental JRE classes such as `FileInputStream` in the first place.

**Comment by jwaynez** [comment]
Will that means the FileInputStream cannot be mocked?

Any other JRE classes which cannot be mocked?

**Comment by rliesenfeld** [comment]
`FileInputStream` *can* be either mocked or faked:
```
package otherTests;

import java.io.*;
import org.junit.*;
import static org.junit.Assert.*;
import mockit.*;

public class TempTest
{
   @Test
   public void fakingFileInputStream() throws Exception {
      new MockUp<FileInputStream>() {
         @Mock void $init(String fileName) {}
         @Mock int read() { return 123; }
      };

      int r = new FileInputStream("notExisting").read();

      assertEquals(123, r);
   }

   @Test
   public void mockingFileInputStream() throws Exception {
      new Expectations(FileInputStream.class) {{
         new FileInputStream(anyString).read(); result = 123;
      }};

      int r = new FileInputStream("notExisting").read();

      assertEquals(123, r);
   }
}
```
These tests work. But since `FileInputStream` is used by many libraries and by the JDK itself, mocking/faking it can easily produce unexpected failures.

**Comment by jwaynez** [comment]
>
> I really appreciate your help.
>
> I ran yours. It worked fine.
>
> But in mine, the constructor had to be FileInputStream(File) rather than
> FileInputStream(String). It was because the production code used the
> earlier one. Then testing had to mock that one.
>
> Actually, it could record the mocking but the problem was when it
> encountered another MockUp or Expectation it hang in mine. Is it the
> FileInputStream(File) cannot be mocked properly?
>

Thanks,

Wayne

**Comment by jwaynez** [comment]
I tried by modifying yours in the "fakingFileInputStream()" to use the
FileInputStream(File).

Then right after that MockUp. I added a new "Expectations()" which does
nothing but to set a member variable to a value.

It failed when trying to record the new "Expectations()".
