### ISSUE TITLE
[BUG] Breakpoints not working with JMockit 1.39

### ISSUE THREAD

**Issue by ghilainm** [jmockit/jmockit1#527]
* Version of JMockit that was used: 
1.39

* JVM version
1.8.0_161

* Description of the problem:
I am using @Tested + @Injectable feature. I can not debug my JUnit test class neither my tested class (debugger doesn't stop). This was working fine with JMockit 1.23. I saw another thread raising the issue but long ago and it seems that the issue is not solved (or reappeared?).

**Comment by rliesenfeld** [comment]
Same as #513.
