### ISSUE TITLE
Replacement for named Expectations ?

### ISSUE THREAD

**Issue by rhuss** [jmockit/jmockit1#530]
Please provide the following information:

* Version of JMockit that was used:  1.40

Thanks for your awesome library, really love the concepts. However, I have severe issues updating a larger Java project from JMockit 1.33 to 1.40 as we used named Expectation subclasses quite intensively.

According to the resolution of #529 :

> Not a bug. Support for named Expectations subclasses was dropped in 1.38.

The question of #529: What can I use as an alternative to named Expectation subclasses?

**Comment by rliesenfeld** [comment]
Answer: create reusable methods containing expectation blocks (it's what I do in practice, although only rarely).
