### ISSUE TITLE
Could not make mock and NPE thrown in nested test with JUnit 5.2.0 

### ISSUE THREAD

**Issue by kunkun26** [jmockit/jmockit1#531]
Please provide the following information:

* Version of JMockit that was used: 
1.40

* Description of the problem:
Using JMoclit 1.40 with JUnit 5.2.0 and try to mock some class in nested test, then NullPointerException is thrown. 
code is like the following.

```
class SampleA {
    private int id;
    private String name;

    SampleA(int id, String name) {
        this.id = id;
        this.name = name;
    }

    String getUid() {
        return "(" + id + ")" + name;
    }
}

@RunWith(JUnitPlatform.class)
class TestClass {

    @Nested
    class TestSubClass {

        @Mocked
        SampleA a;
        
        @BeforeEach
        void setup() {
            new Expectations() {
                {
                    a.getUid();
                    result = "hogehoge";
                }
            };
        }

        @Test
        void test() {
            assertThat(a.getUid(), is("hogehoge"));
        }
    }
}
```
Exception is thrown on line `a.getUid();`

It's seemed that https://github.com/jmockit/jmockit1/issues/412 is similar but if tests are defined under `TestClass` directly (not nested case) or  only mocked member ( i.e. SampleA) is defined in `TestClass`, test was passed

#### cases of test passing

```
@RunWith(JUnitPlatform.class)
class TestClass {
    @Mocked
     SampleA a;

    @BeforeEach
    void setup() {...}
        
    @Test
    void test() {...}
}
```

```
@RunWith(JUnitPlatform.class)
class TestClass {
    @Mocked
     SampleA a;

    @Nested
    class TestSubClass {
        @BeforeEach
        void setup() {...}

        @Test
        void test() {...}
}
```

**Comment by rliesenfeld** [comment]
Mock fields are not supported in `@Nested` test classes (mock parameters are, though).
Adding said support is possible, but not trivial.

I would need to see a realistic use case showing where the feature would be useful, before I can justify the implementation effort.
