### ISSUE TITLE
Please clarify the -javaagent requirements for gradle

### ISSUE THREAD

**Issue by novaterata** [jmockit/jmockit1#545]
In the release notes for 1.42, you say that the -javaagent is now required, but only the Maven example shows it being configured. If it is not required for Gradle, can you clarify that in the documentation, or update the example gradle configuration with one that sets the -javaagent

**Comment by rliesenfeld** [comment]
Yes, "-javaagent" is required regardless of the build tool used. I will add the missing configuration info for Gradle, once I figure it out (again) myself.

**Comment by novaterata** [comment]
Thanks!

**Comment by rliesenfeld** [comment]
Done.

**Comment by novaterata** [comment]
@rliesenfeld Just looked at the updated documentation. Gradle builds don't typically interact with mavenLocal, so this doesn't seem idiomatic to me, and I'm skeptical it will work out of the box for many people. I would expect the jar to be pulled from a dependency configuration like testCompile. I'll try to get it to work and get back to you, but I've been using gradle for a couple of years and never even seen mavenLocal in a gradle script before.

**Comment by arjenm** [comment]
I just spent an hour trying to figure it out, this works for me and is a much cleaner solution than the one in the documentation (which doesn't work in Windows for instance):
`test { 
   jvmArgs "-javaagent:${classpath.find { it.name.contains("jmockit") }.absolutePath}"
}`

As described here: https://github.com/gradle/gradle/issues/4618#issuecomment-371417222
Supplying the plugin would be even better ;)

**Comment by rliesenfeld** [comment]
It works for me on Windows 7, but I am open to a better way. I will test it (the "classpath.find" way) later, and change the documentation accordingly.

**Comment by novaterata** [comment]
It probably works for you because you use maven and have a local
repository. Someone who only uses Gradle and never maven wouldn't have a
local maven repository.

**Comment by mduliszewski** [comment]
@rliesenfeld  Guys i am using gradle and intelliji, I added testCompile('org.jmockit:jmockit:1.4.4') and 
jvmArgs "-javaagent:${classpath.find { it.name.contains("jmockit") }.absolutePath}", like described on the site and i still get an error java.lang.ExceptionInInitializerError (JMockit didn't get initialized; please check the -javaagent JVM initialization parameter was used) 

Also intelijji says it cannot resolve symbol 'absolutePath' when i hover over it

Please help.

**Comment by novaterata** [comment]
The version is 1.44 not 1.4.4, and IntelliJ is only giving the warning
because groovy is a dynamic language, so absolutePath won't exist until
runtime. Once you fix the version string then you should be good.

**Comment by mduliszewski** [comment]
Ok it works now when i change Run/Debug config to Gradle (was JUnit run/debug config) Thanks to @novaterata
