### ISSUE TITLE
Prevent the need for -javaagent on Java 9+ and JMockit 1.42+

### ISSUE THREAD

**Issue by Thunderforge** [jmockit/jmockit1#546]
In #544, it was asked to remove the need for the `-Djdk.attach.allowAttachSelf ` parameter, which appears on JMockit 1.41 and Java 9+. The response was that this would be replaced with `-javaagent` on JMockit 1.42 (and the discussion was frustratingly locked so that no further clarification questions could be asked).

The same underlying problem remains though: it is very inconvenient to have to add a flag to every run in Maven ([and Gradle?](https://github.com/jmockit/jmockit1/issues/545)), as well as IDE runs for individual tests. It is also a common newbie mistake to forget to add these flags, and we've already had several closed issues where that was what people forgot to do. In other words, having a mandatory flag is making JMockit harder to use than it should be.

The best solution would be to create a workaround, [like ByteBuddy did](https://github.com/raphw/byte-buddy/issues/295#issuecomment-297394387), so that neither a `-Djdk.attach.allowAttachSelf` parameter nor a `-javaagent` parameter needs to be added. If this is not possible, then please explain what the obstacles are (in the hopes that someone else can figure out how to overcome the obstacles and submit a PR).

----
(As a meta-concern, I am very frustrated that JMockit issues have been locked immediately after closure. I don't know of any other GitHub project that locks its issues so swiftly. That makes it very difficult to ask for clarifications or otherwise comment on the issue. Please consider turning off the locks so that conversation can continue, if needed).

**Comment by rliesenfeld** [comment]
There are several technical difficulties in getting dynamic Java agent loading (through use of the Attach API) to work. It requires several hacks, and it's ultimately not reliable (for example, in certain cases Maven/Gradle ends up loading Expectations subclasses before the agent gets loaded, preventing JMockit's `ClassFileTransformer` from doing its job).

"-javaagent", on the other hand, is the standard way to get a Java agent loaded. With a good IDE (for example, IntelliJ), all you need to do is add the parameter in the test execution command line (for example, in Maven Surefire plugin configuration); the IDE should automatically add it to the command line whenever a test is executed (with IntelliJ, which I use, it's working fine - I imagine Netbeans should be ok too as it uses Maven for test execution).

**Comment by jordanglassman** [comment]
> all you need to do 

Coming back to jmockit after 2 years of being forced to suffer with EasyMock and finding this new requirement has been added.

jmockit is the superior mocking framework in every way, but IMO this javaagent requirement is a big step backwards in terms of ease of use and especially for accessibility for new users, which will hurt adoption.  Even experienced Java developers will be scared away by this "icky" requirement.

**Comment by rliesenfeld** [comment]
It's hardly a problem, given that it simply takes an additional line in the `pom.xml` or `gradle.build` file (which a decent IDE picks up automatically, BTW).

Anyway, the requirement for `-javagent` is the responsibility of OpenJDK developers, who insist on it for no good reason (actually, more for the lack of vision in the early Java 5 days, followed by historical inertia), and even add an absurd, non-sensical new constraint such as the `jdk.attach.allowAttachSelf` parameter added in Java 9 (which can be worked-around without much difficulty, proving it's ineffective anyway).

**Comment by Thunderforge** [comment]
> It's hardly a problem, given that it simply takes an additional line in the pom.xml or gradle.build file (which a decent IDE picks up automatically, BTW).

@rliesenfeld Really? For our projects, we have to do the following for Gradle:

```
test {
    // Hook up Gradle tests to JMockit
    jvmArgs "-javaagent:${classpath.find { it.name.contains("jmockit") }.absolutePath}"
}
```

But we couldn't get Intellij IDEA to pick up the setting. Eventually, we were able to get it to work with this:

```
buildscript {
    dependencies {
        classpath "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:0.5"
    }
}

apply plugin: "idea"
apply plugin: "org.jetbrains.gradle.plugin.idea-ext"

import org.jetbrains.gradle.ext.*

idea {
    project {
        languageLevel = project.sourceCompatibility
        settings {
            // See https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.1
            runConfigurations {
                // Default parameters for all JUnit run configurations
                defaults(JUnit) {
                    // JMockit requires a VM parameter to be added.
                    // See http://jmockit.github.io/tutorial/Introduction.html#gradle
                    // Note that we added the "test" scope
                    vmParameters = "-javaagent:${test.classpath.find { it.name.contains("jmockit") }.absolutePath}"
                }
            }
        }
    }
}
```

Our group really hates these gymnastics to get JMockit hooked up, and it's been a point of contention in conversations about if we should switch to Mockito.

I don't know anything about the internals of JMockit or the technical reasons why this is necessary (or the decisions of OpenJDK maintainers), but I think it's disingenuous to say that it's "hardly a problem" for end developers.

**Comment by rliesenfeld** [comment]
See #545 for more info.
