### ISSUE TITLE
Fail to run in debug mode when mocking Thread

### ISSUE THREAD

**Issue by sleepingpig** [jmockit/jmockit1#550]
Please provide the following information:

* Version of JMockit that was used: 
1.42

* Description of the problem:
It looks like whenever I'm trying to mock java.lang.Thread, and run the test code in debug mode using IntelliJ, it will produce the error:
```
java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
```
If not in debug mode, it works fine.
To demonstrate, I used the [sample code](https://github.com/jmockit/jmockit1/blob/2ca1b0b9eb3479e32fc35506df78763ffd7d85fa/main/test/mockit/JREMockingTest.java#L118-L124) in the JMockit source code.
Use debug mode to run the method "secondMockingOfNativeMethods", and the error will pop up.
The IntelliJ version I'm using: 2018.2.3.

**Comment by rliesenfeld** [comment]
It's working fine for me (using IntelliJ 2018.2.3), in debug mode or not.

**Comment by sleepingpig** [comment]
I set the IntelliJ settings as below:
In "Project Structure"
Project SDK: Oracle JDK 1.8.0_121
Project language level: 7
Module language level: 7

In "Preferences" (or "Settings" on Windows) -> "Build, Execution, Development" -> "Compiler" -> "Java Compiler"
target byte code version: 7

And right click on "secondMockingOfNativeMethods" -> "Debug"

I tested it on Mac and Windows 10.
