### ISSUE TITLE
IllegalAccessError tried to access private field in Expectations block (java 11)

### ISSUE THREAD

**Issue by Hirak2018** [jmockit/jmockit1#552]
I am using 1.40 version 

IllegalAccessError tried to access private field in Expectations block (java 11)
This issue is Java11 specific 

======Sample code to reproduce the problem=====

package hirak.inner.test;

import mockit.Expectations;

public class Test {

    private int myNum=0;

    @org.junit.Test
    public void myTestTest2() {
        new Expectations() {{
            Myclass1.getMyclass();
            result = myNum;
            minTimes=0;
        }};

    }
}

class Myclass1 {
    public static int getMyclass() {
        int i=2;
        return i;
    }
}

=======Output======
java.lang.IllegalAccessError: class hirak.inner.test.Test$1 tried to access private field hirak.inner.test.Test.myNum (hirak.inner.test.Test$1 and hirak.inner.test.Test are in unnamed module of loader 'app')

	at hirak.inner.test.Test$1.<init>(Test.java:17)
	at hirak.inner.test.Test.myTestTest2(Test.java:15)

**Comment by rliesenfeld** [comment]
The failure does occur, but it can be avoided by making the field non-private (which is ok since it's in a test class), or (even better) by not accessing such a field from inside an expectation block.
