### ISSUE TITLE
IllegalAccessError on private fields using JDK11

### ISSUE THREAD

**Issue by adessaigne** [jmockit/jmockit1#553]
Please provide the following information:

* Version of JMockit that was used: 1.42

* Description of the problem:
With lastest build of Java 11 which will be released next week I have an issue with JMockit and I've checked that it's not due to bugs in development version of Java.

Here is the code
```java
public class Jdk11Test {
    private static final Map<String, String> DICT = Map.of("Hello", "Bonjour");

    @Mocked
    Supplier<String> m_supplier;

    @Test
    public void shouldWork() {
        new Expectations() {{
            m_supplier.get();
            result = DICT.get("Hello");
        }};
        assertEquals(m_supplier.get(), "Bonjour");
    }

    @Test
    public void isJavaIssue() {
        Map<String, String> map = new HashMap<>() {{
            putAll(DICT);
        }};
        assertEquals(map, DICT);
    }
}
```

When compiled and tested with Java 11, the `shouldWork()` test throws the following exception:
```
java.lang.IllegalAccessError: class Jdk11Test$1 tried to access private field Jdk11Test.DICT (Jdk11Test$1 and Jdk11Test are in unnamed module of loader 'app')
	at Jdk11Test$1.<init>(Jdk11Test.java:19)
	at Jdk11Test.shouldWork(Jdk11Test.java:17)
```

If compiled and tested with Java 10 then it's working.

To be sure that it wasn't due to JDK11 there's the `isJavaIssue()` method that uses the same static initialization than `Expectation`. And this test is working fine.

If needed I have a small maven project that shows the issue.

* Check that:

 - [ ] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
See #552.

**Comment by adessaigne** [comment]
Hello @rliesenfeld ,

As a workaround in #552 you mentioned making the field non-private. Unfortunately this is not an ideal solution in our large codebase as it's not easy to see what is the error when the test fails.

The root cause of the issue is that JDK11 now requires the NestHost class attribute to be defined when accessing private members of outer class. It's defined in [JEP 181](http://openjdk.java.net/jeps/181).

I've just pushed the pull request #555 that supports this NestHost attribute.
