### ISSUE TITLE
mockit.integration.junit4.JMockit class removed in 1.42

### ISSUE THREAD

**Issue by froudj** [jmockit/jmockit1#554]
What happened to `mockit.integration.junit4.JMockit` class on v1.42? The release note doesn't mention this removal.

`@RunWith(JMockit.class)` aren't compiling... This is harsh, not even a "deprecated" annotation in earlier releases...

**Comment by rliesenfeld** [comment]
Starting with JMockit 1.42, `@RunWith(JMockit.class)` would have no effect anyway; simply remove it from test classes.
