### ISSUE TITLE
Subsequent Expectations Blocks Overwrite previous expectations for non strict expectations.

### ISSUE THREAD

**Issue by polydectes** [jmockit/jmockit1#557]
JMockit version 1.18
JDK 1.8.0_172
Language: Java

Description:
We have a number of complex expectations used by multiple tests.  To accommodate these we have made common "expect...()" methods to setup our expectations.

One of these scenarios requires returning the same value from a query multiple times followed by a different value.

i.e.
```
@Mocked private Testable t;
...
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = x;
  result = x;
  ...
  result = x;
  result = null;
...
}};
```
Due to the varying number of returns required for each test we want to do this using times where the count is a variable.

i.e.
```
@Mocked private Testable t;
...
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = x; times = n;
  result = null;
...
}};
```
Unfortunately we are unable to get this structure working using times with this expectations structure.

We have tried creating new expectations as follows:
1) 
```
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = x; times = n;
  result = null;
  ...
}};
```
2)
```
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = x; times = n;
  ...
  t.getSomeValue();
  result = null;
  ...
}};
```
3)
```
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = x;
  result = x;
  ...
  result = x;
  result = null;
  ...
}};
```
4)
```
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = x; times = n;
  ...
}};
new Expectations() {{ 
  ...
  t.getSomeValue();
  result = null;
  ...
}};
```
Of these, we have only been able to get version 3 to work properly.  The others appear to be overwriting the invocations information for the result of x with the invocation for the result of null.  We have confirmed this by drilling into the RecordAndReplayExecution instance executionState.notStrictExpectations list and verified that the entry within the list is replaced with new invocation information effectively throwing out the original result value.

**Comment by rliesenfeld** [comment]
Looks to me the real problem is using the mocking API too much; I would recommend moving towards integration testing; it's what works for me, anyway.
