### ISSUE TITLE
re-creating a Fake during a single test fails

### ISSUE THREAD

**Issue by lstreepy** [jmockit/jmockit1#559]
Please provide the following information:

* Version of JMockit that was used: 
JMockit 1.38 (also tested against 1.39 and 1.41)
Gradle 4.8
JVM: 1.8.0_152 (Oracle Corporation 25.152-b16)
OS: Windows 7 6.1 amd64
TestNG: 6.8

* Description of the problem:

Re-creating a Fake during a single test fails.  To fail, the body of the faked method has to refer to a captured value from the context where the fake was created (in this case a method argument).

If the MockUp creation is inlined into the test method with hard-coded return values, then this test passes.

This failure was introduced somewhere between 1.21 and 1.37.

Reproducer:
```java
package reproducer;

import mockit.Mock;
import mockit.MockUp;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test to show that re-creating a Fake during a single test fails.  To fail, the body of the faked method
 * has to refer to a captured from the context where the fake was created (in this case a method argument).
 * <p>
 * If the MockUp creation is inlined into the test method with hard-coded return values, then this test passes.
 * <p>
 * This failure was introduced somewhere between 1.21 and 1.37.
 */
public class ReFakingTests
{
    public static class CUT
    {
        int getValue()
        {
            System.out.println("in real");
            return -1;
        }
    }

    @Test
    public void testReFaking()
    {
        CUT cut = new CUT();
        Assert.assertEquals(cut.getValue(), -1);

        makeFake(1);
        Assert.assertEquals(cut.getValue(), 1);

        makeFake(2);
        Assert.assertEquals(cut.getValue(), 2); // Fails at version 1.37, passes with 1.21
    }

    void makeFake(int value)
    {
        new MockUp<CUT>()
        {
            @Mock
            int getValue()
            {
                System.out.println("in fake " + value);
                return value;
            }
        };
    }
}
```

**Comment by rliesenfeld** [comment]
Re-applying a mock-up that is already in effect indeed does nothing (it is checked and ignored).

A second mock-up applied to the same type overrides the current mock-up, if any (such as in the "MockUp creation inlined into the test method with hard-coded values" case mentioned above, which actually are two different mock-ups, not the same one applied twice).

**Comment by lstreepy** [comment]
First, a question: How are calling a method that creates the MockUp vs creating it inline different?

Second, why did you close this issue?  This worked in 1.21 and doesn't work in current versions.

**Comment by rliesenfeld** [comment]
It's not different, because you only one subclass of `MockUp`. However, if you copy & paste that code twice into the test method, then you have two different `MockUp` subclasses.
