### ISSUE TITLE
JMockit runner is not used

### ISSUE THREAD

**Issue by maor11** [jmockit/jmockit1#565]
Please provide the following information:

* Version of JMockit that was used: 
1.43

* Description of the problem:
Getting: java.lang.Exception: Method test should have no parameters.
Seems like it's not using the correct runner.
I'm not sure where is the source of the problem because I had to upgrade a few components of the project simultaneously.
Was using Intellij IDEA 2018.1.5, Java 1.8.0_181, JMockit 1.19 with no problem.
Upgraded to Intellij IDEA 2018.3, Java 11.0.1, JMockit 1.43 and the problem occurs.
We're using junit-4.11.jar and jmockit-1.43.jar appears before it in the classpath.
When adding -javaagent with the jmockit-1.43.jar, the problem doesn't exist.
I also tested the following setups:
IDEA 2018.3, Java 1.8.0_181, JMockit 1.19 - no issues.
IDEA 2018.3, Java 1.8.0_181, JMockit 1.43 - issue exists.

* Check that:

 - [ ] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [x] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [x] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
There is no problem therefore, since use of "-javaagent" is mandatory since JMockit 1.42.

**Comment by maor11** [comment]
Oops, I somehow missed that in the development history page, in my defense I had a lot to read ;)
Can you share some insights as to why this change was made?

**Comment by maor11** [comment]
Nevermind, found it myself: https://github.com/jmockit/jmockit1/issues/546
