### ISSUE TITLE
JMockit 1.44 and Arquillian

### ISSUE THREAD

**Issue by trauchhaupt** [jmockit/jmockit1#566]
* Version of JMockit that was used: 
1.44

* Description of the problem:
Running arquillian based tests (wildfly 14) fails when parts are mocked. The -javaagent is used, and the instrumentation is done in mockit.internal.startup.Startup .  Unfortunately, the tests run within their own detached classloader. The mockit.internal.startup.Startup classes of these classloaders have no instrumentation.
It seems, that #541 already covers the problem. But it was closed.

In former times, we made a workaround using mockit.internal.startup.Startup.initializeIfPossible(). But this method was removed.

Is this scenario a limitation of jmockit?

**Comment by rliesenfeld** [comment]
Arguably, it's a limitation of both JMockit *and* Arquillian. JMockit doesn't do anything regarding the classloader on which tests are running, so IMO it's more a question of Arquillian being a tool which creates a special runtime environment.

On the other hand, JMockit itself supports [integration testing of Java EE applications](http://jmockit.github.io/tutorial/EnterpriseApplications.html). The main difference to Arquillian is that, while the latter does *in-container* test execution (hence the use of a custom classloader), the former does *out-of-container* test execution (ie, regular execution on the default app classloader, similar to using the [Spring TestContext](https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testcontext-framework) for integration tests).

See also: [Difference between Spring TestContext Framework and Jboss Arquillian](https://stackoverflow.com/questions/4922554/difference-between-spring-testcontext-framework-and-jboss-arquillian).
