### ISSUE TITLE
What else will be @Deprecated in the future?

### ISSUE THREAD

**Issue by wellar** [jmockit/jmockit1#574]
I got to know jMockit a couple of years ago and I remember that on its website it was announced as a "mock-anything-mocking-tool". After testing I found the characterization correct because the possibilities where vast. Unfortunately, since then, lots of functions have been marked deprecated and removed from it, also several functions that I used. Many functions have been removed just in the next version following the version where they have been deprecated. For some of the removed methods there wasn't an alternative option. Apparently this removal of functions still goes on - looking at the Release Notes this week I noticed the intent to disallow @Mock-methods that target private methods or constructors in version 1.45. And again many users (including me) have to adjust their code. As I have seen, today, jMockit doesn't present itself as a "mock-anything-tool" anymore. I don't know what concept the library-planners actually pursue but I personally find this ongoing removal of functions and methods not very user-friendly. This doesn't give a very reliable impression and also doesn't fit to the original intent of the library that was announced in the past.

**Comment by rliesenfeld** [comment]
The only part of the API that's still going to be deprecated is the `Deencapsulation` class; probably nothing more.
