### ISSUE TITLE
ExceptionInInitializerError 1.45 with Java 11

### ISSUE THREAD

**Issue by mgcos1231** [jmockit/jmockit1#575]
Please provide the following information:

* Version of JMockit that was used: 1.45

* Java Version 
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

* Description of the problem:
When I run a "mvn test" with Open Jdk 11. I get an error message. The Code works find with Oracle JDK 8.

Test Code
```
        new MockUp<ApplicationConfig>() {
            @Mock public List<String> getVerifiedHostname() {
                return Arrays.asList("localhost", "www.google.com");
            }
        };
```
Error Message
java.lang.ExceptionInInitializerError: null
        at mockit.internal.startup.Startup.verifyInitialization(Startup.java:91)
        at mockit.MockUp.<clinit>(MockUp.java:55)

* Check that:

 - [ ] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [x ] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [x ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
What is this `ApplicationConfig` class?

**Comment by mgcos1231** [comment]
Hi, 
It is a Singleton Class for reading a properties and return to a List. 
public List<String> getVerifiedHostname() {
        return getStringList(VERIFIED_HOSTNAME);
    }
