### ISSUE TITLE
JMockit, JRE Fakes

### ISSUE THREAD

**Issue by teoDev** [jmockit/jmockit1#577]
Hello All.
I have a question.
Does JMockit support faking JRE Classes like "java.lang.Thread"
`public static class MockThread extends MockUp<Thread>`

I can find information about mocking of these classes is not allowed:
https://github.com/jmockit/jmockit1/commit/72ed4d01a92ae15b74b4568ec7a7deeeca6ae361#diff-e18cad0b1fbee4ff92d7dd52d9526e25

And the proper message is displayed:

> Class java.lang.Thread is not mockable

But is it the same thing about Fakes ?

Best regards.

**Comment by rliesenfeld** [comment]
Yes, `Thread` can be faked. It may eventually become "unfakeable", if a reason for that becomes known.
