### ISSUE TITLE
VerifyError when mocking In/OutputStreams in IBM JDK 8

### ISSUE THREAD

**Issue by dgeissl** [jmockit/jmockit1#580]
* Version of JMockit that was used:  1.44

* Description of the problem:

We want to update from jmockit 1.24 to 1.44. Now mocking `java.io.InputStream` or `java.io.OutputStream` leads to `java.lang.VerifyError`. We need to run the tests on a IBM JDK, local tests with oracle seem to work.

* Example:

```
public class JMockitTest {

    @Mocked
    OutputStream os;

    @Test
    public void doSmth() {

    }
}
```
With IBM JDK we get a VerificationError
* java.runtime.name=Java(TM) SE Runtime Environment
* java.vm.vendor=IBM Corporation
* java.vm.name=IBM J9 VM
* java.vm.specification.name=Java Virtual Machine Specification
* java.runtime.version=pwa6480sr3-20160428_01 (SR3)
* java.fullversion=JRE 1.8.0 IBM J9 2.8 Windows 10 amd64-64 Compressed References 20160427_301573 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160427_1620_B301573
JIT  - tr.r14.java.green_20160329_114288
GC   - R28_Java8_SR3_20160427_1620_B301573_CMPRSS
J9CL - 20160427_301573
* java.vm.specification.vendor=Oracle Corporation
* java.vm.specification.version=1.8
* sun.arch.data.model=64
* java.vendor=IBM Corporation
* com.ibm.packed.version=2
* java.compiler=j9jit28

This JDK is part of the IBM WebSphere Application Server 9.0 FP8

With a Oracle JDK the test is working:
* java.vm.version=25.172-b11
* java.vm.vendor=Oracle Corporation
* java.vm.name=Java HotSpot(TM) 64-Bit Server VM
* java.runtime.version=1.8.0_172-b11

**Comment by rliesenfeld** [comment]
The IBM J9 JDK has always been unreliable... And combined with the fact that IBM makes it quite difficult for people to get a JDK distribution, I don't see what I should or could do about the issue.

Also, there is a good chance there is nothing to be done on JMockit's side anyway, since the problem doesn't occur with any of the Oracle/OpenJDK versions.

**Comment by dgeissl** [comment]
Thats very unfortunate as we'd like to test everything in the same runtime as in production but also like the features of jmockit. I know getting hands on the IBM JDK is not easy, but what you basically say is: running jmockit on IBM J9 can break anytime, anywhere without a chance to get fixes, right?

**Comment by rliesenfeld** [comment]
Yes. I believe this is an issue that should be reported to the J9 JDK maintainers.
