### ISSUE TITLE
How to intejct different fields with the same type and name (in different objects)?

### ISSUE THREAD

**Issue by robs-nice99** [jmockit/jmockit1#581]
* Version of JMockit: 1.44
* Related to: https://github.com/jmockit/jmockit1/issues/490

I'm testing a method that returns a list of objects in a random order. Since these are complex objects with several null fields, instead of asserting each field, I was trying to instantiate an expected object and compare the both of them. However, some fields are private and I can't set them, since the value is loaded from storage (and loading the correct data meant  instantiating the tested object itself).

According to issue's #490 answer, I should be testing one object in each test. However, here, since the order can change (these are not unit tests), that's doable, but more difficult. Besides I'm testing a single method that returns a list, I would prefer to use a single test. 

So, here's a minimal similar example:

The prod code:
```
public class AnimalsManager {

    List<Mammal> allAnimals;

    AnimalsManager() {
        allAnimals = new ArrayList();
        Cat c = new Cat();
        c.loadData();
        allAnimals.add(c);
        Dog d = new Dog();
        d.loadData();
        allAnimals.add(d);
    }

    public List<Mammal> getAllAnimals() {
        return allAnimals;
    }
}

class Mammal {
    String id;
    public String getId() {
        return this.id;
    }

    @Override public boolean equals(final Object obj) {
        return id.equals(((Mammal) obj).id);
    }
}


class Cat extends Mammal {

    public void loadData() {
        id = "1234-1234-1234-1234";
    }

    @Override public String toString() {
        return "Cat{id=" + id + '}';
    }
}

class Dog extends Mammal{

    public void loadData() {
        id = "4567-4567-4567-4567";
    }

    @Override public String toString() {
        return "Dog{id='" + id + '}';
    }
}
``` 

And the test code:
```
public class AnimalsManagerTest {

    @Test
    public void testGetAllAnimals(@Injectable(value="1234-1234-1234-1234") String id,
                                  @Tested final Cat c,
                                  @Injectable(value="4567-4567-4567-4567") String id2,
                                  @Tested final Dog d
    ) {
        final AnimalsManager animalsManager = new AnimalsManager();

        assertThat(animalsManager.getAllAnimals()).contains(c,d);
    }
}
```
Thanks for your help in advance!

**Comment by rliesenfeld** [comment]
Injection into `@Tested` objects is done one such object at a time, independently of one another (except for previously declared `@Tested` objects that can be injected into the tested object being currently injected - which is not the case here). So, there is no way to inject a given `@Injectable` into one `@Tested` object, and then another `@Injectable` of the same type into another `@Tested` object.

In this case, however, looking at the code under test I can only see two things that can possibly be tested: 1) that both a `Cat` and a `Dog` are added into the list of mammals; and 2) that each added mammal has its data loaded (here, only an "id"). I would write such a test as follows:

```
public class AnimalsManagerTest {
   @Test
   public void loadCatAndDog() {
      List<Mammal> allAnimals = new AnimalsManager().getAllAnimals();

      assertMammalWithLoadedData(allAnimals, Cat.class);
      assertMammalWithLoadedData(allAnimals, Dog.class);
   }

   void assertMammalWithLoadedData(List<Mammal> mammals, Class<? extends Mammal> expectedType) {
      for (Mammal mammal : mammals) {
         if (mammal.getClass() == expectedType) {
            assertNotNull("Data not loaded into " + mammal, mammal.getId());
            return;
         }
      }

      fail(expectedType + " not added");
   }
}
```

**Comment by robs-nice99** [comment]
ok. Thanks for you input!
