### ISSUE TITLE
Mocking a method of abstract superclass in the subclass does not return mocked instance

### ISSUE THREAD

**Issue by abhijith-gururaj** [jmockit/jmockit1#584]
* Version of JMockit that was used: 1.44

* Description of the problem:
Mocking the methods of **abstract super class** from the subclass using Expectations(SuperClass.class){{...}} does not give a mocked instance when it is invoked. 

Note: The method to be mocked is declared and defined in the super class itself. I am trying to invoke the method from the sub class.

JDK: jdk1.8.0_172

Example for reproducing the issue: 
```
public abstract class TempClass {

    private String testString;
    private int testInt;


    public TempClass getTempClass(){
        return  new TempClass() {
            @Override
            public String toString() {
                return "Real";
            }
        };
    }

    public String getTestString() {
        return "lulz";
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    public int getTestInt() {
        return testInt;
    }

    public void setTestInt(int testInt) {
        this.testInt = testInt;
    }
}
```

```
    public class TempClassTwo extends TempClass {

    @Override
    public void setTestString(String testString) {
        super.setTestString(testString);
    }

    @Override
    public int getTestInt() {
        return 2;
    }

    @Override
    public void setTestInt(int testInt) {
        super.setTestInt(testInt);
    }
}
```

```
public class JMockitPartialMockTest {

    @Test
    public void testJmockit(){
        TempClassTwo tempClassTwo = new TempClassTwo();

        new Expectations(TempClass.class){
            {
                tempClassTwo.getTempClass();
                times = 1;
            }
        };

        doTest(tempClassTwo);
    }


    private static void doTest(TempClassTwo tempClass) {
        TempClass clazz = tempClass.getTempClass();
        System.out.println("TestList: " + clazz);
    }
}
```

If you run the test in 1.44 vs 1.14, you can see that the clazz object in v1.14 is a mocked impl of TempClass (the super class) where as in the v1.44 you notice that the clazz object is the same TempClassTwo object which was used to invoke the method. 

Please refer to the screenshots for better understanding.

![jmockit_1 44_abstractmockissue](https://user-images.githubusercontent.com/7941660/52777032-ea785f00-3068-11e9-97cb-a5e95590176f.PNG)
![jmockit_older_worksasexpected](https://user-images.githubusercontent.com/7941660/52777034-ea785f00-3068-11e9-9578-53df43165c87.PNG)

**Comment by rliesenfeld** [comment]
Yes, it returns the `tempClassTwo` unmocked instance. If you need a mocked instance to be returned from `getTempClass()`, then record it in the expectations block. To get such a mocked instance, use `@Mocked` or `@Injectable`.

**Comment by abhijith-gururaj** [comment]
Okay, then why is it that the v1.14 returns a mocked implementation while v1.44 doesn't?

Our tests were written around the results based on v1.14. They are now failing when we upgrade to the latest version.
