### ISSUE TITLE
Having problems with jmockit 1.45 and Junit 5.4

### ISSUE THREAD

**Issue by ramses-gomez** [jmockit/jmockit1#585]
I just upgraded to the latest version of jmockit (1.45) and jUnit (5.4.0) and all the sudden all test were failing with a null pointer exception I checked and none of the objects injected by jmockit using annotations @Tested, @Injected and @Mocked were being created, they were all null hence the null pointer exception I downgraded JUnit back to 5.3..2 and everything was working again.

Any suggestion with this?

**Comment by sbrannen** [comment]
As I explained in https://github.com/junit-team/junit5/issues/1792#issuecomment-466762498, the `JMockitInitialization` class does not properly register JMockit's `FakeExtensionRegistry` which in turn never gets a chance to register the `JMockitExtension`.

Thus, JMockit's support for JUnit Jupiter simply never gets registered when using JUnit Jupiter 5.4+.

In https://github.com/junit-team/junit5/issues/1792#issuecomment-466762498, I also outlined a workaround that works but is rather intrusive.

**Comment by rliesenfeld** [comment]
It's already fixed...
