### ISSUE TITLE
Having problems returning a List from a Mock

### ISSUE THREAD

**Issue by ramses-gomez** [jmockit/jmockit1#587]
Using version 1.45
I have this:

`new Expectations {{
      object.getList(); result = new ArrayList();
}}`

But I'm getting the error: java.lang.IllegalArgumentException: java.util.List is not mockable

I know in version 1.45 you can not longer Mock Lists but this is not the case.

Any help?

**Comment by rliesenfeld** [comment]
Works fine for me:
```
   static class AClass { List<?> getList() { return null; }}

   @Test
   public void mockMethodWhichReturnsAList(@Mocked final AClass object) {
      new Expectations() {{ object.getList(); result = new ArrayList(); }};

      List<?> result = object.getList();

      assertTrue(result.isEmpty());
   }
```

**Comment by ramses-gomez** [comment]
sorry I thought that returning a List will do but it is a bit more complex:

`interface IList<C> extends List<C> {}

    static class ClassA {
        IList<?> getList() {
            return null;
        }
    }

    @Test
    public void test(@Mocked ClassA classA) {
        new Expectations() {{
            classA.getList(); result=null;
        }};
    }`
