### ISSUE TITLE
Expectations broken - class variables are being instantiated. (Initilization failure)

### ISSUE THREAD

**Issue by 7--** [jmockit/jmockit1#591]
* Version of JMockit that was used: 
1.28
* Description of the problem:
When you put a method in Expectations it calls the class variables of the method. This is not needed and can cause errors. All it should do is give the result, not execute any part of it. This is the code to reproduce the issue:

```
public class ExampleTest {
   @Tested ServiceAbc tested;

   @Test
   public void doOperationAbc(@Mocked AnotherDependency anyInstance) {
      new Expectations() {{
    	  AnotherDependency.nothing(); result = null;
      }};
      tested.doOperationAbc("some data");
   }
}
```

```
public class AnotherDependency {

	private static Object object = returnObject();
	
	public static void nothing(){
	}

	private static Object returnObject()  {
		return 1/0;
	}
}
```

```
public class ServiceAbc {
	public void doOperationAbc(String string) {
		AnotherDependency.nothing();
	}
}

```
Instead of returning null for nothing() mockit is throwing an error at` private static Object object = returnObject(); `I don't see any reason why this class variable is instantiated. I thought the point of expectations was to get a mock result when you're not able to call the method directly. 

* Check that:

 - [x] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [x] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [x] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
Use of `Expectations` here has nothing to do with the failure; if the expectation block is removed entirely from the test, it still fails with the same exception.

Maybe the real problem is the class being mocked shouldn't fail during static initialization...

**Comment by 7--** [comment]
What's the point of Expectations then? I could just feed it values to get the output I want. How am I suppose to write unit tests? I'm not trying to setup DB or log configurations for every dependency.

**Comment by 7--** [comment]
What's the point of Expectations then? I could just feed it values to get the output I want. How am I suppose to write unit tests? When I comment the class variable out it passes, even if there's an error in the method we wrote an Expectation for:
public class AnotherDependency {

	//private static Object object = returnObject();
	
	public static void nothing(){
		int i = 1/0;
	}

	private static Object returnObject()  {
		return 1/0;
	}
}

Why does it work in nothing(), but throws error if it's in the class variable?

**Comment by rliesenfeld** [comment]
The Tutorial should help, it has some example tests.

**Comment by 7--** [comment]
Hows that going to help. Expectations doesn't work.

**Comment by 7--** [comment]
You should reopen this.
