### ISSUE TITLE
Automatic teardown does not appear to teardown static mocks

### ISSUE THREAD

**Issue by ctash** [jmockit/jmockit1#594]
* Version of JMockit that was used: 1.45

* Description of the problem:
Mocked static methods persist for the entire test run. They are not cleared out between tests or between test classes as expected. In my example code ([available here](https://github.com/ctash/jmockit-static-teardown-issue)), the 3rd test in AppTest and the test in AppTestTwo will fail if one runs `gradlew test`.

    This is because the 2nd test in AppTest mocks a static method called in all 4 tests.

* Check that:

 - [X] The problem can be reproduced by JMockit project members.
sample code exhibiting the problem included above

 - [X] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [X] The JDK where the problem occurs is a final release, not a development build.
Currently using 1.8.0_202

**Comment by rliesenfeld** [comment]
Same as #585.
