### ISSUE TITLE
Wrong Expectations

### ISSUE THREAD

**Issue by yfcz** [jmockit/jmockit1#599]
* Version of JMockit that was used: 1.43 (+ TestNG 6.11, JRE 1.8.0_131 JCE)

* Description of the problem: Sometimes test mentioned below fails due to MissingInvocation error. It says there is missing invocation but such invocation was not recorded/expected. (see Expectations block below) 

Test which fails looks like this:
`class TestClass {

	@Test
	void fileTest() {

		final Set<String> images = new LinkedHashSet<>();
		final String imageUuid = "11111111-1111-1111-1111-111111111111";
		images.add(imageUuid);
		images.add(UUID.randomUUID().toString());

		val testedClass = new TestedClass();
		
		final File file = new File("mocked/");
		new Expectations(File.class) {
			{
				file.list();
				result = images.toArray(images.size());
			}
		};

		val result = testedClass.testedMethod(); // this method calls this: File folder = new File("/opt/something/else/"); String[] files = folder.list();
		Assert.assertEquals(result, expected);
	}
}`

Sometimes such test fails with:
Error Message
Missing 1 invocation to:
java.io.File#File("/usr/bin/ps")
   on mock instance: java.io.File@6f84b198
instead got:
java.io.File#File("/opt/something/else")
   on mock instance: java.io.File@1490b1a4
 at java.io.File.<init>(File.java)
 ...
 ...

Stacktrace
mockit.internal.expectations.invocation.MissingInvocation: 
Missing 1 invocation to:
java.io.File#File("/usr/bin/ps")
   on mock instance: java.io.File@6f84b198
instead got:
java.io.File#File("/opt/something/else")
   on mock instance: java.io.File@1490b1a4
	at java.io.File.<init>(File.java)
	...
 	...
Caused by: mockit.internal.expectations.invocation.ExpectationError

**Do you have advice how to avoid mentioned random failure?**

**Comment by rliesenfeld** [comment]
No idea...
Advice: don't mock the `File` class.
