### ISSUE TITLE
Question: Static Mock Objects

### ISSUE THREAD

**Issue by archer920** [jmockit/jmockit1#602]
Please provide the following information:

* Version of JMockit that was used: 1.46
Junit 5.4.2
Java 1.8

* Description of the problem:
JUnit 5 has parameter methods that have to be run from the static context. I don't see any documentation in JMockit that allows for static mocked objects and I tried setting up a test to try and see if I could successfully mock a static object.

Here is an example of what I would like to do:
`
import mockit.Mocked;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.params.provider.Arguments.arguments;

class Pojo{}

public class StaticMocking {

    //Would like it to be possible to Mock objects from the static context
    //so that these objects can be used in parameter methods
    @Mocked
    private static Pojo pojo;

    //Junit 5 Parameter method
    static Stream<Arguments> argumentsStream() {
        return Stream.of(
                arguments(pojo)
        );
    }

    @ParameterizedTest
    @MethodSource("argumentsStream")
    void testPojo(final Pojo pojo){
        assertNotNull(pojo, "Would be nice if this isn't null");
    }
}
`
Is there a way to mock the Pojo object from the static context or can we request a feature for a future version of the library? Thank you!

* Check that:

 - [ ] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
A new feature would require a convincing use case demonstration. I don't see one.

**Comment by archer920** [comment]
@rliesenfeld 

Please take a look at my example code above. The use case would be to use mocked objects inside of parameter methods. Since such methods have to be in the static context, we would need the ability to mock objects in the static context as well.

**Comment by rliesenfeld** [comment]
I don't see anything remotely close to a "convincing use case". If you have a `Pojo` class, then why not instantiate it directly? Not seeing any reason to mock it.
