### ISSUE TITLE
Unable to Mock non-public abstract classes using @Capturing

### ISSUE THREAD

**Issue by harish-prakash** [jmockit/jmockit1#604]
## Unable to Mock non-public abstract classes using @Capturing
I should be able to Mock a solid class by @Capturing its abstract class. I encounter the following error when I do this for a non-public abstract class.
> java.lang.IllegalAccessError: class org.sandbox.$Subclass_TheAbstractClass_mockTheAbstractClass cannot access its abstract superclass org.sandbox.TheAbstractClass (org.sandbox.$Subclass_TheAbstractClass_mockTheAbstractClass is in unnamed module of loader mockit.internal.classGeneration.ImplementationClass$1 @479d31f3; org.sandbox.TheAbstractClass is in unnamed module of loader 'app')

**TheAbstractClass**

    abstract class TheAbstractClass {
        private int value;
        
        protected TheAbstractClass(int value) {
            this.value = value;
        }
    
        public int getValue() {
            return value;
        }
    }
**TheImplClass**

    public class TheImplClass extends TheAbstractClass{
    
        public TheImplClass(int value) {
            super(value);
        }
    }
**TheClassUnderTest**

    public class TheClassUnderTest {
        
        public int TheTestMethod() {
            
            TheImplClass container = new TheImplClass(7);
            return container.getValue();
        }
    }
**TheTestClass**

    public class TheTestClass {
    
        @Tested
        private TheClassUnderTest tested;
        
        @Capturing
        private TheAbstractClass mockTheAbstractClass;
        
        @Test
        public void TheTestMethod_JustRun_GetProperMocks() {
            
            int EXPECTED_RESULT = 12;
            new Expectations() {{
                mockTheAbstractClass.getValue(); result = EXPECTED_RESULT;
            }};
            
            int value = tested.TheTestMethod();
            assertEquals(EXPECTED_RESULT, value);
        }
    }
## Other Information
* **JMockIt Version:** 1.43
* **JDK Version:** 11

**Comment by rliesenfeld** [comment]
Yes, this happens because the JVM does not allow access to a package-private class from a subclass, when the subclass is defined in a different classloader, even if the package is the same.

I don't consider it a real problem, because such a situation has never arisen in practice. Normally, abstract classes are public. And even if it has a good reason to be package-private, you know what the actual subclasses are, since they must be defined in the same package, so they can be mocked directly instead of using `@Capturing`.

**Comment by harish-prakash** [comment]
Would it be useful to render an appropriate error message?
