### ISSUE TITLE
Please reconsider to not remove support for mocking private methods

### ISSUE THREAD

**Issue by ickzon** [jmockit/jmockit1#605]
Hi everyone,

first, thanks a lot for providing JMockit! We are using it for almost 10 years now (since version 0.9x) and never encountered serious problems. It has always been the swiss knife we needed for testing (and even use it for a few other things). But your latest changes are causing some headaches so please forgive the long text below…

Currently I’m porting our product (a universal integration server) to Java 11 and upgraded our test environment to the latest JMockit 1.46. The good news: Coming from version 1.34, most of the latest changes to JMockit haven’t caused much trouble.

But I noticed that faking of private methods is now discouraged and scheduled to be disallowed in one of the next releases and I would really ask you to reconsider this decition! More than 600 of our ~10k tests are currently faking private methods and most of them cannot be refactored easily - and in many cases I don’t even see any way to adapt them at all. I read through #312, so just let me give one or two examples where we use this feature:

1. Simulation of infrastructure failures
Since our product is mission-critical in almost all use cases, we have to handle unexpected infrastructure failures such as power loss, network failure, JVM crash, and such. Many of the recovery tests use one (or a set of) fake(s) to completely/partly disable I/O at some point, restart the system and monitor the recovery process/check the recovered state. We theoretically could refactor larger parts of our system to avoid faking of own private methods but I really don’t see how we could avoid fakes for foreign code. We use about 120 foreign libraries, therefore modifying most/many of them is no option.
 
2. Timing sensitive tests (e.g. we have a number of regression tests for very subtle race conditions/deadlock situations)
Mostly for testing complex modules in a multi-threading environment, timing may become a critical factor. Currently we often use appropriate fakes to gain fine-grained control over critical parts of the code. This is often possible by only faking public methods but sometimes requires to intercept private methods, as well. I don’t see a way we could completely avoid fakes for private methods here, given we want to maintain a clear system architecture and taking into account that some parts of the system heavily depend on foreign code.

3. System tests/complex module tests
Some of our tests start large parts of the product but fake a few central classes to either disable/replace functionality or provide dummy data (e.g. because resources are not available in the test environment or to greatly reduce test time). While we might indeed be able to adapt a lot of those test cases by refactoring the product, some cases cannot be covered easily/at all and the complexity of the product and the tests would increase dramatically. I don’t see any benefit of trading the current ability of faking private methods for a much larger test and much higher complexity.

I know that all oft he above is a bit imprecise. If you even consider my concern worth a discussion, I think I could certainly isolate a few test cases and provide concrete example code. Just drop me a line…

If you are sure about removing support for faking private methods, maybe you could give the reasons for that? Beside the more or less academical approach ("faking/testing private methods is bad")  I just don’t see what motivates you. Surely you wouldn’t remove such a powerful and important feature without good reasons, right?

Cheers,
momo

**Comment by rliesenfeld** [comment]
The main motivation to remove it is having seen, over the years, how easily inexperienced programmers will make use of the ability to mock/fake a private method, just to get a test to pass. Usually, these programmers are not trying to write a proper, meaningful test, but just after something they can claim to be a test. Unfortunately, many people don't seem to understand concepts like TDD, or even what an automated developer test is supposed to be. In my day to day, I use JMockit all the time, but rarely mock or fake anything, much less private implementation details.

So, even if rare cases exist where a private fake would be useful (but that is not clear, since you can always fake the public method which calls the private one), it doesn't seem to justify keeping a feature that is much more often abused than not.

**Comment by ickzon** [comment]
Wow, that was fast :-) Thank you for the clearification!

Okay, so essentially you are trying to prevent (inexperienced) programmers from writing bad tests? There is no other, e.g. technical reason behind that? Well, at least in my experience, such attempt is somewhat futile. We had a lot of experienced developers (at least in terms of years of using Java) in out test team who wrote all kind of stupid, meaningless tests. If someone isn’t able to design a meaningful test, he or she will always mess up things, no matter what tools you give them. More often than not, they created tests that basically tested itself or tested something not even related to the class/component to be tested. But I cannot remember a single case where mocking of internals has been the problem or has even been used in such an absurd test. The most common problem, at least for us, has always been that tests are designed for the actual behavior of the tested class/component, instead of testing the desired/documented behavior (and that tests are incomplete of course, e.g. don’t test relevant corner cases).

Since you didn’t immediately close this ticket I assume you may be willing to further discuss this topic and maybe even re-consider your decision? I still haven’t lost all hope ;-)

Just let me add a few points:

Concerning TDD: While I completely agree that this is an absolute requirement (especially in our case), we cannot always avoid using foreign code. Unfortunately, the nature of our product even requires us to use a lot of external libraries we sometimes have absolutely no control of (some are actually closed source). Nevertheless, to ensure robustness of the whole product or certain parts of it, we indeed have to mess with the internals of external libraries. In some cases we mock external classes essentially for testing parts of our own code (I suppose that are the cases we could, at least to a certain degree, avoid mocking private methods, but at the costs of greatly increased size/complexity of some tests), in other cases we are actually directly testing internals of external libraries, mainly to avoid reintroduction of bugs/problems we already had in the past. For example we have tests for libraries that repeatedly re-introduced the same error again and again over the years and we have to ensure we can safely update to a new version without immediately running into the same problem again.

Concerning your statement "you can always fake the public method which calls the private one": I cannot fully aggree with you here. You surely can create tests for the public API of a single class, but as things are getting complex enough, this may not be fully sufficient anymore. I just think of module tests involving a larger number of classes, multi-threading, I/O and such things. What if you have a class thats public methods are called by multiple threads concurrently and you want to create a regression test for a race condition/dead-lock indirectly caused by calls to its internal methods? How do you get the timing correct to really test for the bug you want to test for? You wouldn’t really want to expose a classes internals just to allow such tests, would you? And I cannot imagine to only use a brute force approach for testing multi-threading robustness, this simply is way  too unstable (and too slow, of course). Apropos, what about performance? Just imagine you have a class that maintains an internal state indirectly created/modified by private methods called by its public methods. In some of our tests it would take minutes (or even hours in some rare cases, think of it as creating a multi GB/TB data base - and in some cases it is exactly this) to create the internal state by just using the public API that is required to run a test that itself only takes a few milliseconds or seconds. Our test suite would run for weeks instead of ~40 hours after the corresponding changes…

Concerning your statement "I use JMockit all the time, but rarely mock or fake anything": Simply put, we literally don’t use JMockit for anything else ;-) Currently, what we need is provided by JMockit’s mocking/faking facilities and TestNG. Anything else is plain Java code…

Okay, I think that should be enough for the time being.  Please let me know what you think! Is there any chance you could re-consider your decision? Anything I can do to convince you?

Cheers,
momo

**Comment by rliesenfeld** [comment]
I am not seeing anything that indicates the faking of private methods was done for good reasons. Of course, such reasons may exist, but there is nothing concrete here, and nothing new to me.

**Comment by nlmarco** [comment]
Your decision totally sucks. Just because there are bad ways of using it doesn't justify to remove a feature. Especially, there are people like me using jmockit in a hobby project and I really don't have the time to refactor heaps of tests!

If I need to refactor, I'm going to kick jmockit out. Your decision is insane!
