### ISSUE TITLE
@Mocked field is not initialized inside JUnit 5 @Nested class

### ISSUE THREAD

**Issue by andreoss** [jmockit/jmockit1#606]
* Version of JMockit that was used: 
1.46
* Description of the problem:
@Mocked field is not initialized inside nested test-class

```
class MockedNestedTest {
    @Nested
    class Field {
        @Mocked Foo foo;
        @Test
        void shouldInitializeField() {
            Assertions.assertNotNull(foo); // this fails
        }
    }
```

See https://github.com/andreoss/junit5-jmockit-issue

**Comment by rliesenfeld** [comment]
Correct, mock fields are only supported in regular test classes.

**Comment by andreoss** [comment]
I haven't found any mention of this in the documentation.
What causes such limitation for nested test classes?
And since mock arguments work inside nested test classes, it's an odd behaviour
I find it's very likely that one may way want to refactor repeated argument mocks as a one mock field.
