### ISSUE TITLE
Coverage tool: add new output format "sonarxml", or create Sonar plugin

### ISSUE THREAD

**Issue by rliesenfeld** [jmockit/jmockit1#61]
For use with the Sonar "Generic Test Coverage" plugin (http://docs.codehaus.org/display/SONAR/Generic+Test+Coverage), which generates an HTML coverage report from a coverage.xml file in its own specific format.

**Comment by maddingo** [comment]
I would like to implement this feature. But it seams now jmockit requires Java 1.8 to run on. Is that correct. I need jmockit to run on Java 1.7

**Comment by rliesenfeld** [comment]
No, JMockit runs on JDK 1.6 or newer.

**Comment by rliesenfeld** [comment]
I don't use Sonar, so this will require contributions from someone else if it is to ever get done.
