### ISSUE TITLE
Mocking implementations of eg java.util.Map

### ISSUE THREAD

**Issue by simonmarshall** [jmockit/jmockit1#610]
jmockit 1.47

First, many thanks for jmockit, it's our primary mocking tool, since it has support for mocking such a wide range of things, from constructors to static methods.  There's always a "however"...

However, I just upgraded from 1.44 and found the change introduced by 1.45 stops certain tests from working.

I have a concrete implementation of java.util.Map that acts as a façade to another class (that itself contains a Map amongst several other things).  The façade, let's call it Foo here, allows me to treat the other class as if a Map in many situations for which it appropriate, providing access to all data in the other class, and of course allows me to use the many Java and 3rd party classes that operate on a Map.

Previously, I could use a @Mocked Foo instance to test other components that use Foo.  Since 1.45, if I provide a mock Foo parameter to a test method, I get the cryptic error:

java.lang.IllegalArgumentException: class Foo is not mockable (mock parameter "bar")

After reading http://jmockit.github.io/changes.html, I'm still struggling to understand the rationale for the 1.45 change.  It mentions that I can no longer mock "Java SE collection and map interfaces", but I'm not mocking an interface, I'm mocking a concrete implementation.  It mentions that they have default methods, but any interface can have default methods.

Please can you explain why I should not be able to mock a concrete implementation of specific interfaces?

**Comment by rliesenfeld** [comment]
Take it as an opportunity to improve the design of the code under test. Creating a class that implements a Map is a known bad practice (unless you really want a custom map implementation different from the standard ones, but this should never be mocked as well, being a "value object"); see Joshua Bloch's book, Effective Java, it has a couple relevant items. Generally, in such a case one should "use composition instead of inheritance"; specifically, `Foo` should *contain* a map, not *be* a map.

**Comment by simonmarshall** [comment]
With respect, it _is_ a reasonable design.  As I alluded to, `Foo` is a façade that ultimately _does_ contain a map, amongst other things, by composition, and the façade is effectively a custom map implementation.  There are specific circumstances where we want to be able to treat both the underlying map and other related things as being part of "a" map (without them actually being in a map as that would _not_ be a good design in this particular situation).  

Implementing `Map` might be a code smell, but it doesn't mean it's _always_ bad design.  Showing the type hierarchy of `Map` in my intellij shows a large number of them from respected communities and organisations from spring to google, including some that look like they are implementing a façade-like role.

I can understand you not liking someone mocking a `Map`, though I'm not sure I would go to the lengths of actively stopping them from doing so, but I'm struggling to understand why (a) you would stop them mocking an _implementation_ of `Map`, and (b) you chose to stop mocking of only those specific interfaces.

**Comment by vishynit** [comment]
@simonmarshall 
Were you able to refactor your test code to make it working? What were your changes?

**Comment by vishynit** [comment]
@rliesenfeld 
My test class is using @Injectable private Properties properties; but getting below error - 
java.lang.IllegalArgumentException: class java.util.Properties is not mockable (mock field "properties")

As mentioned in the release notes  - 
"_In the particular case of having an @Injectable collection/map field which is meant to be injected into a @Tested object, the test should be changed to use @Tested as well on the collection/map field, with its declaration positioned before the target @Tested field._ "

I declared it as @Tested private Properties properties; before my target tested field and getting the following error now - 
java.lang.IllegalStateException: Missing @Injectable for field "java.util.Properties properties"

**Comment by keshin** [comment]
> @rliesenfeld
> My test class is using @Injectable private Properties properties; but getting below error -
> java.lang.IllegalArgumentException: class java.util.Properties is not mockable (mock field "properties")
> 
> As mentioned in the release notes -
> "_In the particular case of having an @Injectable collection/map field which is meant to be injected into a @tested object, the test should be changed to use @tested as well on the collection/map field, with its declaration positioned before the target @tested field._ "
> 
> I declared it as @tested private Properties properties; before my target tested field and getting the following error now -
> java.lang.IllegalStateException: Missing @Injectable for field "java.util.Properties properties"

I'm confused by the release note as well, How can we fix it? change the @Injectable to @Tested doesn't work at all

**Comment by hazemkmammu** [comment]
> > @rliesenfeld
> > My test class is using @Injectable private Properties properties; but getting below error -
> > java.lang.IllegalArgumentException: class java.util.Properties is not mockable (mock field "properties")
> > As mentioned in the release notes -
> > "_In the particular case of having an @Injectable collection/map field which is meant to be injected into a @tested object, the test should be changed to use @tested as well on the collection/map field, with its declaration positioned before the target @tested field._ "
> > I declared it as @tested private Properties properties; before my target tested field and getting the following error now -
> > java.lang.IllegalStateException: Missing @Injectable for field "java.util.Properties properties"
> 
> I'm confused by the release note as well, How can we fix it? change the @Injectable to @tested doesn't work at all

This is a pretty late reply but leaving it anyway in the hope that it might help someone else. Along with @tested on the map field with the declaration positioned before the target @tested field, adding fullyInitialized = true on the target @tested annotation fixed it for me.

**Comment by xd-dw** [comment]
My case:

public class StateOrProvinceFieldBuilderTest {
	@Tested
	StateOrProvinceFieldBuilder stateOrProvinceFieldBuilder;

	@Injectable
	private StateComparator comparator;
}


i get similar error, resolve with below changes:
public class StateOrProvinceFieldBuilderTest {
	
	@Tested
	StateComparator comparator;
	
	@Tested
	StateOrProvinceFieldBuilder stateOrProvinceFieldBuilder;
}
