### ISSUE TITLE
Please return getMockInstance()

### ISSUE THREAD

**Issue by topsy-turvy** [jmockit/jmockit1#612]
Hello,

Regarding https://github.com/jmockit/jmockit1/issues/563 and getMockInstance(). This method was very simple and helpful and I don't agree "it's never been used by anyone". Creating real instances clutters your code by implementing methods you don't really need. For example Apache HttpClient requires you to implement 10 methods. There are interfaces that require more. Of course you can create separate test class. But then you need it to return different results and you start to pass it as parameter to this class. Then the other person supporting your code have to look into the class and understand how it works. Instead of just having compact visible straightforward test you start building kind of infrastructure behind it.

If getMockInstance() is not difficult to support you would be a life saver if return it. I hope other users will join my request

Best regards,
Yet Another JMockit Fan.

**Comment by rliesenfeld** [comment]
Without a realistic example, there is nothing to discuss...
