### ISSUE TITLE
JMockit on Java 12

### ISSUE THREAD

**Issue by tcfurrer** [jmockit/jmockit1#613]
Has JMockit been tested against Java 12?

Does the work done on #534 also enable Java 12, or does more work need to be done for Java 12 compatibility checking?

My project has managed to successfully run at least one test with OpenJDK 12 and a recent JMockit release.  But that doesn't mean if we continued to use it, we wouldn't discover compatibility issues.  For those of us who remain on the cutting edge of Java, it would be nice to get some clarification about whether JMockit is a realistic option for us currently.

**Comment by willforevercn** [comment]
I have the same question for JMockit. Anyone could help answer it?

**Comment by rliesenfeld** [comment]
It's not tested on Java 12 yet.

**Comment by willforevercn** [comment]
got it, thanks!

**Comment by rliesenfeld** [comment]
JMockit 1.46 has been tested on JDK 12.0.1 now; no test failures occurred.
