### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid conditional statement inside expectation block in Verifications block

### ISSUE THREAD

**Issue by salilsurendran** [jmockit/jmockit1#614]
Please provide the following information:

* Version of JMockit that was used:  1.18

* Description of the problem or enhancement request:
I understand that conditionals can't be used within the Expectations block but I am unable to use it in a Verifications block either:

I get a java.lang.IllegalArgumentException: Invalid conditional statement inside expectation block at a line like this

new Verifications(){
{
Assert.assertTrue(
            list
                .stream()
                .**filter**(
                    a ->
                        a.name()
                                .equals("B0000")
                            && a.getScore().equals(0.37128)).count() == 1);
}
}

new Verifications(){
{
Assert.assertTrue(
            list
                .stream()
                .**matchAny**(
                    a ->
                        a.name()
                                .equals("B0000")
                            && a.getScore().equals(0.37128));
}
}

* Check the following:

 - [x] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [x] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [x] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
A `new Verifications() {...}` block is an expectation *verification* block, while a `new Expectations() {...}` block is an expectation *recording* block. They both are expectation blocks, and the same rules apply.

**Comment by salilsurendran** [comment]
Many of the times the methods that we test may not return back results in a fixed order. So one of the ways to test this was to use use for loops in the Verifications blocks and ensure that the results that you expect are present in the returned list.

new Verifications(){
{
 List<Integer> intList = new ArrayList<>();
// I expect the list to contain 1,2,3 but may not be in that order
 mockedClass.save(withCapture(intList));
Integer[] expectedResults = new Integer[]{1,2,3};

for(Integer i:intList)
    Arrays.stream(expectedResults).anyMatch(e -> e.equals(i)

}
}

What is the alternative way of testing such scenarios presently allowed in the Verifications block?

**Comment by rliesenfeld** [comment]
Simply move the assertion outside the verification block.
