### ISSUE TITLE
Regression: JMockit does not support JUnit Jupiter 5.5

### ISSUE THREAD

**Issue by sbrannen** [jmockit/jmockit1#619]
## Overview

This was brought to my attention in https://github.com/junit-team/junit5/issues/1938.

The root cause is the same as in #585. 

As I mentioned in https://github.com/jmockit/jmockit1/commit/7cb53e00b1873efcd8b49c4304e80090964d5b30#r32463129,

> if the JUnit team decides to change the internal implementation of `ExtensionRegistry` in JUnit 5.5 (which it is at liberty to do), JMockit would then only work with the 5.4.x releases of JUnit Jupiter.

This is now the case due to https://github.com/junit-team/junit5/commit/932ff166f2f8523e8afd932d61ae3d8f647ee998.

Please note that continuing to rely on unsupported internals of JUnit Jupiter will likely lead to conflicts with new versions of JUnit Jupiter.

**Comment by sbrannen** [comment]
Thanks for the quick turnaround on this issue!

**Comment by AlvaHenrik** [comment]
Many thanks to both of you for addressing this so fast!
