### ISSUE TITLE
The published sources jar does not appear to contain correct sources

### ISSUE THREAD

**Issue by lstreepy** [jmockit/jmockit1#620]
Please provide the following information:

* Version of JMockit that was used: 1.46 and 1.47

* Description of the problem or enhancement request:
I am comparing the sources contained in the published sources jar and the code in the jmockit1 gihub repo, and they do not seem to correlate.  I also see no tags on the source repo to exactly determine which revisions are the basis for which release.  But, just going by modification and publication dates should be close enough.  The code differences are significant.

As an example, the RecordAndReplayExecution#recordOrReplay in the jmockit1 code repo has the following initial code:
```java
   public static Object recordOrReplay(
      @Nullable Object mock, int mockAccess, @Nonnull String classDesc, @Nonnull String mockDesc, @Nullable String genericSignature,
      int executionModeOrdinal, @Nullable Object[] args
   ) throws Throwable {
      if (calledFromSpecialThread()) {
         return proceedIntoRealImplementationOrGetDefaultReturnType(mock, mockAccess, mockDesc, genericSignature);
      }

      if (args == null) {
         //noinspection AssignmentToMethodParameter
         args = NO_ARGS;
      }

      ExecutionMode executionMode = ExecutionMode.values()[executionModeOrdinal];
```
While the code from the published sources jar (as downloaded by IntelliJ) looks like this:
```java
   public static Object recordOrReplay(
      @Nullable Object mock, int mockAccess, @Nonnull String classDesc, @Nonnull String mockDesc, @Nullable String genericSignature,
      int executionModeOrdinal, @Nullable Object[] args
   ) throws Throwable {
      if (args == null) {
         //noinspection AssignmentToMethodParameter
         args = NO_ARGS;
      }

      ExecutionMode executionMode = ExecutionMode.values()[executionModeOrdinal];
```
Note the lack of the block handling `if (calledFromSpecialThread())`

Can you please verify that the published sources are in sync with the repo?  Or, help me to figure out which code to "trust"?  I am trying to debug an issue and without accurate sources, it is proving difficult.

Thanks.

**Comment by rliesenfeld** [comment]
No, that first version of "recordOrReplay" is not what's in the github jmockit1 repo:

https://github.com/jmockit/jmockit1/blob/master/main/src/mockit/internal/expectations/RecordAndReplayExecution.java

And the sources published in the jmockit-1.xy-sources.jar on Maven Central are all correct, as far as I can see.

**Comment by lstreepy** [comment]
Sorry, not sure how, but my git repo was out of date.  Apologies.  But, I'm trying to track down why Expectations are not apparently executing properly on the EDT.  I will post another ticket if/when I figure out what is going wrong.

Again, thanks for the rapid response.
