### ISSUE TITLE
Mockit.Invocation parameter in the mocked method causes java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by vgavinash** [jmockit/jmockit1#622]
Please provide the following information:

* Version of JMockit that was used: jmockit-1.6.jar

* Description of the problem or enhancement request: When I try to mock the classes of a standard java api using the Invocation object, I am getting the error "java.lang.IllegalArgumentException: wrong number of arguments". Kindly help. Code as seen below, 

			new MockUp<com.sterlingcommerce.cd.sdk.MediatorEnum>() {
				MediatorEnum it;
				
				@Mock(minInvocations = 0)
				public boolean hasMoreElements(Invocation inv) {
                                        it = inv.getInvokedInstance();
					if (it instanceof ProcessMediatorEnum) {
						return false;
					}
					return true;
				}		
			};

This issue does not happen if its a local class. What may be the issue? Is there an alternate way of accessing the invocation object? 

* Check the following:

 - [ ] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
1.6 is a very old version... Anyway, I would need to know the signature of the "hasMoreElements(...)" method in MediatorEnum to diagnose the failure.

**Comment by vgavinash** [comment]
Hi Rliesenfeld, 

Thank you for the quick response. The signature of the method is, 

public boolean hasMoreElements()

**Comment by vgavinash** [comment]
Could you please provide me the link to download the latest versions of jmockit?

**Comment by rliesenfeld** [comment]
Ok, so that test should work... 
I won't be able to reproduce the problem, probably. Anyway, if there was a bug in JMockit 1.6, it was probably fixed long ago.

The version history can be found at http://jmockit.github.io/changes.html. All downloadable artifacts are in Maven Central.
