### ISSUE TITLE
Wrong super constructor is called

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#623]
This is a followup to #582.
The fix for it only fixed one narrow edge case.
I described other cases where it fails and even provided a reproducer project and described the needed logic to properly fix the issue.
The last comment was, that this will get fixed with the fix for #492.
But the fix for #492 was only a documentation change and the problem still persists.
All relevant information including reproducer and suggested logic to fix the issue is available in #582.

**Comment by rliesenfeld** [comment]
Ok, after examining https://github.com/Vampire/jmockit-wrong-super (from #492), it seems there is only one case to be considered, as shown in this minimal test case:
```
public class Issue623Test {
   static class Foo {
      final int value;
      Foo() { value = 1; System.out.println("Foo(): should not be called"); }
      Foo(int value) { this.value = value; }
   }

   static class SubFoo extends Foo {
      SubFoo() { super(2); }
      void doSomething() { assert value == 2 : "Not 2"; }
   }

   static class Bar extends SubFoo {}
   static class Baz extends SubFoo {}

   @Test
   public void mockOneSubclassButInstantiateUnmockedSibling(@Mocked Bar mockBar) {
      new Baz().doSomething(); // not mocked, should execute without error
   }
}
```

**Comment by Vampire** [comment]
> The case from #492 is fixed (it wasn't just an API documentation change).

Ah, ok, sorry. I only have seen the doc change and that my provided test cases still fail the same.

To have it here in context, I'll again write my suggestion:

> I guess any constructor found through guessing is wrong and even if the correct constructor would be found, the default parameters would break it eventually. The only rock-solid case probably is, if there is only one constructor and it has no parameters, as then not much can go wrong. For all other cases it is like russian roulette.
> I guess what might work is, to search in the original constructor the original super constructor call and copy it as first instruction, including the arguements given and then continue.
> If the call is mocked, it doesn't matter, if it is not mocked, hopefully the correct things happen with the correct arguments.
