### ISSUE TITLE
An IllegalArgumentException is not thrown when a matching real method/constructor cannot be found for a given fake method

### ISSUE THREAD

**Issue by rh-cal** [jmockit/jmockit1#624]
According to the documentation found at http://jmockit.github.io/tutorial/Faking.html: 
"Each @Mock method must have a corresponding "real method/constructor" with the same signature in the targeted real class. For a method, the signature consists of the method name and parameters; for a constructor, it's just the parameters, with the fake method having the special name "$init". If a matching real method/constructor cannot be found for a given fake method, either in the specified real class or in its super-classes (excluding java.lang.Object), an IllegalArgumentException is thrown when the test attempts to apply the fake class. Notice this exception can be caused by a refactoring in the real class (such as renaming the real method), so it's important to understand why it happens."

However, this does not seem to occur when using version 1.47 of JMockit.  If I have the following defined:
```
public class ClassToMock {
    public int instanceMethodNew() {
        return 2;
    }
}
```
```
public class ClassToMockTest {
    @Test
    public void instanceMethodTest() {
        new MockUp<ClassToMock>() {
            @Mock
            public int instanceMethod() {
                return 4;
            }
        };

        ClassToMock classToMock = new ClassToMock();
        Assert.assertEquals(4, classToMock.instanceMethodNew());
    }
}
```

then the test fails due to the assertEquals instead of an IllegalArgumentException. This also occurs if the parameters of the mocked method do not match instead of the name not matching (i.e. if the method in ClassToMock is "instanceMethod(int ignoreValue)" instead of "instanceMethodNew()"). 

Is this expected behavior and the documentation is incorrect or should an IllegalArgumentException be thrown? I was hoping for an IllegalArgumentException as this would catch when the real class/method is refactored but the related tests were not.

**Comment by rliesenfeld** [comment]
Indeed, that validation was removed in version 1.30. The API documentation was updated back then, but the Tutorial was not. It has been now.
