### ISSUE TITLE
New Junit 5 integration issues

### ISSUE THREAD

**Issue by TheGoesen** [jmockit/jmockit1#625]
Using jmockit 1.47.  on Junit 5
This is a follow up to
https://github.com/jmockit/jmockit1/issues/619

This issue changed how jmockit integrates into JUnit, now a system property is set to enable automatic extension lookup in junit5.
But this will cause junit5 to pick up all extensions, not just the jmockit extension. In my case a faulty extension that i don't need or want to be picked up automatically (jmock) gets picked up as well and the testcase simply crashes out.
I believe this is currently a bug/limitation in Junit as it doesn't seem to provide a clean way that jmockit can register its own (and only its own) extension.

Until JUnit offeres a solution to this problem, maybe this can be mitigated by providing a new systemproperty in which case ` junit.jupiter.extensions.autodetection.enabled", "true"` will **not** be set and the user has to setup the junitextension by himself.

**Comment by rliesenfeld** [comment]
It's a bug in jmock-2.11 (the `JUnit5Mockery` class erroneously assumes that any test class would have a `Mockery` field). I noticed you already reported [this bug](https://github.com/jmock-developers/jmock-library/issues/155) to the jMock project, so I am closing this issue.
