### ISSUE TITLE
Way to inject mock values in BeforeClass or BeforeSuite method. 

### ISSUE THREAD

**Issue by KanakdasG** [jmockit/jmockit1#628]
Hi,

I'm trying to use JMockit 1.47 version and switching from Powermockito. Here is the situation.

I've @PostConstruct method where FacesContext object is used which will not be available in testing environment hence need to create Mock.

Example :
Class ToBeTested () {
@PostConstruct
UIViewRoot viewRoot = FacesContext.getCurrentInstance ( ).getViewRoot ( );
        UIComponent column = viewRoot.findComponent ( tableId + SymbolConstants.COLON + fieldId );
}

TestClass {
@Tested ToBeTested  toBeTested;

@Mocked FacesContext facesContext;

}

Now in the above example I've facesContext mocked hence i'm getting some object in "viewRoot" but there is no option that can mock behavior of "viewRoot.findComponent ( tableId + SymbolConstants.COLON + fieldId )".

Tried things:
including @MockUp and Expectations in @BeforeClass @BeforeSuite both does not work as Jmockit can only inject mocks from @BeforeMethod.

Please let me know if there is existing implementation to overcome this.

**Comment by rliesenfeld** [comment]
The following test works for me:
```
public class JSFPageTest {
    static class ToBeTested {
        int childCount;

        @PostConstruct
        void init() {
            UIViewRoot viewRoot = FacesContext.getCurrentInstance().getViewRoot();
            UIComponent column = viewRoot.findComponent("someComponentId");
            childCount = column.getChildCount();
        }
    }

    @Tested ToBeTested tested;
    @Mocked FacesContext facesContext;
    @Mocked UIViewRoot viewRoot;
    @Mocked UIComponent column;

    @Before
    public void setUp() {
        new Expectations() {{
            viewRoot.findComponent("someComponentId"); result = column;
            column.getChildCount(); result = 123;
        }};
    }

    @Test
    public void mockFacesComponent() {
        assertEquals(123, tested.childCount);
    }
}
```
It's too much mocking, though. From my previous experience with JSF/PrimeFaces, it seems weird to be accessing page components on the JSF page bean like that - it shouldn't be necessary.
