### ISSUE TITLE
Having problems mocking a constructor

### ISSUE THREAD

**Issue by ramses-gomez** [jmockit/jmockit1#630]
JMockit version: 1.48

as per the documentation we could mock constructors like this:

void test(@Mocked ClassA classAMock) {
     new Expectations() {{
          new ClassA(); result = classAMock
     }}
}

However, when I do this I get the error message:

Invalid assignment to result field for constructor expectation
java.lang.IllegalArgumentException: Invalid assignment to result field for constructor expectation

I was able to use the other way to mock a constructor using:

void test(@Mocked ClassA classAMock) {
     new Expectations() {{
          ClassA classA = new ClassA();
          classA.getInt(); result = 5;
     }}
}

**Comment by rliesenfeld** [comment]
What documentation exactly?

Anyway, the first test above is indeed incorrectly recording a constructor expectation, and the second one is recording a redundant constructor expectation. To get a mocked `getInt()` to return `5` on any `@Mocked ClassA` instance, the test should simply be as follows:
```
void test(@Mocked ClassA anyA) {
    new Expectations() {{ anyA.getInt(); result = 5; }};

     int i1 = anyA.getInt();
     int i2 = new ClassA().getInt();

    assertEquals(5, i1);
    assertEquals(5, i2);
}
```
```

**Comment by ramses-gomez** [comment]
This is the documentation:

https://jmockit.github.io/tutorial/Mocking.html#futureInstancesByConstructor

**Comment by rliesenfeld** [comment]
Yes, but that is only for the case where you want (two or more) *different* future instances to have *different* behavior, depending on the constructor calls with which they were created.

**Comment by ramses-gomez** [comment]
Yes I understand so that means this will not work when you have only one instance?

**Comment by rliesenfeld** [comment]
Yes, because it serves no purpose to record the constructor expectation in that case.

**Comment by ramses-gomez** [comment]
Ok but to be honest the documentation is not very clear in that aspect.
