### ISSUE TITLE
Faking API needs simpler way to assert Invocations

### ISSUE THREAD

**Issue by jbennett2091** [jmockit/jmockit1#635]
Please provide the following information:

* Version of JMockit that was used:  1.48

* Description of the problem or enhancement request:
In JMockit 1.47, we mocked static methods using the Expectations API and asserted the number of calls with the simple "times=2" syntax.  As statics method mocking must now use the Faking API, it would be nice to have a simple way to check the same concept.  In today's Faking API, this necessitates checking for overflow using "assertTrue( Invocations.getInvocationCount() <= 2)", but there's no easy way to check for minTimes=2.  [I was able to use a MutableInt as a counter, but that's clumsy].   Way back in the day (I think), the "@Mock" annotation supported an "(invocations=2}" value that would be invaluable as a cleaner API.

* Check the following:

 - [x] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [x] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

I can provide if need be.

 - [x] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [x] The JDK where the problem occurs is a final release, not a development build.

AdoptOpenJDK 1.8_222

**Comment by jbennett2091** [comment]
This relates to the issue #492 that drove the shift of statics to Faking API

**Comment by jbennett2091** [comment]
`import org.apache.commons.lang3.mutable.MutableInt;
import org.junit.Assert;
import org.junit.Test;

import mockit.Invocation;
import mockit.Mock;
import mockit.MockUp;

public class Example635Test
{
	@Test
	public void testDesiredAPI()
	{
		new MockUp<ClassUnderTest>()
		{
			@Mock(invocations = 2)
			void bar(
				final int idx)
			{
				// no-op
			}
		};

		new ClassUnderTest().foo(2);
	}

	@Test
	public void testCurrentAPI()
	{
		// create a counter
		final MutableInt muty = new MutableInt();
		
		new MockUp<ClassUnderTest>()
		{
			@Mock
			void bar(
				final Invocation invocations,
				final int idx)
			{
				// this can be used to verify that we do not go OVER the number of calls.
				// However, it cannot be used to identify underflows (e.g. minTimes)
				Assert.assertTrue(invocations.getInvocationCount() <= 2);

				// track a counter
				muty.add(1);
			}
		};

		new ClassUnderTest().foo(2);

		// check for underflow
		Assert.assertEquals(2, muty.intValue());
	}

}

class ClassUnderTest
{
	public void foo(
		final int max)
	{
		for (int i = 0; i < max; ++i)
			bar(i);
	}

	public static void bar(
		final int idx)
	{
		System.out.println("idx: " + idx);
	}
}
`

**Comment by rliesenfeld** [comment]
"As statics method mocking must now use the Faking API" ?!?

No, static methods are still mockable with the Expectations API, there was no change.

**Comment by jbennett2091** [comment]
Ok, perhaps I am not describing the affected code properly.  In 1.48, support was dropped for partial mocking of a set of classes.  These are the ones that need to move to Faking API.  

In any event, having better way to check invocations on Fake API would be a good thing

**Comment by rliesenfeld** [comment]
No need, the test already can be written nicely as follows:

```
    @Tested @Mocked ClassUnderTest cut;

    @Test
    public void example() {
        new Expectations() {{ ClassUnderTest.bar(anyInt); times = 2; }};

        cut.foo(2);
    }
```

**Comment by rliesenfeld** [comment]
See any of the sample test suites under https://github.com/jmockit/jmockit1/tree/master/samples
