### ISSUE TITLE
Having problems using expectations block

### ISSUE THREAD

**Issue by xy720** [jmockit/jmockit1#638]
Version of JMockit
1.13

Can I put the Expectations block in a static method?
Sample:

```
public class TranslatorTest {
    private Translator translator;

   @Before
   public void setUp() {
       translator = TranslatorTestUtil.fetchTranslator();
   }

   @Test 
   public void testNormal() {
       String stringNeedToTranslate = "你好, 我的名字是xy720";
       String stringAlreadyTranslated = translator.translate(stringNeedToParse);
       Assert.assertEquals("Hello, my name is xy720", stringAlreadyTranslated);
   }
}

public class TranslatorTestUtil {
    public static Translator fetchTranslator() {
        Translator translator = new Translator();
        new Expectations(translator) {
            
            translator.getSourceLanguage();
            result = Language.Chinese;
        
            translator.getTargetLanguage();
            result = Language.English;
        }
        return translator;
   }
}
```
The code in this expectations block and this "translator" will be used  a lot in many test class, so I try to put this expectations block in a static method to reduce the repeated code. 

But some Exception I have received :

```
java.lang.IllegalStateException: Invalid place to record expectations
at TranslatorTestUtil$2.<init>(TranslatorTestUtil.java:4)
	at TranslatorTestUtil.fetchTranslator(TranslatorTestUtil.java:4)
	at TranslatorTest.setUp(DescribeStmtTest.java:5)
```

Does the expectations block can only be placed in a test class?
Is there an other way to reduce the repeatability of expectations block?
Please give me some advice. Thank you

**Comment by rliesenfeld** [comment]
That `IllegalStateException: Invalid place to record expectations` exception is not referring to any `static` method, but to the JUnit `@Before` method. This behavior has changed in newer versions, though.
