### ISSUE TITLE
JMockit throws NullPointerException with no apparent stack trace

### ISSUE THREAD

**Issue by lindstrum** [jmockit/jmockit1#639]
Please provide the following information:

* Version of JMockit that was used: 1.42 and later. This is not a problem in 1.41 or before

* Description of the problem or enhancement request:

This is done with Java 1.8.231 and Maven.

 Given the class structure 

```
class Type1 {

 }

 class Type2 {
      private Type1 type1;

      Type2(Type1 type1) {
           this.type1= type1;
      }
 }
```

And the following test

```
 class Type2Test {
      @Injectable
      Type1 type1;


      @Test
      void randomTestThatShouldPass() {
           Assert.assertTrue(true);
      }
 }
```

I get a `NullPointerException` thrown with no apparent stack trace. The following is what is shown on my console 
>java.lang.NullPointerException

Note that if I change `@Injectable` to `@Mocked`, the same issue occurs. The following is my pom.xml file

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ok.ubc.cosc.VisualizeCode</groupId>
  <artifactId>VisualizeCode</artifactId>
  <packaging>jar</packaging>
  <version>1.0</version>
  <name>VisualizeCode</name>
  <url>http://maven.apache.org</url>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <dependencies>
      <dependency>
          <groupId>org.testng</groupId>
          <artifactId>testng</artifactId>
          <version>6.14.3</version>
          <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.jmockit</groupId>
        <artifactId>jmockit</artifactId>
        <version>1.48</version>
        <scope>test</scope>
    </dependency>
  </dependencies>
</project>

```
I also described my issue [here](https://stackoverflow.com/questions/59130084/why-is-jmockit-throwing-a-nullpointerexception-with-no-stack-trace)

* Check the following:

 - [x] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [x] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
Check the documentation on how to run JMockit tests from Maven, https://jmockit.github.io/tutorial/Introduction.html#maven, as the surefire plugin configuration needs to be provided.
