### ISSUE TITLE
Why a list member can not be mocked?

### ISSUE THREAD

**Issue by xy720** [jmockit/jmockit1#641]
* Version of JMockit: 1.48

* Description of the problem:
How can I mock a List type of member ?

I run the code following:

```
class MyClass {
    public List<MyInfo> myInfoList;

    public String print() {
        return "listSize: " + myInfoList.size();
    }
}

class MyClassTest {
    @Tested
    public MyClass myClass;

    @Test
    public void testNormal(@Injectable List<MyInfo> myInfoList,
                                            @Injectable MyInfo myInfo) {
        myInfoList.add(myInfo);
        Assert.assertEquals("listSize: 1", myClass.print());
    }
}
```

And I receive a exception:
java.lang.IllegalArgumentException: java.util.List is not mockable

Why a list member can not be mocked ? How can I overcome this problem ?
Please give me some advice. Thanks a lot!

**Comment by rliesenfeld** [comment]
A `List` is not mockable because it's never a good idea to mock one.

**Comment by xy720** [comment]
I see. How about mocking a Thread object ? I wonder why JMockit remove this skill in newer version.
