### ISSUE TITLE
with jdk11 ,facing class redefinition failed: attempted to change the class NestHost or NestMembers attribute

### ISSUE THREAD

**Issue by hackathon64** [jmockit/jmockit1#643]
Please provide the following information:

* Version of JMockit that was used: 1.37

* Description of the problem or enhancement request:

With jdk 11 and  jmokit 1.37 version, facing **java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost or NestMembers attribute
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)**

Test cases are working fine with Jmokit 1.37 and jdk>=8.
could you please provide any workaround for same.

**Comment by rliesenfeld** [comment]
This has been solved in newer releases, not sure which one, but after 1.37.

**Comment by hackathon64** [comment]
Thank you :)
