### ISSUE TITLE
java.lang.IllegalStateException: Running on JDK 9 requires -javaagent:<proper path>/jmockit-1.n.jar or -Djdk.attach.allowAttachSelf

### ISSUE THREAD

**Issue by hackathon64** [jmockit/jmockit1#644]
* Version of JMockit that was used: 1.37

* JDK Version 11 

While running Unit test case on JDK 11 getting **java.lang.IllegalStateException: Running on JDK 9 requires -javaagent:<proper path>/jmockit-1.n.jar or -Djdk.attach.allowAttachSelf** 

Test cases are running fine with JDK<=1.8.

--------------------------
How we can add/pass  VM arguments in maven?

**Comment by rliesenfeld** [comment]
That's a question about Maven usage, try StackOverflow or Maven documentation.
