### ISSUE TITLE
Unable to mock superclass in JMockit 1.48

### ISSUE THREAD

**Issue by zeic** [jmockit/jmockit1#647]
* Version of JMockit that was used: 1.47 and 1.48

In the 1.47 version of JMockit I am able to prevent content from running in a superclass of my @Tested class by simply using an @Mocked of the superclass type, or if I wanted to control some of the method behaviors, by using a partial mock with the MockUp<> pattern. when switching to 1.48, the @Tested annotation seems to now call the initialization of the superclass (and any of its superclasses) regardless of what I try to mock/fake, resulting in null pointer exceptions in the constructors of the superclass. If this is an intended change, what is now the process to properly mock out the superclass of a tested class to control the test environment?

For example, in this case, I am using JMockit to test a SmartfoxServer2X extension class which extends the SFSExtension by design I was able to @Mocked the SFSExtension in my test class and when I used @Tested on my extension everything worked. now in 1.48 and 1.49 this is no longer the case and the tests fail in initializing the @Tested extension due to failures in the SFSExtension init and its superclass init in BaseSFSExtension.

I imagine that any case where heavy lifting is done in a superclass constructor this could be an issue.

Any help would be appreciated. I like to keep my dependencies to the latest versions and I really like the flexibility JMockit provides with testing capabilities and I don't want to have to be stuck on version 1.47 forever.

**Comment by rliesenfeld** [comment]
Consider writing tests that focus on relevant functionality, not on implementation details. It's what I do, and although I frequently write complex tests for complex code with JMockit, I never run into such issues.

**Comment by zeic** [comment]
The issue is as basic as possible when it comes to unit testing. The SmarkfoxServer2x framework I am utilizing has requirements to extend their classes. its not about testing relevant functionality as I cannot test ANY functionality. I am unable to use @Tested on the class under test because it throws a failure in <init> because JMockit 1.48 ignores the Mock I made of the superclass to prevent the <init> failures. I do not want to test the functionality of the super class. I am simply asking if there is a way to do this going forward past version 1.47. I don't want to have to change the implementation code to move any and all logic to a new handler class simply so I do not have to worry about not being able to use @Tested on the class I desire to test. If the answer is to leave my version at 1.47 then I will do so.

**Comment by ldeck** [comment]
Shame this was closed. I’m having this same issue updating from 1.38 to 1.49.

Some spring classes require a concrete implementation be provided, but the superclass is too complex to consider writing tests for — it’s just our business logic we care about.

How do we translate tests that used @mocked for the superclass and verified interactions with it to the later version of JMockit?
