### ISSUE TITLE
Broken verification of method calls when using @Injectable

### ISSUE THREAD

**Issue by yfcz** [jmockit/jmockit1#650]
Please provide the following information:

* Version of JMockit that was used:
1.49

* Version of TestNG was used: 
6.11, 6.13, 7.0.0

* Description of the problem or enhancement request:
Since version 1.37 there is an issues with verification of method calls to static methods when using @Injectable annotation.

It can be reproduced when running following example. See testStaticMethod method:

`package whatever;

import org.testng.annotations.Test;

import mockit.Injectable;
import mockit.Verifications;

public class TestClass {

    // works fine when using @Mocked
    @Injectable private Dependency dependency;

    // passes with JMockit 1.49 (since version 1.37)
    @Test
    void testStaticMethod() {

        new Verifications() {
            {
                dependency.staticMethod();
                times = 100;

                Dependency.staticMethod();
                times = 100;

                dependency.staticMethod();
                Dependency.staticMethod();
            }
        };
    }

    // fails with JMockit 1.49 as expected
    @Test
    void testNonStaticMethod() {

        new Verifications() {
            {
                dependency.nonStaticMethod();
                times = 100;

                dependency.nonStaticMethod();
            }
        };
    }

    private final static class Dependency {

        static void staticMethod() {
        }

        void nonStaticMethod() {
        }
    }
}`

**Comment by rliesenfeld** [comment]
I don't see anything unexpected in the outcome from these (incomplete) tests. They are getting exactly what the JMockit documentation says they should get.

The first test passes as it should, since it is not recording any expectations on mocked methods, and `Dependency#staticMethod()` does nothing.
