### ISSUE TITLE
Unable to mock Region class from Apache Geode

### ISSUE THREAD

**Issue by Sable021** [jmockit/jmockit1#655]
Please provide the following information:

* Version of JMockit that was used: 1.45, 1.49

* Description of the problem or enhancement request:
The Region class is an extension of Java's ConcurrentMap, which cannot be mocked via @Injectable as explained in the release notes. However, if I follow the recommendation and declare an @Tested Region class before the actual class to be tested I will receive a missing @Injectable error instead.

// Region declaration in class
public class TrackData {
  ...    
  @Autowired
  @Qualifier("Track")
  private Region<Object, Object> trackRegion;
  ...
}

// Will give "Missing @Injectable" error
...
@Tested
private Region<Object, Object> mockRegion;

@Tested
private TrackData tested;
...

// Will give "java.util.Map is not mockable" error for jmockit 1.45 
// Will give "org.apache.geode.cache.Region is not mockable" error for 1.49
...
@Tested
private TrackData tested;

@Injectable
private Region<Object, Object> mockRegion;
...

**Comment by rliesenfeld** [comment]
The "Missing @Injectable" error message should mention that a @Tested object would also do; this shortcoming was fixed for the next release.

Beyond that, the @Tested API documentation describes other relevant details.
