### ISSUE TITLE
Best practice to test a method without mocking private method inside

### ISSUE THREAD

**Issue by baibinghere** [jmockit/jmockit1#656]
* Version of JMockit that was used: 
JMockit 1.32

Since JMockit has deprecated any possibility of mocking private method, I'm asking what should I do with JMockit to test getResult() in the following case:

```Java
public class A {
    List<File> fileList;
    private String readFile(File f) {
         // read content string s from a file.
          return s;
    }
    public String getResult() {
          String wholeS = "";
          for (File f: fileList) {
               s = readFile();
               // conditionally concatenate with wholeS
               wholeS += s;
           }
           // do some calculation with wholeS and return result.
           return result;
    }
}
```
The `readFile()` function will read from a local data file which only exist in actual environment.
My purpose is to verify if the getResult() function's calculation is correct.

Previously, I could mock readFile, different File f returns different String result.
What is the best practice to test getResult() now?

**Comment by rliesenfeld** [comment]
You can use actual files.

**Comment by baibinghere** [comment]
Hi rliesenfeld,

I'm afraid this is just an easy-to-read example of the problem.
This so called `readfile` does not always be that simple.
It could be some data that we can only read from production internal network.

I thought one of the purpose of UT(comparing to IT) is to isolate the environment, so that each function can run without preparing run time environment (such as files, network...)

Could you please guide me a little more if I'm not understanding this correctly?
