### ISSUE TITLE
java.lang.IllegalStateException: Invalid place to apply a mock-up

### ISSUE THREAD

**Issue by margamraviteja** [jmockit/jmockit1#657]
Please provide the following information:

* Version of JMockit that was used: 1.9
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <version>1.9</version>

* Description of the problem or enhancement request:
When running the junit test cases in parallel, its throwing "exception Invalid place to apply a mock-up". Using Java (1.8), JUnit (4.12) and maven-surefire-plugin (2.19.1) with configuration parallel as "classes" and threadCount as "10"

* Check the following:

 - [ ] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
Same as #408.

**Comment by sbagal21** [comment]
I am getting same error .. can anyone help me to resolve issue.
Issue:
invalid place to apply a mock-up.
Jmockit version 1.9
