### ISSUE TITLE
Cant mock Implementation of Map.

### ISSUE THREAD

**Issue by KaWoll** [jmockit/jmockit1#661]
Hi folks,

JMockit: 1.48

In my code I am using a third party jar-file, can't change the source code. To test my code I wanted to use JMockit, but I can't mock a class which implements Map. 

Error: java.lang.IllegalArgumentException: class com.platform.api.Parameters is not mockable (mock field "p")

Is there any way to mock the Parameters-class or do I have to switch to Mockito again?

Best regards,

Kalle.

**Comment by rliesenfeld** [comment]
Same as #610.
