### ISSUE TITLE
Fake is not being torn down in Spock tests

### ISSUE THREAD

**Issue by kriegaex** [jmockit/jmockit1#668]
Please provide the following information:

* Version of JMockit that was used: 
1.49

* Description of the problem or enhancement request:
I use Spock, a Groovy framework based on JUnit, for writing tests. As it cannot mock final classes, I tried JMockit and it works nicely. The problem is that in between test methods my `MockUp<FinalClass>` is not being torn down even though the instance was created inside test method A. But in test method B run after A the mock is still active. I added an `onTearDown()` method printing something to the console, but obviously it is never being called. Can you explain how JMockit recognises test methods? I read somewhere tear-down should occur when the mock-up goes out of scope, however you determine that. In fact, it does not.

* Check the following:

 - [x] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [x] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

I know that this question is about Groovy and I did not want to raise an issue, just ask a question. But I found no other way to contact the maintainer, such as contacting him via Gitter or e-mail. Please bear with me and answer the question if you can. You can also tell me how to contact you in a more appropriate way.

Even a workaround such as a way to manually tear down the mock-up would be okay at this point. I know there used to be such a way which was first deprecated and then removed. Is there a clean way to hook into the lifecycle?

 - [x] The JDK where the problem occurs is a final release, not a development build.

**Comment by kriegaex** [comment]
BTW, I just found PR #358 by @Vampire which you refused. Sorry not to have found it earlier, but I was searching for existing issues, not for closed PRs.

**Comment by rliesenfeld** [comment]
JMockit integrates into the test runner, provided it is either JUnit 4, JUnit 5, or TestNG. Spock is not going to be supported.

My personal recommendation, use Java with JUnit 5. Groovy and Spock don't really provide extra value, to the best of my knowledge.

**Comment by kriegaex** [comment]
> JMockit integrates into the test runner, provided it is either JUnit 4, JUnit 5, or TestNG. Spock is not going to be supported.

Spock also runs on top of JUnit 4 or 5 platform.

> My personal recommendation, use Java with JUnit 5.

Thank you, that is not an option for me. Neither is it for 

> Groovy and Spock don't really provide extra value, to the best of my knowledge.

Then your knowledge is very limited. There is so much extra value, I wouldn't even know where to begin listing it.

Anyway, I get the message. It is the same as what you told @Vampire. You just refuse to even consider it, even if someone volunteers to contribute code like him. I did not even request Groovy or specifically Spock support but was asking a question about JMockit lifecycle, specifically with regard to tear-down and whether I can get a workaround in order to initiate it manually. You did not even comment on that.

**Comment by rliesenfeld** [comment]
Ok, to better answer your questions:
1. It was never the case that mock-up tear down would "occur when the mock-up goes out of scope". It is done through test runner integration, that is, JMockit knows about and uses the regular events from the test runner (test starting/ending).
2. JMockit used to have "a way to manually tear down the mock-up", but it was deprecated in removed from the API about 4 years ago, as noted in the Release Notes: "Deprecated the MockUp#tearDown() method. Mock-up tear down is automatic, so explicit calls to this method are either made by mistake, or by misuse in tests that should be broken down into two or more test methods."

**Comment by kriegaex** [comment]
> 1. It was never the case that mock-up tear down would "occur when the mock-up goes out of scope".

I was just quoting the [Javadoc of `MockUp.onTearDown`](https://github.com/jmockit/jmockit1/blob/73cfb5fe805c1e2c95a94462306b36b208f1f7d5/main/src/mockit/MockUp.java#L133):

>> Tear down happens when the fake goes out of scope: at the end of the test when applied inside a test, at the end of the test class when applied before the test class, or at the end of the test run when applied through the `fakes` system property.

Who wrote that Javadoc if not you @rliesenfeld ?

> It is done through test runner integration, that is, JMockit knows about and uses the regular events from the test runner (test starting/ending).

As I said, Spock runs on top of JUnit 4 or 5 (Spock 1.x / 2.x), which is why I am surprised that it does not work. I run it normally via Maven Surefire or Failsafe, get the usual Maven test success/error reports, but JMockit fake objects do not get torn down.

> 2. JMockit used to have "a way to manually tear down the mock-up", but it was deprecated and removed from the API about 4 years ago

I know that because I read those release notes, which is why I as a first-time user know about it in the first place. Sorry, Rogério, but I really did my homework before bothering you with what you may think are silly questions.

> as noted in the Release Notes: "Deprecated the MockUp#tearDown() method. Mock-up tear down is automatic, so explicit calls to this method are either made by mistake, or by misuse in tests that should be broken down into two or more test methods."

Yeah, if it ***was*** automatic I would not have asked for a way to somehow do it manually.

Thank you very much for your renewed effort to answer my questions, but you only told me what I already knew and said above. How about finding the root cause of the problem together? Maybe there is a bug in JMockit or something about the test runner integration is too framework-specific or it can be fixed in Spock or what have you? Without your expertise I will not be able find out, I am afraid.

**Comment by Vampire** [comment]
> As I said, Spock runs on top of JUnit 4 or 5 (Spock 1.x / 2.x), which is why I am surprised that it does not work. I run it normally via Maven Surefire or Failsafe, get the usual Maven test success/error reports, but JMockit fake objects do not get torn down.

Are you sure they are not torn down generally with Spock 1.x?
Afair the `MockUp` instances are torn down after the feature.
The problem is that the `MockUp` should be torn down after each iteration.
You could achieve that with the manual `tearDown()` method before it was removed.
But as long as you do not use a `MockUp` in a data-driven feature it should work as far as I remember.

With Spock 2.x it will probably be different.
I bet the JUnit 5 compatibility is only for the Jupiter engine.
But Spock provides an own JUnit 5 engine, so the Jupiter hook-points will not help.

**Comment by kriegaex** [comment]
@Vampire, actually my original test project was with JUnit 5 Jupiter, Groovy 3 and Spock 2.0-M3. But after you said that I copied the test and the JMockit agent starter into my Spock 1.x project and the result is the same. Here is my [MCVE](https://stackoverflow.com/help/mcve):

**Java classes under test:**

```java
package de.scrum_master.stackoverflow;

public final class FinalClass {
  public static final String finalStaticMethod() {
    return "x";
  }

  public final String finalMethod() {
    return "x";
  }
}
```

```java
package de.scrum_master.stackoverflow;

public class AnotherClass {
  public String doSomething(FinalClass finalClass) {
    return finalClass.finalMethod();
  }

  public String doSomethingElse() {
    return FinalClass.finalStaticMethod();
  }
}
```

**Spock test:**

```groovy
package de.scrum_master.stackoverflow

import mockit.Mock
import mockit.MockUp
import spock.lang.Specification
import spock.lang.Stepwise

@Stepwise
class FinalClassJMockitTest extends Specification {
  def setupSpec() {
    URLClassLoader urlClassLoader = this.class.classLoader
    urlClassLoader
      .URLs
      .collect { it.path.replaceFirst(".*/", "") }
      .unique()
      .findAll { it =~ /spock-core|^groovy-[0-9]|jmockit|^junit-[0-9]/ }
      .each { println it }
  }

  def "use original final class before JMockit"() {
    expect:
    new AnotherClass().doSomething(new FinalClass()) == "x"
  }

  def "use JMockit to stub final method in final class"() {
    given:
    new FakeFinalClass()

    expect:
    new AnotherClass().doSomething(new FinalClass()) == "mocked"
  }

  def "use original final class after JMockit"() {
    expect:
    new AnotherClass().doSomething(new FinalClass()) == "x"
  }

  static class FakeFinalClass extends MockUp<FinalClass> {
    @Mock
    String finalMethod() {
      "mocked"
    }

    @Override
    protected void onTearDown() {
      println "FakeFinalClass tearDown"
    }
  }
}
```

**Console log:**

```none
junit-4.12.jar
spock-core-1.3-groovy-2.5.jar
groovy-2.5.4.jar
jmockit-1.46.jar

Condition not satisfied:

new AnotherClass().doSomething(new FinalClass()) == "x"
|                  |           |                 |
|                  mocked      |                 false
|                              |                 6 differences (0% similarity)
|                              |                 (mocked)
|                              |                 (x-----)
|                              <de.scrum_master.stackoverflow.FinalClass@1cdc4c27>
<de.scrum_master.stackoverflow.AnotherClass@6e35bc3d>

at de.scrum_master.stackoverflow.FinalClassJMockitTest.use original final class after JMockit(FinalClassJMockitTest.groovy:35)
```

So you see the problem occurs in normal feature methods (test methods in JUnit speak), not just in iterated ones (parametrised tests).

**Comment by Vampire** [comment]
Well, then I maybe remember wrongly or things changed.
I'm not sure, it is 5 years or so ago that I played with it.

**Comment by kriegaex** [comment]
For completeness' sake, here is the same test as a Java JUnit test which works as expected:

```java
package de.scrum_master.stackoverflow;

import mockit.Mock;
import mockit.MockUp;
import org.junit.FixMethodOrder;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.runners.MethodSorters.NAME_ASCENDING;

@FixMethodOrder(NAME_ASCENDING)
public class FinalClassJMockitJUnitTest {
  @Test
  public void a_useOriginalFinalClassBeforeJMockit() {
    assertEquals(new AnotherClass().doSomething(new FinalClass()), "x");
  }

  @Test
  public void b_useJMockitToStubFinalMethodInFinalClass() {
    new FakeFinalClass();
    assertEquals(new AnotherClass().doSomething(new FinalClass()), "mocked");
  }

  @Test
  public void c_useOriginalFinalClassAfterJMockit() {
    assertEquals(new AnotherClass().doSomething(new FinalClass()), "x");
  }

  static class FakeFinalClass extends MockUp<FinalClass> {
    @Mock
    String finalMethod() {
      return "mocked";
    }

    @Override
    protected void onTearDown() {
      System.out.println("FakeFinalClass tearDown");
    }
  }
}
```

Of course it also prints this during execution of the second method:

```none
FakeFinalClass tearDown
```

**Comment by kriegaex** [comment]
Okay, I finally found a workaround by manually creating a `mockit.internal.state.SavePoint` and rolling that save point back after each feature method or iteration like so:

```groovy
  def jMockitSavePoint = new SavePoint()

  def cleanup() {
    jMockitSavePoint.rollback()
  }
```

This is not nice, but it works and uses public API, even though from an internal package. Now maybe @rliesenfeld want to tell me that this is bad and list a few negative side effects, and in that case I would of course listen and learn. For now I am just happy I found a workaround.

The full updated Spock specification (test class in JUnit speak) looks like this:

```groovy
package de.scrum_master.stackoverflow

import mockit.Mock
import mockit.MockUp
import mockit.internal.state.SavePoint
import spock.lang.Specification
import spock.lang.Stepwise

@Stepwise
class FinalClassJMockitTest extends Specification {
  def jMockitSavePoint = new SavePoint()

  def cleanup() {
    jMockitSavePoint.rollback()
  }

  def "use original final class before JMockit"() {
    expect:
    new AnotherClass().doSomething(new FinalClass()) == "x"
  }

  def "use JMockit to stub final method in final class"() {
    given:
    new FakeFinalClass()

    expect:
    new AnotherClass().doSomething(new FinalClass()) == "mocked"
  }

  def "use original final class after JMockit"() {
    expect:
    new AnotherClass().doSomething(new FinalClass()) == "x"
  }

  static class FakeFinalClass extends MockUp<FinalClass> {
    @Mock
    String finalMethod() {
      "mocked"
    }

    @Override
    protected void onTearDown() {
      println "FakeFinalClass tearDown"
    }
  }
}
```
