### ISSUE TITLE
Add helper in place of withArgThat()

### ISSUE THREAD

**Issue by wacker** [jmockit/jmockit1#669]
Let's say I want to write a unit test for the following Method:

```java
void signUp(String username) {
    User user = UserRegistry.create(new UserProperties(username));
    AuditService.report(new AuditEntry(USER_CREATED, user.id));
}
```

In 1.43 and before, I could have written:

```java
@Test
public void signUp() {
    User dummyUser = new User() {{ id = 42; }};

    new Expectations() {{
        UserRegistry.create(withArgThat(hasProperty("name", is("john"))));
        result = dummyUser;
    }};

    underTest.signUp("john");

    new Verifications() {{
        AuditService.report(withArgThat(hasProperty("userId", is(42))));
    }};
}
```

Now I have to write:

```java
@Test
public void signUp() {
    User dummyUser = new User() {{ id = 42; }};

    new Expectations() {{
        UserRegistry.create(with(new Delegate<UserProperties>() {
            boolean matches(UserProperties properties) {
                return hasProperty("name", is("john")).matches(properties);
            }
        }));
        result = dummyUser;
    }};
		
    underTest.signUp("john");
		
    new Verifications() {{
        AuditService.report(with(new Delegate<AuditEntry>() {
            boolean matches(AuditEntry entry) {
                return hasProperty("userId", is(42)).matches(entry);
            }
        }));
    }};
}
```

or, using a helper:

```java
static <T> Delegate<T> argThat(Matcher<? super T> matcher) {
    return new Delegate<T>() {
        boolean matches(T arg) {
            return matcher.matches(arg);
        }
    };
}

@Test
public void signUp() {
    User dummyUser = new User() {{ id = 42; }};

    new Expectations() {{
        UserRegistry.create(with(argThat(hasProperty("name", is("john")))));
        result = dummyUser;
    }};
		
    underTest.signUp("john");
		
    new Verifications() {{
        AuditService.report(with(argThat(hasProperty("userId", is(42)))));
    }};
}
```

So, why was `withArgThat()` removed? And why is this helper not part of JMockit instead?

**Comment by rliesenfeld** [comment]
That's not the alternative to `withArgThat` that was recommended  in the "Release notes" when it was deprecated in 2018.

Personally though, I think all three versions of the test (the two above plus the one that could be written using argument capturing) are bad. The proper way to test the `signUp` method is by *not* mocking anything.

**Comment by wacker** [comment]
> That's not the alternative to withArgThat that was recommended in the "Release notes" when it was deprecated in 2018.

These ["Release notes"](https://jmockit.github.io/changes.html#1.43) state:

> Deprecated [...], in favor of argument capturing (the `withCapture(...)` methods) and the `with(Delegate)` method.

Since the [tutorial on `withCapture(...)`](https://jmockit.github.io/tutorial/Mocking.html#withCapture) only mentions verifications and not `Expectations`, `with(Delegate)` was used in the tests presented.

The [tutorial](https://jmockit.github.io/tutorial/Mocking.html#withMethods) offers no clue on how `with(Delegate)` is intended to be used. The [JavaDoc on `with(Delegate)`](https://javadoc.io/static/org.jmockit/jmockit/1.49/mockit/Expectations.html#with-mockit.Delegate-) states:

> The class of the given delegate object should define a single non-private delegate method (plus any number of helper private methods)

without providing an example. A _class that should define a single non-private method_ [sounds familiar](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html#package.description) and begs the  question if threre is a (or why there is no) [functional interface](https://docs.oracle.com/javase/8/docs/api/index.html?java/lang/FunctionalInterface.html) provided by JMockit.

>  Personally though, I think all three versions of the test [...] are bad.

Can you please point to a more detailled explanation, documentation or a collection of examples that would substantiate your opinion?

> The proper way to test the `signUp` method is by not mocking anything.

Pretty sure at least `AuditService` and `UserRegistry` need to be mocked in order for the test to be a _Solitary UnitTest_. Besides that, I see your point. This may be the case with the tests presented, which have been simplified for illustrative purposes. Please bear in mind the case that `UserProperties` and `AuditEntry` are more complex objects or objects of derived classes and therefore not so easy to handle.

**Comment by rliesenfeld** [comment]
Note I wrote the recommended alternative to `withArgThat` is *argument capturing* (the `withCapture(...)` methods), *not* `with(Delegate)` (which you already used in your example test, so we are already discounting that).

"Could you please point to a more detailled explanation, documentation or a collection of examples that would substantiate your opinion?"

Sure: see https://jmockit.github.io/tutorial/Introduction.html#anExample, https://jmockit.github.io/tutorial/EnterpriseApplications.html, and a complete sample test module at https://github.com/jmockit/jmockit1/tree/master/samples/petclinic.

**Comment by wacker** [comment]
> Note I wrote the recommended alternative to `withArgThat` is [...] _not_ `with(Delegate)` [...]

I cannot see where you wrote that. The bullet point in the [Release Notes](http://jmockit.github.io/changes.html#1.43) contains an '_and_' instead of a '_not_' at this place:

> **Deprecated** the `withArgThat(Matcher)` method [...], in favor of argument capturing (the `withCapture(...)` methods) and the `with(Delegate)` method.

Also the deprecation hint in your [commit](https://github.com/jmockit/jmockit1/commit/f93923c4ca231be544097b97e6cba281990d5657) suggests to use `with(Delegate)`:

> `@deprecated Use withCapture(List) argument capturing or with(Delegate) instead.`

So, what's wrong now about `with(Delegate)`?

```java
new Expectations() {{
    methodCall(withArgThat(matcher1));
    result = result1;
    methodCall(withArgThat(matcher2));
    result = result2;
}};
```

Is this not possible after 1.43 any more?

None of the examples you pointed to are clear on this or contain any calls to either `withCapture()` or `with(Delegate)`.

**Comment by rliesenfeld** [comment]
My initial comment: "... (the two above plus the one that could be written *using argument capturing*).

But you can use `with(Delegate)` if you prefer. I wouldn't, as the `withCapture` methods ("argument capturing") provide a better alternative.

The https://jmockit.github.io/tutorial/Mocking.html#withCapture section provides three example tests using `withCapture`.

**Comment by wacker** [comment]
Thanks for your patience and for clearing this up. Ok, so if `withCapture(...)` is the way to go, I _guess_ (since the usage in combination with `Expectations` is not shown in any of the three example tests) my test would look like this:

```java
List<UserProperties> userPropertiesArgs = new ArrayList<>();
new Expectations() {{
    UserRegistry.create(withCapture(userPropertiesArgs));
    result = dummyUser
}};

underTest.signUp("john");

assertThat(userPropertiesArgs.size(), is(1));
assertThat(userPropertiesArgs.get(0), hasProperty("name", is("john")));
new Verifications() {{
    AuditEntry entry;
    AuditService.report(entry = withCapture());
    assertThat(entry, hasProperty("userId", is(42)));
}};
```

In which way is this better than my initial test using `with(Delegate)`?

Also, using this approach, how could the `result` be dependent on the argument (referring to my previous comment)?

This variant for example worked in earlier versions of JMockit:

```java
new Expectations() {{
    UserRegistry.create(withArgThat(hasProperty("name", is("john")))); result = john;
    UserRegistry.create(withArgThat(hasProperty("name", is("mary")))); result = mary;
}};
```

How would the 'better' alternative would look like in this case? Using the current version of JMockit, is this even possible ?

**Comment by rliesenfeld** [comment]
It's not about being a better API, since `withArgThat` is no longer available, and it certainly is not returning because it was a problematic Hamcrest-specific part of the API.

These kinds of complications arise from excessive use of *mocking*. If you really want to have lots of good and useful tests (I have ~1400 of them in my current project), avoid mocking as much as you can. I only use it in a few tests, when really needed.

**Comment by wacker** [comment]
You are lucky to work on code that can be tested using only little mocking.

Many projects depend on components that have been developed _without_ testing in mind: A lot of strong coupling, deep inheritance, static initializers, business logic in constructors, mixing different types of dependcy injection, ...

You _have to_ apply excessive use of mocking in those scenarios, and JMockit has been a great tool for that — not any more:

* Removed: `withArgThat()` (the current issue)
* Removed: the `Deencapsulation` class
* Removed: the `stubOutClassInitialization` attribute
* Removed: `MockUp#getMockInstance()`
* Removed: super class mocking (see [Issue 647](https://github.com/jmockit/jmockit1/issues/647))
* Removed: mocking anything that uses or inherits from `java.lang` classes

I can imagine all of these features were complicated and had issues. But removing them entirely and designing JMockit increasingly for only testing well structured code makes your tool a lot less useful.

In my project, the current Surefire report counts 3105 tests, which practically all use JMockit, version 1.24. Unfortunately, it's impossible to switch to the current version.

**Comment by rliesenfeld** [comment]
I have written lots of tests for code that didn't originally had tests too (most of those 1400 tests fall in this category). My impression is that most developers don't even try to create proper tests, reaching for mocking libraries by default. The testing approach I use (basically what's shown in the "petclinic" sample) works fine for legacy code.

**Comment by wacker** [comment]
Strange to read the author of J**Mock**it advocate against mocking.

The [PetClinic Sample](https://github.com/jmockit/jmockit1/tree/master/samples/petclinic) in fact does not use mocking. Also, it only contains *integration tests* requiring a database and does **not** contain any ([solitary](http://blog.jayfields.com/2014/07/solitary-unit-test.html)) unit tests. When executed, it only uses **16%** (2109/13264 lines) of JMockit.

Sorry for the sarcasm, but following your reasoning, why don't you deprecate and subsequenty remove the remaining 84% of JMockit as well?

**Comment by rliesenfeld** [comment]
What do you mean, "only uses 16% of JMockit"? No, the tests in the Petclinic sample test suite exercise close to 100% of the code under test in that module.

And yes, they *are* integration tests, never said otherwise. I can see your problem is that you are new to automated developer testing, and problably a novice developer too. I have been doing this for 15 years now, and also thought that isolated unit tests could be a good idea years ago, when I was still naive about the subject.

**Comment by wacker** [comment]
I try not to fall for dogmatic views about the use of tools but that's irrelevant since my point is observational:

You advise against unit testing and against the use of mocking, fine. Consistently, petclinic does not make use of any API from JMockit besides `mockit.Tested`. No `Expectations`, no `Verifications`, no `@Mocked` or `Delegate`.

When you execute the petclinic integration tests, only 16% of the lines of code that `jmockit-1.49.jar` is made of are utilized.

Now following you argument, since petclinic is the only legitimate approach to testing in your opinion, will you follow this through and deprecate `Delegate`, `@Mocked`, ... as well i.e. the remaining 84% of JMockit, just as you did with `withArgThat()` and the other features mentioned?

If you see a reason to keep those, face the questions in this thread. If not, go ahead and strip the API down to just `@Tested`, your pet project won't suffer.

**Comment by rliesenfeld** [comment]
"When you execute the petclinic integration tests, only 16% of the lines of code that jmockit-1.49.jar is made of are utilized (measured with IntelliJ coverage)." Huh, yes, so what? That is a *sample test suite* for *sample of code under test*, not a test suite for JMockit itself!

**Comment by rliesenfeld** [comment]
"Now following your argument, since petclinic is the only legitimate approach to testing in your opinion, will you follow this through and deprecate Delegate, @Mocked, ... as well i.e. the remaining 84% of JMockit, just as you did with withArgThat() and the other features mentioned?"

Do you realize the non-sense you're saying?

**Comment by wacker** [comment]
Yes, because I cited _you_ for the most part. Admittedly, the deduction I added was of sarcastic nature. But how else to reach someone who became dogmatic and bitter about (actually some pretty good) code written in a course of 15 years?
