### ISSUE TITLE
JEE Section 2 Documentation is missing.  Is there a previous version of the doc which has it?

### ISSUE THREAD

**Issue by benze** [jmockit/jmockit1#676]
I was reading the online documentation for jMockit  https://jmockit.github.io for JEE & Spring Apps, and noticed that Section 2 (Interfact Resolution) is missing/empty.  See https://jmockit.github.io/tutorial/EnterpriseApplications.html#testedObjects.

Is this section simply not written yet, or has it accidentally been dropped from an earlier version of the site?  I tried to find the documentation on github to look at earlier versions, but cannot find it anywhere in the repo.

Does a jMockit user-group still exist anywhere to ask these kinds of questions, or is everything on github/stackoverflow only?

**Comment by rliesenfeld** [comment]
It's not written yet.
