### ISSUE TITLE
use  feild “instrumentation”，but no  check

### ISSUE THREAD

**Issue by maming123450** [jmockit/jmockit1#678]
Please provide the following information:

* Version of JMockit that was used: 
1.49
* Description of the problem or enhancement request:
mockit.internal.startup
function ：retransformClass
sometimes error config will leading the error “-javaagent”。In this  way  ，run  test  allways be  “java.lang.NullPointerExceptione”，and only this info。it should   use  verifyInitialization（），before use instrumentation；
* Check the following:

 - [ ] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
??? "Description of the problem" means you are supposed to describe the problem...
