### ISSUE TITLE
Capturing new instances is no more working

### ISSUE THREAD

**Issue by rlagoue** [jmockit/jmockit1#679]
Please provide the following information:

* Version of JMockit that was used:  1.48 

* Description of the problem or enhancement request:
This issue starts with version 1.48.  It is easy to reproduce, just try to mock a constructor by using new instances capturing as described [here](https://jmockit.github.io/tutorial/Mocking.html#capturingNewInstances).

The execution process will step inside the body of the constructor expected to be mocked.
Moving back to version 1.47, solves the issue.

**Comment by rliesenfeld** [comment]
Seems to be working fine in 1.49.
