### ISSUE TITLE
Support for mocking private methods

### ISSUE THREAD

**Issue by hemanthrough** [jmockit/jmockit1#682]
I have read all the discussions about why mocking private methods is not continued. but I want to put my stand on this issue. As discussed one of the reasons of using Jmockit was its ability to mock private methods. As repeatedly emphasized by  many developers using various issues #629 #633 , #656  and many. But the dev team dont seems to take heed of our pleas. But as mentioned in this issue #605 we dont have any option other than forking and keeping the ability to mock private methods or moving to another tool which would provide that option for our us.

**Comment by rliesenfeld** [comment]
Same as #629.
