### ISSUE TITLE
Performance issue with Cascading Mocks. (with fix)

### ISSUE THREAD

**Issue by SvenRosvall** [jmockit/jmockit1#685]
* Version of JMockit that was used: 
1.49

* Description of the problem or enhancement request:
Mock cascading feature is causing performance problems. Suggest disabling cascading by default and enabling with annotations.

We have a module that builds in 20 minutes with version 1.12 and later and 2 minutes with 1.9. This has blocked us from upgrading JMockit for several years. We are now forced to use later JMockit because of migration to Java 11.

Mock cascading may be a nice feature but it adds a workload by creating and deleting mocks for every possible function call of a class, regardless if it is used in the test or not. There are issues where this performance problem has been described and performance has not been observed by the JMockit authors. (Thanks to responses in those issues we could track down what caused the performance issue for us.)

I have patched a local clone of JMockit to disable cascading by default and added the cascading attribute. This brings the build time of our module back to 2 minutes.

We see this performance problem growing with the size of the modules. In our smaller modules we cannot see any degradation. But in our biggest module we see a 10x slowdown. This module has 775 test files and 3840 expectation blocks. JConsole shows that 60,000 classes are loaded with current JMockit and only 20,000 with my patched JMockit.

There could also be a performance issue with a sub-optimal algorithm such as lookup with quadratic complexity but I haven't been able to find any such code.

Attaching a patch file with my changes.
[Disable_Mock_Cascading.patch.txt](https://github.com/jmockit/jmockit1/files/4982003/Disable_Mock_Cascading.patch.txt)

**Comment by rliesenfeld** [comment]
I agree that the "cascading" feature, in hindsight, is not worth having. Besides the potential for performance issues, it also has a serious problem which is that it encourages excess mocking.

Personally, I would prefer to drop the feature entirely. Or keep it as it is, since having annotation parameters such as `@Mocked(cascading = true)` is ugly, and it would have to be done with `@Injectable` and `@Capturing` as well.
