### ISSUE TITLE
How to mock private fields with jmockit 1.49?

### ISSUE THREAD

**Issue by Fabriceli** [jmockit/jmockit1#686]
Please provide the following information:

* Version of JMockit that was used:  1.49, jdk 1.8.261

* Description of the problem or enhancement request: 
**How to mock private fields with jmockit? and the 'Deencapsulation.setField' is deprecated, thanks a lot**

* Check the following:

 - [ ] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] If an enhancement or new feature request, it should be justified by an example test
  demonstrating the validity and usefulness of the desired enhancement or new feature.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
See the [release notes](https://jmockit.github.io/changes.html).
