### ISSUE TITLE
Class not mockable

### ISSUE THREAD

**Issue by nealplotnikgit** [jmockit/jmockit1#687]
* Version of JMockit that was used: 1.49

* Description of the problem or enhancement request:
Error: java.lang.IllegalArgumentException: class xxxxxxxxx.ABC is not mockable (mock field "mockABC")

partial test Class:
@Mocked
private ServiceRegistry mockServiceRegistry;
@Mocked
private MAS mockMAS;	
@Mocked
private RDS mockRDS;	
@Mocked
private RDT mockRDT;	
@Mocked
private ABC mockABC;	
...
   @Test
   public void testExecuteAddScheduleCallback() throws CmException {
  new Expectations() {{
	   mockMAS.execute(any); result = new HashMap();
	}}; 
...
facade.executeAddScheduleCallback();  <- this internally uses all above mocked classes. the 1st, 2nd, and 3rd have no problem but when trying to add ABC i get this error

### **Class with issues:**

package xxxxxxxx
import xxxxxxxx.IABC;
 import java.util.Vector;
 public class ABC
   implements IABC
 {
   Object[] data;
   int index;
   
   public ABC(Object[] data)
   {
     this.data = data;
}
...

### **related interface**

package xxxxxx;

import java.util.Enumeration;
import java.util.Vector;

public abstract interface IABC
  extends Enumeration
{
  public abstract int getElementCount();
  
  public abstract boolean hasMoreElements();
  
  public abstract Vector next(int paramInt)
    throws IndexOutOfBoundsException;
  
  public abstract Object nextElement();
  
  public abstract void setIndex(int paramInt)
    throws IndexOutOfBoundsException;
}

**Comment by NagaSiva2611** [comment]
Hi can u provide me the resolution for the above issue, bcoz I am also facing the same. I am able to mock some class using jmockit1.30 but the same class is not mockable using jmockit1.49
