### ISSUE TITLE
JMockit + Jacoco + JDK11 : ArrayIndexOutOfBound

### ISSUE THREAD

**Issue by jbennett2091** [jmockit/jmockit1#688]
Please provide the following information:

* Version of JMockit that was used:   1.49

* Description of the problem or enhancement request:
Enviroment that works JMockit+Jacoco+JDK8, when upgraded to JDK11 causes ArrayIndexOutOfBoundException during test execution.  There have been some related defects raised around this issue (and possibly partially fixed?) (#664) (#615) but I am still seeing issues in the latest versions.  I am including a stripped down example to illustrate as that seems to have been requested

I am using:
- Jmockit 1.49 (current latest)
- Jacoco 0.8.5 (current latest)
- AdoptOpenJDK 11.0.8 hotspot (in contrast to AdoptOpenJDK 1.8.0_262)
- maven 3.6.3 (current latest)
- surefire 3.0.0.M5 (current latest)

* Check the following:
see attached zip
[example.zip](https://github.com/jmockit/jmockit1/files/5157636/example.zip)
[build.log](https://github.com/jmockit/jmockit1/files/5157660/build.log)
[buildDebug.log](https://github.com/jmockit/jmockit1/files/5157661/buildDebug.log)

**Comment by jbennett2091** [comment]
As an experiment, I changed jacoco 0.8.5->0.8.3 and tests run.  This may be a potential work-around for people affected pending an update (from jmockit?).  Supposedly, the jacoco folks have switched to using 'condy' in their latest versions (e.g. 0.8.5), but earlier version (0.8.3) does not have condy.  Per that discussion, jmockit needs to properly support latest-jacoco-using-condy (I am paraphrasing based on what I think I read).

**Comment by rliesenfeld** [comment]
Same as #615.

**Comment by matthiasdenu** [comment]
FYI, I also get this `ArrayIndexOutOfBoundsException` with the following:

```
org.jmockit:jmockit:1.35
org.jacoco:org.jacoco.ant:0.8.7
org.jacoco:org.jacoco.core:0.8.7
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
Apache Ant(TM) version 1.10.12 compiled on October 13 2021
```

I will try the recommendations here and from #615
