### ISSUE TITLE
Fake teardown does not work in IntelliJ test runner

### ISSUE THREAD

**Issue by mrts** [jmockit/jmockit1#689]
* Version of JMockit that was used: 1.44
* Version of JUnit that was used: 5.6.2

* Description of the problem:

According to documentation,

> Once applied, a fake will remain in effect for the execution of all tests in the test class. The scope of a fake applied in a "before" method includes the code in any "after" methods the test class may have (annotated with @After for JUnit or @AfterMethod for TestNG). The same goes for any fakes applied in a @BeforeClass method: they will still be in effect during the execution of any AfterClass methods. Once the last "after" or "after class" method finish being executed, though, all fakes get automatically "torn down".

So I would expect that when I mock the system date in one test, it does not affect other tests.

However, given the following two JUnit 5 test classes:

**MockedDateTest**

```java
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class MockedDateTest {

    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");

    @Override
    @BeforeEach
    public void setup() {
        var mockedDate = DATE_FORMAT.parse("2020-04-11");
        new MockUp<System>() {
            @Mock
            public long currentTimeMillis() {
                return mockedDate.getTime();
            }
        };
    }

    @Test
    public void dateShouldBeMocked() throws ParseException {
        assertThat(new Date())
            .isEqualTo(DATE_FORMAT.parse("2020-04-11"));
    }
}
```

**RealDateTest**

```java
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class RealDateTest {

    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");

    @Test
    public void dateShouldNotBeMocked() throws ParseException {
        assertThat(new Date())
            .isNotEqualTo(DATE_FORMAT.parse("2020-04-11"));
    }
}
```

when I run the test suite that contains both of them in IntelliJ 2020.2 test runner, then I see that the mocked date leaks into `RealDateTest` and the `RealDateTest.dateShouldNotBeMocked()` fails.

When I run the test suite with Maven from command line with `mvn test`, then `RealDateTest.dateShouldNotBeMocked()` succeeds, so this is related to IntelliJ test runner.

**Comment by mrts** [comment]
Perhaps you could consider reviving explicit mock teardown to avoid issues like this?

**Comment by rliesenfeld** [comment]
See #583. Tear-down actually works, that is not the real issue, but the fact that the JVM does not support restoring a *native* method that was redefined with bytecode. That's why JMockit dropped the support for @Mock on native methods in version 1.47.
