### ISSUE TITLE
No more  release after dec 2019?

### ISSUE THREAD

**Issue by mnadeem** [jmockit/jmockit1#724]
Is this project actively maintained ?

**Comment by abtabhi** [comment]
yeah we are also looking answer for the same question @ihoro is the project maintained ?

**Comment by phakamiles** [comment]
Co Ask!

**Comment by ihoro** [comment]
> yeah we are also looking answer for the same question @ihoro is the project maintained ?

Unfortunately, I’m not aware of this project’s status. I’m not its author or maintainer.

**Comment by rliesenfeld** [comment]
It's not currently active. I do use the library daily in a real project, though, with Java 17.

**Comment by abtabhi** [comment]
but does your project works with jacaco with the fix present in https://github.com/jmockit/jmockit1/pull/665. can we please merge this change.
