### ISSUE TITLE
Fix regressions in JMockit 1.9 in the support for mocking of Android classes under the Robolectric test runner

### ISSUE THREAD

**Issue by rliesenfeld** [jmockit/jmockit1#8]
In JMockit 1.8, Robolectric-based tests using JMockit to mock Android classes were working, but changes in version 1.9 broke them.

**Comment by markshiz** [comment]
I am experiencing the same issue.  Since this has been open for 9 mos. now, I'm curious, is there a recommended fix?

**Comment by rliesenfeld** [comment]
I don't develop Android apps, so this will require assistance from the user community. Closing for now, can be reopened if there is interest.

**Comment by janiduw** [comment]
I'm using Jmockit 1.8 since the latest version does not work with Robolectric. Tests are running perfectly fine for me on MacOSX but on linux I get a RuntimeException java.lang.RuntimeException: Unable to mock class org.webrtc.PeerConnection due to a missing dependency
