### ISSUE TITLE
JMockit 1.12 causes java.lang.LinkageError when used with Jacoco

### ISSUE THREAD

**Issue by henryken** [jmockit/jmockit1#87]
Hi,

I have an issue when using JMockit 1.12 with Jacoco.
The last working JMockit version is 1.9.

The following is my stack:
- Java 1.8.0_20
- JMockit 1.12
- Jacoco 0.7.2.201409121644

java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name

**Comment by jeffrey-yan** [comment]
I am still experiencing this issue with JMockit 1.19.
