### ISSUE TITLE
Add Osgi meta information to your MANIFEST.MF file

### ISSUE THREAD

**Issue by SimonScholz** [jmockit/jmockit1#91]
Your mocking framework looks really interesting, but unfortunately I cannot easily give it a try, because it does not contain necessary Osgi information.

Can you please provide these so that I can also use your framework in a Osgi environment?
I could do it myself, but it's better if you directly provide your jars Osgi conform.

Thanks in advance.

**Comment by rliesenfeld** [comment]
Even adding OSGi entries to MANIFEST.MF is not so easy. This enhancement will require help from the user community. Closing for now, can reopen if there is interest.
