### ISSUE TITLE
Validate that no conditionals appear inside expectation recording block

### ISSUE THREAD

**Issue by rliesenfeld** [jmockit/jmockit1#97]
For verification blocks, conditionals need to be allowed in assertions, at least.

**Comment by topsy-turvy** [comment]
Hello. I have the following code

new StrictExpectations(accountInfoUpdater) {
            {
                for (int i = 0; i < squadRequests.length; ++i) {
                    accountInfoUpdater.updateAccountInfo(squadRequests[i]);
                }
            }
        };

It checks that 'updateAccountInfo' was called for each squadRequests member. I'm not sure I understand how it should look like now. Could you assist?

**Comment by rliesenfeld** [comment]
I would probably capture the arguments passed in multiple calls to "updateAccountInfo" into a List, then check the contents of the list afterwards:

    final List<AccountInfo> updatedSquadRequests = new ArrayList<>();
    new Expectations() {{
        accountInfoUpdater.updateAccountInfo(withCapture(updatedSquadRequests));
    }};
    // call SUT
    assertArrayEquals(asList(squadRequests), updatedSquadRequests);

Even better, use a verification block (unless partial mocking of "accountInfoUpdater" really is needed):

    // call SUT

    new Verifications() {{
        List<AccountInfo> updatedSquadRequests = new ArrayList<>();
        accountInfoUpdater.updateAccountInfo(withCapture(updatedSquadRequests));
        assertArrayEquals(asList(squadRequests), updatedSquadRequests);
    }};

**Comment by topsy-turvy** [comment]
Thank you rliesenfeld,

The first sample with Expectations works.
